### ISSUE TITLE
Julia and deploying complex graphical applications for laypeople | Vexatos, Cruor | JuliaCon2201

### ISSUE THREAD

**Issue by MillironX** [JuliaCommunity/YouTubeVideoTimestamps#105]
Here's a great video that needed some love.

Speaker: Vexatos & Cruor
Video Title: Julia and deploying complex graphical applications for laypeople | Vexatos, Cruor | JuliaCon2201
Link: https://youtu.be/q-78N_bEf90

0:08 - Introduction
0:30 - Background
1:00 - Maple
1:35 - Ahorn
1:55 - Working with Julia
2:33 - The Challenges
2:58 - The "Solution"
3:16 - Where it failed
4:18 - Julia 1.0 Salvation
4:43 - How it got better
5:12 - Where we are now
5:44 - GTK comparison
5:59 - Updates on Ahorn
6:26 - Julia in Hindsight
6:45 - How it can get even better
7:24 - The biggest improvement wanted
7:36 - Conclusion, link: https://github.com/CelestialCartographers/Ahorn

**Comment by logankilpatrick** [comment]
Thank you very much!
