### ISSUE TITLE
What's Bad About Julia - Jeff Bezanson

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#107]
Hello.

I'm a fan of this particular video [https://www.youtube.com/watch?v=TPuJsgyu87U](https://www.youtube.com/watch?v=TPuJsgyu87U). So if you considered timestamps to be valuable addition to it, I will try to cut my teeth on it.

If so, I have a question. Different videos have slightly different style of timestamps. For example _Working with images in Julia_ [https://www.youtube.com/watch?v=DGojI9xcCfg](https://www.youtube.com/watch?v=DGojI9xcCfg) use format
> 0:00 Welcome
> 1:00 First topic

while _How to install Julia and Pluto_, [https://www.youtube.com/watch?v=OOjKEgbt8AI](https://www.youtube.com/watch?v=OOjKEgbt8AI) use format
> 0:00 - Welcome
> 1:00 - First topic

and there is probably dozen of other conventions that they used. Are any particular guidelines that I should follow or I just trust my taste?

Best,
Kamil

**Comment by KZiemian** [comment]
I read some many timestamps over last few days, that I decided to give it a try, without waiting for more guidelines. If they are bad, it is my fault, you can change anything to improve it. And I know my English is bad, so you also need to change this.

00:00 Welcome!
00:50 Purpose of the talk
02:04 Users should speak about their problems with Julia
02:34 Widely know bad things about Julia
06:54 Is the presented list of problems exhaustive?
07:30 Why some problems were chosen as the main topics of this talk
07:53 Modularity
09:14 Example of modules we want to keep separate
12:03 Problem with isolating constructors
13:01 Types
14:06 How to handle Missing type in code
15:17 Compiler problem with some types definitions
16:25 Opaque method specificity rules
17:40 First, the most important rule of method specification
18:09 Second "rule" of method specification
18:45 Why we have problem with second "rule"
21:34 Problem of "X is more specific that Y. Example 1
23:32 Problem of "X is more specific that Y. Example 2
25:20 Conclusions
26:15 Q&A: What would happens in the case of circular specification?
27:09 Q&A: What would happens if specification rules were stricter?
27:52 Q&A: How many methods need to be write to allow to make specifications rules stricter? (Follow up to previous question.)
28:18 Q&A: What is the order of priority of fixing well know bad things in Julia?
28:44 Q&A: What is last big Julia's problem that was fixed, according to Jeff Bezanson?
29:38 Q&A: How much better or worse world be without unions?

Best,
Kamil

**Comment by logankilpatrick** [comment]
This is great, I added these.
