### ISSUE TITLE
JuliaCon 2020 | Keynote: Scientific Machine Learning | Prof Karen Willcox

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#108]
_JuliaCon 2020 | Keynote: Scientific Machine Learning | Prof Karen Willcox_, [https://www.youtube.com/watch?v=Bk4PJnjuPps](https://www.youtube.com/watch?v=Bk4PJnjuPps)

I will try to make timestamps to this video to the end of the week. I'm not promise anything, since this video, which I like and already watch it twice, can be too hard to me to grasp enough to to make desired timestamps.

**Comment by KZiemian** [comment]
_JuliaCon 2020 | Keynote: Scientific Machine Learning | Prof Karen Willcox_, [https://www.youtube.com/watch?v=Bk4PJnjuPps](https://www.youtube.com/watch?v=Bk4PJnjuPps)

It was quite a challenge, but here is my attempt at making timestamps to this lecture. You can change anything, especially my bad English, if you want.

00:00 Welcome and information about JuliaCon 2020
01:42 Introduction and acknowledgments
02:50 Outline of the talk
03:25 What is Scientific Machine Learning (SciML)?
05:04 What are the opportunities and challenges of SciML?
10:32 BIG DATA alone is not enough
11:27 Using physics base models means that we are doing Computational Science
13:19 Problem 1: Complex multiscale multiphysics phenomena
14:46 Problem 2: High dimensional parameters
15:54 Problem 3: Data are sparse, intrusive and expensive to acquire
16:48 Problem 4: Rare events
17:33 Problem 5: Uncertainty qualification
18:11 SciML and Computational Science, summary
18:47 Example: flow inside a rocket engine combustor
20:08 Example: equations of flow inside a rocket engine combustor
20:41 Physics-based model are powerful but computational expensive
23:10 Overview of model reduction methods
26:04 Similarities and differences between model reduction and ML
27:17 Can we have best of two words (model reduction and ML)?
30:05 Overview of Lift & Learn approach
33:00 Example: Lift & Learn approach to 2D flow in a rocket engine
34:34 Example: Training of the model
36:04 Example: Comparing results for pressure and temperature
37:38 Outlook of Sci ML
38:42 Diverse future of computational science and programming languages
39:31 Q&A: Advice for people bringing ML approach to scientific problems
42:09 Q&A: Pitfalls of interplay between domains knowledge and ML
43:33 Q&A: Does presented approach improves fidelity of solution of highly non-linear systems?

**Comment by logankilpatrick** [comment]
This is great! Thanks : )
