### ISSUE TITLE
JuliaCon 2018 | Native Elementary Functions in Julia | Patrick Kofod Mogensen

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#109]
_Native Elementary Functions in Julia_, [https://www.youtube.com/watch?v=B03F6EFUm78](https://www.youtube.com/watch?v=B03F6EFUm78)

I'm interested in this topic and since no one reserve this talk, I will try to make timestamps for it. Inform me if it takes much, much to long for such short talk to work it out.

**Comment by KZiemian** [comment]
_Native Elementary Functions in Julia_, [https://www.youtube.com/watch?v=B03F6EFUm78](https://www.youtube.com/watch?v=B03F6EFUm78)

It was small challenge, I don't hear to well question on 12:07, so what I write at this timestamp is to some extents guess work. Change anything that you find bad or wrong in them.

00:00 Welcome
00:25 Speaker introduction
00:53 How I get involved in this project?
01:59 What is a libm?
03:30 Types of algorithms for evaluating mathematical functions
04:55 Why use range reduction?
05:26 Why use polynomials?
05:47 Numerical algorithm and multiple dispatch
07:50 Previous Julia's standard mathematical libraries
08:38 Julia's standard mathematical libraries today
09:05 Challenges that I faced
10:36 What mathematical functions are missing?
11:02 Future of Julia's standard mathematical libraries
12:07 Q&A: Can you do clibm in Julia now?
12:47 Q&A: Do you measure speed of functions new implementations?

**Comment by logankilpatrick** [comment]
Added, thank you!
