### ISSUE TITLE
JuliaCon 2017 | The State of the Type System | Jeff Bezanson

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#110]
_The State of the Type System_, [https://www.youtube.com/watch?v=Z2LtJUe1q8c](https://www.youtube.com/watch?v=Z2LtJUe1q8c)

Topis is very interesting, I hope that I can understand it enough to make some timestamps.

**Comment by logankilpatrick** [comment]
Hey @KZiemian no need to open issues until you have the timestamps complete

**Comment by KZiemian** [comment]
No problem to me, but on main page of this repository we can read

> Open a new issue with the videos title to "claim" the video such that there's no overlapping work

I can see that there is no big competition to me now ;), but I try to follow all the rules.

**Comment by KZiemian** [comment]
_The State of the Type System_, [https://www.youtube.com/watch?v=Z2LtJUe1q8c](https://www.youtube.com/watch?v=Z2LtJUe1q8c)

Making this timestamps was a lot of fun, but there still may be bad. Corrected anything you want.

00:00 Welcome!
00:39 What is the type system?
02:52 History of Julia type system
03:40 First interesting change: reworking tuples in v0.4
05:29 Changes introduced in v0.5
06:21 Overview of type systems evolution in versions 0.1-0.5
06:45 With v0.6 type system changed in a big way
07:02 Questions about type system that was left open in v0.5
08:24 Semantic subtyping
09:51 Example of defining type using "where": Array
10:51 Example of type instatiation: Array{Float32, 2}
12:50 Implications of mechanism of type instatiation
14:40 Variables with bounds that depends on outer variables
16:11 Example: Array eltype
17:10 Syntactic sugar
18:41 New subtyping algorithm
20:47 Examples: subtyping
23:53 New algorithm for type intersection
25:59 Summary of type system in v0.6
26:22 Three categories of future improvements
28:36 Possible future type system features

**Comment by logankilpatrick** [comment]
Thank you for adding these!
