### ISSUE TITLE
Jeff Bezanson, "Introduction to Julia Internals", JuliaCon 2014

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#111]
Jeff Bezanson _Introduction to Julia Internals_, [https://www.youtube.com/watch?v=osdeT-tWjzk](https://www.youtube.com/watch?v=osdeT-tWjzk)

It is quite old, so I guess no one will want timestamp to it. But inform me if I work on it for too long. Stefan Karpinski said about it ["Still mostly accurate, I suspect"](https://discourse.julialang.org/t/is-jeff-bezansons-2014-introduction-to-julia-internals-relevant-in-2021-onward/73255/2?u=kziemian).

**Comment by KZiemian** [comment]
This is the best I can do. Feel free to change and correct all you want.

00:00 Origin story
00:28 Aim of the talk
00:57 Three component of programming language: data model, code model, glue
03:02 Tag-bits arrangement
04:34 Type primitives
05:45 Object graph of types
06:48 Code object primitives
07:41 Code intrinsics
08:15 Translation stages
10:09 Test subject
10:17 Julia is just lisp
12:04 "You can call various functions, that are of curse not documented."
14:03 Parsed test subject code
16:00 Expanding macros
17:17 Syntax de-sugaring
18:52 Are |#s number| symbols related to LLVM code?
19:23 Statementize control flow
20:18 Flattening code using goto from
21:47 Flattened code in @code_lovered form
22:13 Would it be any worth in reading code in goto form?
22:53 Why we have in code statements like "6: goto 7"?
23:45 Running the code
24:51 Method cache (file gf.c)
27:23 Overview of type inference
28:30 Compile-time method lookup and secret internal function
30:07 Type inference (file inference.jl)
30:50 Inlining, high-level optimisation
31:32 LLVM IR generation
31:42 Code generation key concepts
32:52 emit_expr and emit_function
35:03 Type translation between Julia and LLVM
35:35 Q&A: When is the most time spent at runtime?
36:30 Q&A: Do you plan to extend syntax to add new feature?
37:24 Q&A: Do LLVM and garbage collector allow static analysis?
38:52 Q&A: Stack and heap allocation
39:16 Q&A: Can I press button and get graph of whole architecture?
39:43 Q&A: Better mechanism for simple unions
40:17 Q&A: Types lookup and exponential complexity
40:50 Q&A: How many types Julia look up before
42:01 Q&A: How "widening" of types works?
43:27 Q&A: What are the heuristic that decided that something is inline or not?

**Comment by logankilpatrick** [comment]
Added this! Thanks.
