### ISSUE TITLE
LatticeQCD.jl: Simulation of quantum gauge fields, JuliaCon 2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#112]
LatticeQCD.jl: Simulation of quantum gauge fields, [https://www.youtube.com/watch?v=2OQYyRlUi_k](https://www.youtube.com/watch?v=2OQYyRlUi_k)

Correct them in any way you want.

00:00 Welcome!
00:29 Overview of presentation
01:01 What is lattice QCD?
01:50 Difference between classical and quantum field
02:46 Overview of typical lattice QCD computation
03:35 List of publicly available lattice QCD codes
03:53 Why we make new code?
04:42 How to use LatticeQCD.jl?
06:17 Benchmarking LatticeQCD.jl against other codes
06:39 Parallelization in Julia 1.6 is not enough
07:18 Linear algebra side of the problem
08:15 Summary

**Comment by logankilpatrick** [comment]
Added, thank you!
