### ISSUE TITLE
JuliaCon 2021 | Day 1 Single Track | Prof. Jan Vitek Keynote

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#113]
JuliaCon 2021 | Day 1 Single Track | Prof. Jan Vitek Keynote
[https://www.youtube.com/watch?v=LT4AP7CUMAw](https://www.youtube.com/watch?v=LT4AP7CUMAw)

This was hard, but satisfying lecture to do. Again, change anything you want

00:00 Welcome!
01:28 Information about JuliaCon 2021
02:53 Schedule and organization of the JuliaCon 2021
05:21 Introduction of prof. Jan Vitek
07:16 Prof. Jan Vitek "Julia: Great language or the greatest language"
07:54 Why we still inventing, adopting and abandoning programming languages?
09:17 How to revolutionize scientific programming?
10:11 Programming languages landscape
11:50 What we learned in the last 20 years?
14:10 Intel project on parallel accelerator
15:38 Publishing papers on Julia
16:59 Our first paper: Julia is fast
19:15 Julia implementation
19:56 Julia design
21:33 Julia coding style
22:29 Implementation, design and code style make Julia fast
23:06 Second paper: formalizing Julia subtyping algorithm
25:54 Defining rules of subtyping
27:03 Normalization of types
27:35 Normalization of types is in the exponentially complexity class
28:09 Representing types as trees
29:15 Third paper: rational reconstruction of Julia subtyping
31:03 Who is right?
31:50 Subtyping parametric types
36:26 The diagonal rule
37:47 Julia type system isn't decidable, what we will do with it?
39:48 Fourth paper: eval and world age
42:30 Fifth paper: type stability and type grounded
45:51 Q&A: What are the promising techniques from JIT theory that weren't put into practice?
47:39 Q&A: What are the barriers for Julia reaching speed of C?
48:58 Q&A: Is the concept of programming from time before 2010 still relevant in 2021?

I written down all the papers that I see in the presentation, maybe you found it useful. I open [discussion](https://discourse.julialang.org/t/adding-more-links-to-materials-on-julia-yt-channel/73264) about that.

Todd A. Anderson et al., "Parallelizing Julia with a Non-Invasive DSL",
DOI: 10.4230/LIPIcs.ECOOP.2017.4

Jeff Bezanson et al, "Julia: dynamism and performance reconciled by design"
[https://doi.org/10.1145/3276490](https://doi.org/10.1145/3276490)

Benjamin Chung, Francesco Zappa Nardelli, Jan Vitek, "Julia’s Efficient
Algorithm for Subtyping Unions and Covariant Tuples",
DOI: 10.4230/LIPIcs.ECOOP.2019.24

Francesco Zappa Nardelli et al., "Julia subtyping: a rational
reconstruction", [https://doi.org/10.1145/3276914](https://doi.org/10.1145/3276914)

Julia Belyakova et al., "World age in Julia: optimizing method dispatch in
the presence of eval",
[https://doi.org/10.1145/3428275](https://doi.org/10.1145/3428275)

Artem Pelenitsyn et al., "Type Stability in Julia: Avoiding Performance Pathologies in JIT Compilation", https://doi.org/10.1145/3485527, [arXiv:2109.01950](https://arxiv.org/abs/2109.01950)

**Comment by logankilpatrick** [comment]
Added! I don't think the papers are as relevant here but thank you for adding them!
