### ISSUE TITLE
FunSQL: a library for compositional construction... | Clark C. Evans, Kyrylo Simonov | JuliaCon2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#114]
FunSQL: a library for compositional construction... | Clark C. Evans, Kyrylo Simonov | JuliaCon2021 [https://www.youtube.com/watch?v=rGWwmuvRUYk](https://www.youtube.com/watch?v=rGWwmuvRUYk)

It was hard thing to do. I not very good at SQL and talk is very fast, but maybe it still can be useful.

00:00 Welcome!
00:10 FunSQL.jl? Who needs it?
00:39 Problem: query depending on user input
01:47 Query algebra
02:11 Scheme of data base
02:56 Describing scheme of data base in FunSQL.jl
03:17 Cratering query
04:12 Bound and unbound references
04:57 Generating SQL function
05:21 JOIN clause
06:36 Example: using JOIN to create query
07:05 SQL and FunSQL.jl grammar can differ
08:31 (query algebra) How FunSQL.jl query constructor works
09:47 FunSQL.jl special set of constructors
11:03 Inspecting query object
11:58 Query parameters
12:29 Correlated queries
13:39 FunSQL.jl syntax for correlated queries
14:42 Aggregate functions
17:17 Window functions
18:12 In FunSQL.jl aggregate and window functions use the same notation, but different constructors
19:16 Example: merging overlapping visits
20:44 Conclusions
20:58 Example: solving problem from the beginning of the talk
21:47 Current state of FunSQL.jl and plans for the future

**Comment by logankilpatrick** [comment]
I think this is a duplicate, closing for now.
