### ISSUE TITLE
A mathematical look at electronic structure theory | Workshop | JuliaCon 2021. Timestamps by Tae Hee Ko

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#115]
_A mathematical look at electronic structure theory_, [https://www.youtube.com/watch?v=HvpPMWVm8aw](https://www.youtube.com/watch?v=HvpPMWVm8aw)

Author of this timestamps is Tae Hee Ko, NOT me. He/she put it into commentary and I allow myself to make few cosmetic changes and put them here.

00:00 Welcome!
26:56 DFT formulation
31:13 Definition of SCF
1:12:03 Simple mixing
1:19:16 Anderson mixing
2:38:16 How to compute forces
2:41:07 Finite difference method
2:42:11 Forward diff
2:43:13 How to compute stresses

**Comment by logankilpatrick** [comment]
Added!
