### ISSUE TITLE
Corrections to timestamps of various videos

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#116]
Since issue _Mistakes and typos in Julia YT video's timestamps #106_ is already very long, I believe that opening another with proposition of corrections of miscellaneous timestamps is a good idea. Hopeful I'm not wrong.

_Package development: improving engineering quality & latency | Workshop | JuliaCon 2021_, [https://www.youtube.com/watch?v=wXRMwJdEjX4](https://www.youtube.com/watch?v=wXRMwJdEjX4)

Division of progress bar (?) in chapter doesn't work. I believe changing
> 0:20 Julia internals: compiler specialization, dispatch, backedges, invalidation, precompilation
> 31:50 Catching errors and inference failures with JET

to 
> 00:00 Welcome!
> 00:20 Julia internals: compiler specialization, dispatch, backedges, invalidation, precompilation
> 31:50 Catching errors and inference failures with JET

will solve the problem.

**Comment by logankilpatrick** [comment]
Fixed this, thanks!
