### ISSUE TITLE
JuliaCon 2020 | `SymbolicTensors.jl` -- high-level tensor manipulation in Julia | Robert Rosati

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#117]
_JuliaCon 2020 | `SymbolicTensors.jl` -- high-level tensor manipulation in Julia | Robert Rosati_, [https://www.youtube.com/watch?v=_b4JIv044GY](https://www.youtube.com/watch?v=_b4JIv044GY)

This is what I can do.

00:00 Welcome!
00:21 Introduction
00:47 Informal introductions to tensors
01:45 Aim of the SymbolicTensors.jl
02:36 Example of using SymbolicTensors.jl
03:32 Improving SymPy capabilities
04:30 Support for derivatives of tensors
05:06 Simplification option
05:40 SymbolicTensors.jl and General Relativity
06:23 Generating SymPy expressions
07:08 Benchmarking
08:05 Summary
08:37 Acknowledgments

**Comment by logankilpatrick** [comment]
Added!
