### ISSUE TITLE
Partitions and chains: enabling batch processing for your data | Jacob Quinn | JuliaCon2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#120]
_Partitions and chains: enabling batch processing for your data_, [https://www.youtube.com/watch?v=Ryp0F0dHnLA](https://www.youtube.com/watch?v=Ryp0F0dHnLA)

Maybe this timestamps find some use. I'm not satisfied by them.

00:00 Welcome!
00:11 Introduction
00:24 Working with the tables
02:06 [TableOperations.jl](https://github.com/JuliaData/TableOperations.jl)
03:48 ChainedVector type
05:17 Examples of using ChainedVector type
07:31 Ending thought and information

**Comment by logankilpatrick** [comment]
Added, thank you!
