### ISSUE TITLE
Q&A: Julia Core Team Panel | JuliaCon 2014

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#123]
_Q&A: Julia Core Team Panel_, [https://www.youtube.com/watch?v=2CdtvRKVuhE](https://www.youtube.com/watch?v=2CdtvRKVuhE)

In the timeline of Julia language this panel is from the time of middle Roman Empire, but when I once decide to do something, generally it is better for me to do it than not, so here you have it. I hope that timestamps are not too bad.

I had a problem with 13:11, so I put question mark there. You should check yourself if this timestamps is correct.

00:00 Welcome!
00:47 Stefan Karpinski, introduction
01:17 Jameson Nash, introduction
01:49 Keno Fisher, introduction
02:58 Viral Shah, Jeff Bezanson, introduction
03:12 Alan Edelman, introduction
04:17 Computation on GPUs
06:21 "My preferred approach: to hope that GPUs go away"
06:45 Problems with GPUs
09:36 Better implementation of strings in Julia
13:11 What would happen if money runs out? (?)
14:15 Who is in the Julia core team?
14:44 Getting founding for Julia
16:11 Performance and functional programming in Julia
19:29 Balance between performance, features and correctness of implementation in Julia releases
22:21 GC improvements
23:49 Julia environment
28:49 Control flow comprehensions

**Comment by logankilpatrick** [comment]
Added, thank you!
