### ISSUE TITLE
FourierTools.jl Working with the Frequency Space | Felix Wechsler, Rainer Heintzmann | JuliaCon2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#124]
_FourierTools.jl Working with the Frequency Space_, [https://www.youtube.com/watch?v=qYgJDb_Ko2E](https://www.youtube.com/watch?v=qYgJDb_Ko2E)

00:00 Welcome!
00:14 Overview of FourierTools.jl
00:48 Mathematical definition of Fourier transform
01:39 Fast Fourier Transform (FFT)
02:07 Functionality of FourierTools.jl
04:51 Calculate sinc interpolation
06:17 Fourier Shift Theorem
07:05 Convolution
07:25 Final information and thoughts

**Comment by logankilpatrick** [comment]
Thank you!
