### ISSUE TITLE
State of DataFrames.jl | Bogumił Kamiński | JuliaCon 2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#126]
_State of DataFrames.jl_, [https://www.youtube.com/watch?v=ErAAV4u2Fuk](https://www.youtube.com/watch?v=ErAAV4u2Fuk)

I hope that these timestamps are good enough. I want to make some good one for this presentation, but I feel that I miss the mark. Feel free to change everything.

00:00 Welcome!
01:20 What is [JuliaData](https://github.com/JuliaData)?
01:35 Place of [DataFrames.jl](https://github.com/JuliaData/DataFrames.jl) in [JuliaData](https://github.com/JuliaData) landscape
02:11 [DataFrames.jl](https://github.com/JuliaData/DataFrames.jl): designed with production in mind
04:44 Key features of [DataFrames.jl](https://github.com/JuliaData/DataFrames.jl)
06:57 DataFrames.jl development survey, July 2020, [Julia Discourse](https://discourse.julialang.org/t/dataframes-jl-development-survey/44022)
07:32 With arriving of version 1.0 [DataFrames.jl 1.0](https://github.com/JuliaData/DataFrames.jl) API is now stable
08:59 Performance
10:30 Compilation latency
12:19 "Source => transformation => target" minilanguage
13:23 The ecosystem
13:53 Plans for the future
14:16 Closing remarks

**Comment by logankilpatrick** [comment]
Thanks!
