### ISSUE TITLE
JuliaCon 2021 | Day 2 Single Track | Dr. Xiaoye (Sherry) Li Keynote

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#127]
JuliaCon 2021 | Day 2 Single Track | Dr. Xiaoye (Sherry) Li Keynote
[https://www.youtube.com/watch?v=sUyddZQaeyg](https://www.youtube.com/watch?v=sUyddZQaeyg)

I have big doubts about these timestamps, you should read them carefully.

00:00 Welcome!
02:03 Introduction by the speaker
02:32 Acknowledgments
03:05 Algebraic solvers are fundamental tools
04:36 Mathematical libraries in which development we were involved
05:44 Two main themes of the talk
06:09 Kernel methods in ML
07:24 Kernel Ridge Regression (KRR)
09:59 Solving large sense linear systems
10:53 Low-rank compression
13:02 Classes of low-rank structured matrices
13:51 Cluster tree of matrix
15:10 Fast algebraic algorithm: sketching
16:45 Problem: we don't know target rank
17:19 Stochastic norm estimation
18:15 Example: compression of HSS matrix
19:17 Fast geometric algorithm: approximate nearest neighbor
21:27 Approximate nearest neighbor with iterative merging
22:51 Comparison of algebraic and geometric algorithms
23:50 [STRUMPACK](https://github.com/pghysels/STRUMPACK) (STRUctured Matrix PACKage)
25:13 Linear algebra and machine learning
27:09 Bayesian optimization
28:19 Modeling phase
29:05 Search phase
29:37 Parallelization of code execution
29:55 Examples of ML improved linear algebra computations
31:45 Summary
33:09 Q&A: What do we need more: linear algebra code for new architectures or for new applications?
33:59 Q&A: How we can give users ability of using ML to get performance?
34:55 Q&A: What developments you want to see in the Julia ecosystem?
35:41 Q&A: What high performance algorithms can make use of specific code generation?
36:37 Q&A: Do you think that Julia can replace C++ as language for linear algebra?
37:32 Q&A: Do you search for rank revealing LU?
38:58 Announcements

**Comment by logankilpatrick** [comment]
Awesome, thanks!
