### ISSUE TITLE
JuliaCon 2020 | Minisymposium on Partial Differential Equations BEAST.jl | Kristof Cools

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#128]
JuliaCon 2020 | Minisymposium on Partial Differential Equations BEAST.jl | Kristof Cools [https://www.youtube.com/watch?v=PmJqqqg8bjg](https://www.youtube.com/watch?v=PmJqqqg8bjg)

The more timestamps I had done, the more doubts I have about their quality. For these reason after doing few other from my TO-DO list, I will stop making theme, until someone evaluate these already done and posted here.

00:00 Welcome!
00:38 Class of scattering problems
01:35 Boundary Element Methods (BEM)
02:25 Stating scattering problem in the terms of the boundary values
03:12 Variational formulation of problem boundary value problem
04:03 Goals of package [BEAST.jl](https://github.com/krcools/BEAST.jl)
04:41 Place of [BEAST.jl](https://github.com/krcools/BEAST.jl) in the ecosystem
06:36 Solving scattering problem with [BEAST.jl](https://github.com/krcools/BEAST.jl)
08:45 Post-processing
10:40 Assembly loop
12:49 Parallelism
14:23 [BEAST.jl](https://github.com/krcools/BEAST.jl) and retarded potential integral equations
16:18 Quick overview of other features
18:14 Future work

**Comment by logankilpatrick** [comment]
These look good, thank you!
