### ISSUE TITLE
JuliaCon 2020 | State of Julia | Jeff Bezanson & Stefan Karpinski

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#129]
JuliaCon 2020 | State of Julia | Jeff Bezanson & Stefan Karpinski [https://www.youtube.com/watch?v=xKrIp4ZVOrg](https://www.youtube.com/watch?v=xKrIp4ZVOrg)

Checking my English is always good thing to do.

00:00 Welcome!
00:15 Introduction by Stefan Karpinski
00:58 Multithreading
02:39 Latency: "I think about it everyday, I worry about it every day."
04:54 Debugger for Julia
07:50 Pkg3, Julia package manager
10:51 Package ecosystem
15:21 JuliaMono, Julia typeface
16:16 Where are we now: v1.5
16:48 Multithreading in v1.5
17:49 Why is Julia sometimes slower than C++?
18:11 Heap allocation in Julia
19:49 What is watershed moments in development of language?
20:32 Scope of variable
24:25 Pkg protocol
26:42 [PkgServer.jl](https://github.com/JuliaPackaging/PkgServer.jl) package and servers infrastructure
27:46 Latency still is a problem
28:30 Tasks and threads system
29:47 Compiler: the next generation
31:32 Pkg features coming with Julia v1.6
33:11 The king is dead: Julia 1.0 will stop being LTS version
33:54 Long live the king: Julia 1.6 will be the new LTS
35:37 Amazing progress & bright future
36:17 Thank you!
37:32 Q&A: Does work plan for latency include working on task and threads?
38:14 Q&A: What is the best case scenario for Julia compiler latency?

**Comment by logankilpatrick** [comment]
Thank you!!
