### ISSUE TITLE
JuliaCon 2020 | Keynote: Conic Optimization in Julia and JuMP | Juan Pablo Vielma

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#130]
JuliaCon 2020 | Keynote: Conic Optimization in Julia and JuMP | Juan Pablo Vielma [https://www.youtube.com/watch?v=DGsYIHLnR4U](https://www.youtube.com/watch?v=DGsYIHLnR4U)

This timestamps can be improved. Also, old timestamps are placed in weird place in description, be sure to remove them.

00:00 Welcome!
00:50 What is Conic Optimization (CO)?
01:51 Why we should use CO?
03:00 Overview of Conic Optimization in JuMP
04:12 Example: controlling drone that need avoid some obstacles
07:28 Example: computational results
08:32 Do I really need to learn CO?
09:40 Why using CO? Reason 1: Linear-programming-like duality
11:33 Why using CO? Reason 2: Faster and more stable algorithms
12:21 Historical interplay between JuMP and CO
16:03 Pure Julia-based continuous solvers supporting variety of cones
18:51 [Hypatia.jl](https://github.com/chriscoey/Hypatia.jl) solver
21:35 Interior point algorithms, central path and barriers
24:35 More cones = more smaller models
26:15 Benchmarking [Hypatia.jl](https://github.com/chriscoey/Hypatia.jl)
27:43 Final remarks
29:55 Q&A: In your opinion how macro heavy JuMP is?
31:22 Q&A: How general are cones shown on presentations?
32:31 Q&A: Are there any key problems that you want overcome before release JuMP 1.0?

**Comment by logankilpatrick** [comment]
Great! I forgot I did the intro for this keynote haha
