### ISSUE TITLE
Everything you need to know about ChainRules 1.0 | Miha Zgubič | JuliaCon2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#131]
_Everything you need to know about ChainRules 1.0_, [https://www.youtube.com/watch?v=a8ol-1l84gc](https://www.youtube.com/watch?v=a8ol-1l84gc)

Miha Zgubič post link to slides in comment section, we should consider adding this link to the description. [https://github.com/mzgubic/ChainRulesTalk/blob/master/ChainRules.pdf](https://github.com/mzgubic/ChainRulesTalk/blob/master/ChainRules.pdf)

00:00 Welcome!
00:16 If you want more Julia and less emissions come and join us
00:42 Three main topics of the talk
01:00 JuliaCon 2020 talk in the nutshell
01:30 Overview of the place of ChainRules in ecosystem
02:08 Two kinds of differentiation rules: frule and rrule
02:55 Available kinds of tangent
03:46 Perfect AD system need rules, imperfect one need even more
04:43 Examples in [Zygot.jl](https://github.com/FluxML/Zygote.jl)
05:25 How to write rules?
07:51 Struct gotchas
08:36 @not_implemented macro
09:05 @non_differentiable macro
09:22 @scalar_rule macro
09:47 RuleConfig
12:28 Array dilemma
15:30 Two new functionality arising form array dilemma: ProjectTo and @no_rrule
16:40 Error on slide 43, see description of this video
17:01 How to test your rules?
18:20 Quick overview of ChainRules 1.0
19:03 Looking in to the future
19:26 Summary

**Comment by logankilpatrick** [comment]
Added! Thank you
