### ISSUE TITLE
A Tour of the differentiable programming landscape with Flux.jl | Dhairya Gandhi | JuliaCon2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#132]
A Tour of the differentiable programming landscape with Flux.jl | Dhairya Gandhi | JuliaCon2021 [https://www.youtube.com/watch?v=_UOD4hceFDQ](https://www.youtube.com/watch?v=_UOD4hceFDQ)

This is a high pace talk, I did what I can to capture it flow in timestamps.

00:00 Welcome!
00:34 Technical note
00:47 [Chemellia](https://github.com/Chemellia)
01:27 [DifferentiableDFTK](https://github.com/niklasschmitz/DifferentiableDFTK): automatic differentiation for density functional theory in Julia
02:26 [Molly.jl](https://github.com/JuliaMolSim/Molly.jl) and [Zygote.jl](https://github.com/FluxML/Zygote.jl)
03:06 [Flux3D.jl](https://github.com/FluxML/Flux3D.jl) a 3D vision library
03:59 [SciML](https://sciml.ai/) must be mentioned
04:12 ∂P as a tool
04:50 [Dagger.jl](https://github.com/JuliaParallel/Dagger.jl) and [Flux](https://fluxml.ai/Flux.jl/stable/)
06:58 Large scale distributing training in Julia
07:33 [Optimisers.jl](https://github.com/FluxML/Optimisers.jl)

**Comment by logankilpatrick** [comment]
Added, thank you!
