### ISSUE TITLE
JuliaCon 2020 | Makie.jl | Simon Danisch

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#133]
JuliaCon 2020 | Makie.jl | Simon Danisch, [https://www.youtube.com/watch?v=ACqBmDlhTBU](https://www.youtube.com/watch?v=ACqBmDlhTBU)

00:00 Welcome!
00:23 Acknowledgments
01:53 Roadmap: making React API for [Makie.jl](https://github.com/JuliaPlots/Makie.jl)
03:00 Roadmap: recipes
03:31 Roadmap: MakieLayout integration
04:47 Demos
07:18 [JuliaDynamics](https://github.com/JuliaDynamics) and [Makie.jl](https://github.com/JuliaPlots/Makie.jl)

**Comment by logankilpatrick** [comment]
Thank you!
