### ISSUE TITLE
JuliaCon 2020 | Keynote: Adventures in Computing | Prof Linda Petzold

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#134]
JuliaCon 2020 | Keynote: Adventures in Computing | Prof Linda Petzold, [https://www.youtube.com/watch?v=BY2qijwB33Y](https://www.youtube.com/watch?v=BY2qijwB33Y)

This is very enjoyable, full of personal histories nontechnical talk. It is also hard than in technical talk to pin down what is main topic of given chapter, but I tried it. Here are my results, maybe there aren't good, but at least now we have proposition of timestamps for all keynotes from JuliaCon 2020 and 2021. In the case of prof. Jan Vitek's keynote from 2021 their are even already accepted.

00:00 Welcome!
01:19 Programming with punch cards
01:49 My first serious encounter with numerical methods for ODEs
02:34 Why should users have to decide whether their problem is stiff or not?
04:02 Livermore Solver for Ordinary Differential Equations Automatic (LSODA) is now available in Julia by [LSODA.jl](https://github.com/rveltz/LSODA.jl)
04:14 Computational combustion (see [DASSL.jl](https://github.com/SciML/DASSL.jl)) and lessons about releasing code
06:35 Solar power plan and challenges that it provided
08:29 True problem wasn't in the code, but in our math
09:36 "DAEs are not ODEs" (Differential Algebraic Equations)
10:55 Development of theory and algorithms for Differential Algebraic Equations (DAE, see [DASKR.jl](https://github.com/SciML/DASKR.jl))
14:53 Solving F = ma with constraints
19:42 DAEs and various problems on which I was working around 1991
23:53 DAEs and parameter estimations, optimal control, etc.
24:41 Works on trajectories of small spacecrafts
27:32 Chemical vapor deposition and DAE
28:36 Discrete stochastic simulations
32:34 Stochasticity in biological systems
36:57 Circadian rhythm
38:27 Spatial stochastic simulation
41:03 Stochastic simulation of COVID-19
43:09 Acknowledgments
44:11 Q&A: What do you think about briers that specialist encounter when dealing with software engineering?
47:42 Q&A: What are your reflections on modeling biological systems?
49:16 Q&A: What do you think about recent hype that differential equations get from machine learning community?

**Comment by logankilpatrick** [comment]
Added, thanks!
