### ISSUE TITLE
JuliaCon 2020 | Loop Analysis in Julia | Chris Elrod

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#135]
JuliaCon 2020 | Loop Analysis in Julia | Chris Elrod, [https://www.youtube.com/watch?v=qz2kJdVDWi0](https://www.youtube.com/watch?v=qz2kJdVDWi0)

I highly admire Chris Elrod so I need to make timestamps for his talk. I hope that there are good enough.

00:00 Welcome!
00:19 Loop vectorization and [LoopVectorization.jl](https://github.com/JuliaSIMD/LoopVectorization.jl)
01:43 Current limitations of [LoopVectorization.jl](https://github.com/JuliaSIMD/LoopVectorization.jl)
02:48 First main part of intra-core parallelism: Single Instruction Multiple Data (SIMD)
03:46 Loading and storing vectors
06:34 Second main part of intra-core parallelism: super scalar parallelism
08:23 Example: summing a vector
10:31 Problem: no all vectors have length that is multiple of 32
13:02 Vectorization of loop with `@avx`
13:51 `@avx` and functions like `log` from stdlib
14:34 `@avx` and [StructArrays.jl](https://github.com/JuliaArrays/StructArrays.jl)
15:27 Eliminating redundant operations
19:56 [LoopVectorization.jl](https://github.com/JuliaSIMD/LoopVectorization.jl) and generated functions
20:48 Redundancy in convolutions
23:08 Internal working of [LoopVectorization.jl](https://github.com/JuliaSIMD/LoopVectorization.jl)

**Comment by logankilpatrick** [comment]
Done, thanks!
