### ISSUE TITLE
Changes to "Roadmap to Julia BLAS and LinearAlgebra" by Chris Elrod, JuliaCon 2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#136]
I was so impressed by Chris Elrod talk at JuliaCon 2020, that I watch his talk from JuliaCon 2021. It already have timestamps, but I tried to building on them make them more comprehensive. If you think this was bad decision you can throw them away.

_Roadmap to Julia BLAS and LinearAlgebra_, Chris Elrod, [https://www.youtube.com/watch?v=KQ8nvlURX4M](https://www.youtube.com/watch?v=KQ8nvlURX4M)

00:00 Welcome!
00:09 Introduction
01:00 Why we want to create Julia version of BLAS and LAPACK?
03:03 Performance
03:40 Commentary on [LoopVectorization.jl](https://github.com/JuliaSIMD/LoopVectorization.jl)
04:50 Multi-threaded matrix multiplication
05:51 Our biggest success: [RecursiveFactorization.jl](https://github.com/chriselrod/RecursiveFactorization.jl)
07:25 Multi-threaded implementations are not always straightforward
08:58 Recursive factorization is fast even for relatively big matrices
11:16 Flexibility
13:49 Express operation as BLAS, or optimize direct?
15:14 Interoperability with rest of the Julia ecosystem
16:00 Support for wide variety of types
16:47 Julia multi-threading can lead to better workload balance
18:43 Roadmap

**Comment by logankilpatrick** [comment]
These are great! I am always for more detailed timestamps.
