### ISSUE TITLE
Simulating Chemical Kinetics with ReactionMechanismSimulator.jl | Matthew S. Johnson | JuliaCon 2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#137]
_Simulating Chemical Kinetics with ReactionMechanismSimulator.jl_ | Matthew S. Johnson | JuliaCon 2021, [https://www.youtube.com/watch?v=Bvs-sUK693U](https://www.youtube.com/watch?v=Bvs-sUK693U)

I hope this timestamps will be useful. ReactionMechanismSimulator.jl looks pretty amazing and it deserves attention.

00:00 Welcome!
00:27 Outline of the talk
00:48 What is a chemical mechanism and why would I want to simulate one?
01:28 Elementary reactions and mass action kinetics
02:27 Timescale for unimolecular chemical reactions
02:56 Chemical mechanism, summary
03:24 What does a mechanism simulation look like?
03:58 Mathematical description of chemical mechnism
04:31 What is [ReactionMechanismSimulator.jl](https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl) (RMS)?
05:08 [RMS](https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl) was tested in many applications
05:36 Introduction to using [RMS](https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl)
09:17 Using [DifferentialEquations.jl](https://github.com/SciML/DifferentialEquations.jl) with  [RMS](https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl)
09:36 Using `SystemSimulation` object for plotting and analyzing solutions
11:30 Comparison with similar software
12:15 Qualitative comparison of software for simulation chemical mechanism
14:57 Benchmarks
16:03 Adjoint sensitivity analysis
16:43 Sensitivity analysis
17:21 Interpolated and parallel forward sensitivity analysis
18:36 [RMS'](https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl) unique tools: mechanism analysis
19:35 18:36 [RMS'](https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl) unique tools: symbolic reduction
20:58 How were we able to do this?
21:25 Case study: steady state solution identification
23:05 Why paper worth development in Cantera is 1-2 day job in [ReactionMechanismSimulator.jl](https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl)?
24:25 Conclusions
24:53 Acknowledgements

**Comment by logankilpatrick** [comment]
Thanks!
