### ISSUE TITLE
Solving discrete problems via Boolean satisfiability with Julia | David P. Sanders | JuliaCon 2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#138]
_Solving discrete problems via Boolean satisfiability with Julia_ | David P. Sanders | JuliaCon 2021, [https://www.youtube.com/watch?v=F5QuDrTkAow](https://www.youtube.com/watch?v=F5QuDrTkAow)

I hope this will fit with eight minutes talk.

00:00 Welcome!
00:15 Outline
00:35 Motivation: colouring graphs
01:03 Modelling the colouring graph problem
01:30 Domain constraints
02:05 Edge constraints
02:22 Constraint satisfaction problem
03:10 Colouring the ring graph
03:36 Colouring a Penrose tiling
03:53 We solve this problems using Boolean satisfiability problem (SAT)
05:34 Overview of SAT solvers
06:08 [SimpleSATSolver.jl](https://github.com/dpsanders/SimpleSATSolver.jl)
06:39 Algorithm for solving boolean satisfiability
07:10 Applying this techniques to solve discrete numerical problems
07:53 Conclusions

**Comment by logankilpatrick** [comment]
Thank you!
