### ISSUE TITLE
JuliaCon 2020 | DFTK: A Julian approach for simulating electrons in solids | Michael Herbst

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#139]
_DFTK: A Julian approach for simulating electrons in solids_, [https://www.youtube.com/watch?v=-RomkxjlIcQ](https://www.youtube.com/watch?v=-RomkxjlIcQ)

It was well structured talk with good slides, so I guess YT automatic timestamps for it would be enough for it. But, I listen to it and here are my propositions for timestamps.

00:00 Welcome!
01:14 Overview of the talk
01:33 Why care about electrons?
02:55 Aren't experiment good enough?
04:05 Electronic structure theory
05:36 Problem: computing integral over high-dimension space
06:34 Density Functional Theory (DFT)
07:35 Solving DFT: self-consistent field procedure
08:40 Landscape of DFT codes
09:12 Why we bother with developing [DFTK.jl](https://github.com/JuliaMolSim/DFTK.jl/)?
12:01 Overview of [DFTK.jl](https://github.com/JuliaMolSim/DFTK.jl/)
13:29 The only way we can manage it awesome Julia community and ecosystem
14:35 Lowering the entrance barrier for researches
17:44 High-throughput screening
20:41 A posteriori error analysis in DFT
22:23 A posteriori error analysis with [DFTK.jl](https://github.com/JuliaMolSim/DFTK.jl/)
24:00 A posteriori error analysis, first results
24:26 Quick look at SCF algorithms
24:43 Summary and outlook
25:40 Acknowledgements

**Comment by logankilpatrick** [comment]
Thank you!!
