### ISSUE TITLE
JuliaCon 2019 | Intelligent Tensors in Julia

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#140]
_Intelligent Tensors in Julia_, [https://www.youtube.com/watch?v=A2ypJkA26co](https://www.youtube.com/watch?v=A2ypJkA26co)

Sebastián Grijalva made timestamps for this video and put it in the comments to this video. Their are NOT made by me.

First the video need to edited again, four minutes at the beginning where nothing happens is too much. After that we can tweak there in appropriate way and add them to description.

04:00 Beginning of the talk
09:48 Definition Tensor Networks
12:33 ITensor using indices and basic operations
14:35 ITensor community and other higher level functions
15:38 Moving away from C++
16:42 Moving to Julia
18:46 Pain Points with Julia
19:34 Internal Details of ITensors
21:33 GPU functionality
25:24 Future Directions (2019)

**Comment by logankilpatrick** [comment]
Great, I just trimmed the first 4 minutes off, can you update these timestamps?

**Comment by logankilpatrick** [comment]
bumping this @KZiemian

**Comment by a2k42** [comment]
Is this what you wanted

```js
const exp = src.replace(/\d\d(?:\:)/g, (val) => ((Number.parseInt(val) - 4) + ":").padStart(3, "0"));
```

00:00 Beginning of the talk
05:48 Definition Tensor Networks
08:33 ITensor using indices and basic operations
10:35 ITensor community and other higher level functions
11:38 Moving away from C++
12:42 Moving to Julia
14:46 Pain Points with Julia
15:34 Internal Details of ITensors
17:33 GPU functionality
21:24 Future Directions (2019)

If it wasn't exactly 4 minutes that was trimmed off then the code can be modified a little.

**Comment by KZiemian** [comment]
Thank you @Andy2K11. In the last two weeks I have hand full of work, but I will try check this today.

**Comment by KZiemian** [comment]
Finally! After very long time I taken timestamps made by Sebastián Grijalva (see comments section on [YouTube](https://www.youtube.com/watch?v=A2ypJkA26co)) and refined them a bit watching current version of the talk. Below you can seen a result.

Contents
00:00 Welcome!
00:44 Why we need packages for working with tensors?
02:12 We work with very big tensors
03:35 Notation used in this talk (we like it)
05:23 Question: can you write double line between A and B?
05:51 Definition of tensor networks
06:43 How we code tensor operations?
08:33 Basic functionality of ITensors.jl
10:38 ITensor community
11:18 Higher level features that we want to port to Julia
11:44 Moving away from C++
12:46 Moving to Julia
13:24 Julia strong points
14:50 Pain points with Julia
15:38 Internal details of ITensors.jl
17:27 Adding fully tensor aware GPU functionality
19:01 Benchmarking tensor contractions
20:27 Limitations of GPU-based ITensors.jl
21:27 Future directions (state from 2019)
22:05 Check out [ITensors.jl](https://github.com/ITensor/ITensors.jl)
22:24 Acknowledgments
23:23 Q&A: which of things mentioned if futures directions can attract new people to Julia?
24:24 Q&A: how ITensors.jl benchmarks against other tensors packages?
24:23 Q&A: do you have any BLAS 3 like operations written in Julia?
25:48 Q&A: how you handles internal indices during SVD?

Resources
[ITensors.jl](https://github.com/ITensor/ITensors.jl)

**Comment by KZiemian** [comment]
@Andy2K11 I apologize for not mentioning you regular (expression) contribution. It was to late to think clearly.

**Comment by a2k42** [comment]
@KZiemian I wasn't expecting you to, did it for practice really and thought it might be useful as I'd seen you were doing a bit of work on them (Issue #106). With JuliaCon happening I wasn't sure if there would be much need for processing the timestamp formatting from different contributors, I guess if it works then that's the main thing, but let me know if you think I can help.

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close the issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We can now close this issue.
