### ISSUE TITLE
Cedar: A Composable ML Accelerated Analog Circuit Simulator | G. Hertz, P. de Vos | JuliaCon 2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#141]
_Cedar: A Composable ML Accelerated Analog Circuit Simulator_, [https://www.youtube.com/watch?v=q8SzFTtgA60](https://www.youtube.com/watch?v=q8SzFTtgA60)

This video was on my radar for the long time, I hope I made good timestamps for it.

00:00 Welcome!
00:20 Agenda
01:57 Technical computing is behind the times
02:27 We aim at matching technical computing with the times
02:46 Three simulation products from Julia Computing
03:20 JuliaHub, a supercomputer at your fingertips
03:55 A differential analog circuit simulator written in pure Julia
04:43 How to transform circuit model into equation?
06:52 Current state of parser and simulator
08:08 Using [Symbolics.jl](https://github.com/JuliaSymbolics/Symbolics.jl) in designing of circuits
10:37 Differentiable circuit optimization
11:12 Our simulator is just a Julia library, so we can seamlessly use whole Julia ecosystem
12:43 ML is reshaping computing, including circuit design
13:00 Black box and white box surrogatizaton of models
13:32 Problem: surrogate models of circuits are stiff
13:56 Challenges of dealing with Continuous-Time Echo State Networks (CTSN)?
14:33 New approach to train oscillatory process (at the time of the talk, not published)
15:00 Analog design today is often the same as it was 1990s and have serious drawbacks
17:39 Julia Computing bring to analog circuits what digital community already do
19:43 Be we want to do it even better
22:48 [Xyce.jl](https://github.com/JuliaComputing/Xyce.jl): wrapper for Xyce, a parallel circuit-simulator
23:38 Summary

**Comment by logankilpatrick** [comment]
Great, thank you!
