### ISSUE TITLE
Geostatistical Learning | Júlio Hoffimann | JuliaCon 2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#142]
_Geostatistical Learning_, [https://www.youtube.com/watch?v=75A6zyn5pIE](https://www.youtube.com/watch?v=75A6zyn5pIE)

I hope their are good, because this talk deserves good timestamps.

00:00 Welcome!
00:29 The two connotations of the word "Geo"
00:47 Here we understand GEOstatistics as statistics developed for GEOspatial data
01:02 Geospatial data is combination of tables of attributes and discretization of geospatial domain
01:12 We support any table implementing [Table.jl](https://github.com/JuliaData/Tables.jl) interface
01:23 We support any domain implementing [Meshes.jl](https://github.com/JuliaGeometry/Meshes.jl) interface
01:40 [Makie.jl](https://github.com/JuliaPlots/Makie.jl) allows use to visualise these domains efficiently on GPU
02:06 Example 1: 3D grid data
03:38 Example 2: 2D grid data (a.k.a. image)
04:28 Example 3: Map data
05:16 Example 4: Mesh data
05:59 Classical learning framework
06:50 Assumptions of classical learning framework do NOT hold in GEOspatial applications
07:20 Problem 1: Why the error is so high?
09:02 Samples are geospatial correlated
09:27 Cross-validation (CV) vs geostatistical validation
11:15 Showcase of working code
12:22 Problem 2: Why the clusters are everywhere?
13:07 Geostatistical clustering methods
13:47 We propose new framework: geostatistical learning
14:16 Advanced example: learning Wind-Chill Index (WCI) for models of airplane and helicopter
15:30 Advanced example: Wind-Chill Index for model of helicopter
16:31 Advanced example: Final result
17:19 Challenges and opportunities
17:56 We invite you to join our community if you share our feeling about geostatistics and industry

**Comment by logankilpatrick** [comment]
Added, thanks!
