### ISSUE TITLE
Put some constraints into your life with JuliaCon(straints) | Jean-François Baffier | JuliaCon 2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#143]
_Put some constraints into your life with JuliaCon(straints)_, [https://www.youtube.com/watch?v=G4siuvNMj0c](https://www.youtube.com/watch?v=G4siuvNMj0c)

This one was hard to do. I hope that this timestamps can be useful for other viewers.

00:00 Welcome!
01:15 What is Constraint Programming (CP)?
01:55 Formal definition of model
02:18 Canonical example of PC: AllDifferent constraint (as in the sudoku game)
03:08 Overview of CP Julia ecosystem
04:11 [ConstraintSolver.jl](https://github.com/Wikunia/ConstraintSolver.jl), the first CP solver in pure Julia
04:55 Example 1: solving sudoku with [JuMP](https://github.com/jump-dev/JuMP.jl) and [ConstraintSolver.jl](https://github.com/Wikunia/ConstraintSolver.jl)
06:20 [CPLEXCP.jl](https://github.com/JuliaConstraints/CPLEXCP.jl): Julia interface to commercial [CPLEX CP](https://www.ibm.com/analytics/cplex-cp-optimizer) optimizer
07:07 [SeaPearl.jl](https://github.com/corail-research/SeaPearl.jl): Constraint Programming solver that can use Reinforcement Learning
07:21 Example 2: Solving n-Queens problem
08:53 Backtracking solvers vs Constraint-Based Local Search (CBLS)
10:00 [LocalSearchSolvers.jl](https://github.com/JuliaConstraints/LocalSearchSolvers.jl): Constraint-Based Local Search framework
10:50 [ConstraintDomains.jl](https://github.com/JuliaConstraints/ConstraintDomains.jl): package for defining continuous and discrete domains
11:47 Example 3: Magic square
12:51 [Constraints.jl](https://github.com/JuliaConstraints/Constraints.jl) and [CompositionalNetworks.jl](https://github.com/JuliaConstraints/CompositionalNetworks.jl)
14:40 Example 5: Golomb ruler
17:03 Functionality of [Constraints.jl](https://github.com/JuliaConstraints/Constraints.jl)
17:19 [COPInstances.jl](https://github.com/JuliaConstraints/COPInstances.jl)
18:00 Overview of [LocalSearchSolvers.jl](https://github.com/JuliaConstraints/LocalSearchSolvers.jl)
18:47 Why making parallel [LocalSearchSolvers.jl](https://github.com/JuliaConstraints/LocalSearchSolvers.jl) was so easy?
20:24 Problems with Garbage Collector in parallel computing
22:03 Acknowledgments
22:58 Thoughts on future of Constraint Programming in Julia
23:42 Closing information

**Comment by logankilpatrick** [comment]
Thanks!
