### ISSUE TITLE
ReTest.jl - more productive testing | Rafael Fourquet | JuliaCon 2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#144]
_ReTest.jl - more productive testing_, [https://www.youtube.com/watch?v=n-UP_Ul-JjE](https://www.youtube.com/watch?v=n-UP_Ul-JjE)

I need to dig up more into testing to make better timestamps for this video. This is my first try and maybe I will be able to improve them before they will be place on YouTube.

00:00 Welcome!
00:19 [ReTest.jl](https://github.com/JuliaTesting/ReTest.jl) is mostly backward-compatible stdlib Test
00:45 Example
01:55 Standard test workflow in Julia
03:00 [ReTest.jl](https://github.com/JuliaTesting/ReTest.jl) workflow
04:13 Function watch
05:36 Function hijack
06:50 Function hijack_base for testing Julia Base

**Comment by logankilpatrick** [comment]
Thanks! Tests are cool : )
