### ISSUE TITLE
The state of JuMP | Oscar Dowson | JuliaCon 2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#145]
_The state of JuMP_, [https://www.youtube.com/watch?v=ODUrSmeWIBQ](https://www.youtube.com/watch?v=ODUrSmeWIBQ)

Beyond my poor English, this timestamps look quite decent to me.

00:00 Welcome!
00:33 What is [JuMP](https://jump.dev/)?
01:45 What is actually [JuMP-dev](https://github.com/jump-dev) GitHub organization?
02:58 Acknowledgments
03:16 Annually [JuMP](https://jump.dev/) workshops
03:39 Where is [JuMP](https://jump.dev/) used?
05:10 Outline of the rest of the talk
05:42 [JuMP](https://jump.dev/) related talks at JuliaCon 2021
07:31 Governance changes in [JuMP](https://jump.dev/) community
09:18 NSF funding for long term maintenance and support for [JuMP](https://jump.dev/)
11:25 Features request for [JuMP](https://jump.dev/)
11:39 Roadmap to [JuMP](https://jump.dev/) 1.0 from 2019 two years later
12:41 Many tutorials are now integrated into [JuMP](https://jump.dev/) documentation
14:12 You should check performance tips tutorial
15:33 New [JuMP](https://jump.dev/) features
18:52 We are close to [JuMP](https://jump.dev/) 1.0, but still some work need to be done
20:08 Planned breaking changes in [JuMP](https://jump.dev/) 1.0
21:37 Plans for the future beyond [JuMP](https://jump.dev/) 1.0
23:21 How you can to get involved with [JuMP](https://jump.dev/)?

**Comment by logankilpatrick** [comment]
Added, thank you!
