### ISSUE TITLE
ReactiveMP.jl: Reactive Message Passing-based Bayesian Inference | Dmitry Bagaev | JuliaCon 2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#146]
_ReactiveMP.jl: Reactive Message Passing-based Bayesian Inference_, [https://www.youtube.com/watch?v=twhTsKsXa_8](https://www.youtube.com/watch?v=twhTsKsXa_8)

I think that timestamps for this presentation could be done easily by YT mechanism and I'm not need to much. But since I have already done it, here are my propositions.

00:00 Welcome!
00:25 Overview of Julia probabilistic programming libraries: [Gen.jl](https://github.com/probcomp/Gen.jl), [Turing.jl](https://github.com/TuringLang/Turing.jl), etc.
00:37 Evolution of ideas behind [ForneyLab.jl](https://github.com/biaslab/ForneyLab.jl)
01:04 Brief introduction to [ForneyLab.jl](https://github.com/biaslab/ForneyLab.jl) ideas
02:22 [Example](https://github.com/biaslab/ReactiveMP_JuliaCon2021): estimating hidden state of moving object
04:41 Benefits of reactive implementation
05:42 Performance comparison
06:34 Plan for the future: combining [ReactiveMR.jl](https://github.com/biaslab/ReactiveMP.jl) and [GraphPPL.jl](https://github.com/biaslab/GraphPPL.jl)
06:46 The scope of the package
07:35 Other usages examples
07:53 Quick overview of [ReactiveMR.jl](https://github.com/biaslab/ReactiveMP.jl)

**Comment by logankilpatrick** [comment]
Thanks again!
