### ISSUE TITLE
Effects.jl: Effectively Understand Effects in Regression Models | Phillip Alday | JuliaCon 2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#149]
_Effects.jl: Effectively Understand Effects in Regression Models_, [https://www.youtube.com/watch?v=jnzw7i4rWuI](https://www.youtube.com/watch?v=jnzw7i4rWuI)

Sounds and in lesser extent video quality made working on this timestamps quite hard. Someone with better knowledge of the topic should review and improve what I have done. But, until then here are my propositions.

00:00 Welcome!
00:14 Analyzing concrete data using linear regression
00:57 Two-way interaction model
01:38 Finding prediction and effects using given data
04:11 Predictions and effect are invariant to contrast coding
05:01 Three-way interaction model
06:55 Summary

**Comment by logankilpatrick** [comment]
These look okay, and yes, the audio was very quiet. Thank you!
