### ISSUE TITLE
Parallel and Distributed Computing with Julia | Jeff Bezanson

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#152]
_Parallel and Distributed Computing with Julia_, [https://www.youtube.com/watch?v=JoRn4ryMclc](https://www.youtube.com/watch?v=JoRn4ryMclc)

It was one of the hardest videos to make timestamps, because there is a lot of questions and people don't speak directly to microphone, when they ask them.

Person better at parallel computing should try to find out what is a question on 35:27. And someone should check at least timestamps with question and find if they are correct.

00:00 Welcome!
00:55 Parallelism we have now is basically multiprocessing
01:49 **@async** macro
02:32 **@time** as example of macro
03:08 **@async** macro and **RemoteRef** type
04:35 Example: using object of **RemoteRef** type
05:40 Question: what is actually in **RemoteRef()**?
06:09 Question: how to get value from object of **RemoteRef()** type?
06:39 Question: can you assign value to object of **RemoteRef()** type or only pull of from it?
06:55 Adding local processes
07:50 **remote_call** a low level primitive
09:05 Question: what happen when you fetch value that hasn't been computed?
09:20 **@ spawn** macro
09:53 Question: are these processes on local or remote machine?
10:10 Question: to which processor are you talking?
10:58 **@ everywhere** macro
11:52 Question: can you **@spawn myid()**?
13:31 Parallel comprehensions with **@parallel** macro
14:19 Question: can we see where parts of distributed array actually are?
15:37 Current state of distributed arrays
16:05 Question: is the information about one process available to other process?
17:08 Question: what is send between process?
18:08 Question: can you talk to different processors in your REPL (shell)?
18:57 Question: can you run things asynchronously and then be told which one is finish without waiting for it?
19:35 Question: what do you think about Node.js model?
20:29 Question: what is an equivalent of MPI_Barrier?
21:03 Question: can you implement MPI model on the top of what we have now?
22:40 Question: can you make reductions?
24:47 Question: can you use **@ everywhere** for this example?
25:47 Question: do you have generic **sum** function?
27:59 Question: can you do the same by adding method to **reduce**?
28:44 By default you can use things from module **Base**, but you can't change them
30:37 Question: do you have **preduce** (parallel reduce) function?
30:58 Question: how you operate on multiple distributed arrays?
32:11 Question: can you do something like **reshape** operator?
33:13 Question: how hard it will be create data frames in Julia?
34:03 Working with distributed array
35:27 Question about some parallel functionality

**Comment by KZiemian** [comment]
For some reason Markdown (?) sometimes capitalize first letter after "@", like in **@everywhere**.

**Comment by logankilpatrick** [comment]
Added, these look good!
