### ISSUE TITLE
Enhanced Sampling in Molecular Dynamics Simulations with Julia | Pablo Zubieta | JuliaCon 2021

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#153]
_Enhanced Sampling in Molecular Dynamics Simulations with Julia_, [https://www.youtube.com/watch?v=a6sciHRP6m4](https://www.youtube.com/watch?v=a6sciHRP6m4)

This is quite fast talk, so it was hard to do. Someone else should check them.

00:00 Welcome!
00:20 Two the most common approaches to molecular dynamics
00:37 What is enhanced sampling in molecular dynamics?
01:25 Various flavors of enhanced sampling
01:42 State of software suitable for advanced general ensemble simulations
02:10 Enhanced Sampling on GPUs
02:38 Our goal: improve the performance of the existing solutions
03:45 Overview of my workflow
05:16 What Julia brings to my work with C++ and Python?
05:40 Julia libraries that I wrote as a byproduct: [DLPack.jl](https://github.com/pabloferz/DLPack.jl), [ReactionCoordinates.jl](https://github.com/pabloferz/ReactionCoordinates.jl), SSAGES.jl
05:55 Performance comparison
06:41 Example: alanine dipeptide in water
07:41 Conclusions

**Comment by logankilpatrick** [comment]
Added, thanks!
