### ISSUE TITLE
Keynote - Tricks and Tips in Numerical Computing | Nick Higham | JuliaCon 2018

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#154]
_Keynote - Tricks and Tips in Numerical Computing_, [https://www.youtube.com/watch?v=Q9OLOqEhc64](https://www.youtube.com/watch?v=Q9OLOqEhc64)

I hope that they are good enough.

00:00 We need to thanks again everyone that works on Julia 1.0
00:33 Introducing the speaker
01:14 What are tricks and tips?
02:14 Differentiation with(out) a difference
03:20 V-shape curve is a result of floating-point evaluation (cancelation) errors dominating truncation errors
04:00 "Automatic differentiation "
04:15 Complex step method
06:27 Example: derivative of atan(x)/(1 + e^(-x^2)) at x = 2
07:19 Computing principal logarithm in complex plane, a multi-valued function
08:03 Computing the principle logarithm in 1960s
10:35 Logarithm of product of numbers, complex case
12:32 Arcsin and Arccos in complex plane
13:06 Unwinding number
14:33 Roundtrip relations
16:19 Accurate difference
18:02 Low rank updated of n x n real matrix A
19:13 Why Sherman-Morrison formula holds?
20:45 World's Most Fundamental Matrix Equation
21:33 Computing a product
22:31 Matrix chain multiplication problem (MCMP)
23:10 Chain rule of differentiation and MCMP
24:46 Randomization
27:17 1985 IEEE Standard 754 and it 2008 Revision
28:10 Model for rounding errors analysis
28:48 This model is weaker than what IEEE Standard actually says
29:16 Model vs correctly rounded result
30:19 Prevision versus accuracy
31:24 Accuracy in not limited by precision
32:08 Photocopying errors
32:53 Typing errors
33:25 Low precision arithmetic
35:32 Applications of half precision (fp16, floating point 16 bits)
36:50 Error analysis in low precision arithmetic
37:46 What you can do to reduce error in fp16?
40:11 Can we obtain more information bounds?
41:24 Conclusions
42:48 Q&A: how to avoid case when randomization make problem worse?
43:27 Q&A: how to choose between methods like contour integral and higher precision arithmetic?
45:03 Q&A: does half precision allow a brute force analysis of distribution of operations?
46:17 Q&A: can you comment of low precision and power consumption?

**Comment by logankilpatrick** [comment]
Added, thanks for the work on this !
