### ISSUE TITLE
JuliaCon 2017 | Julia Computing | Viral Shah

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#156]
_Julia Computing_, JuliaCon 2017, [https://www.youtube.com/watch?v=Am09Nu2_B58](https://www.youtube.com/watch?v=Am09Nu2_B58)

This is 5 minutes non-technical talk, but since it have "Help us add" I made them. This is a kind of relaxing timestamping for me.

00:00 Welcome!
00:20 Who we are at Julia Computing
00:44 Foundries that we have done
02:01 We can now focus more on product oriented business
02:38 Our products
03:48 Our business goal is going to particular domains and solve their problems

**Comment by logankilpatrick** [comment]
Added, thanks!
