### ISSUE TITLE
JuliaCon 2017 | Celeste.jl: Petascale Computing in Julia | Prabhat, Regier & Fischer

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#157]
_Celeste.jl: Petascale Computing in Julia_, [https://www.youtube.com/watch?v=uecdcADM3hY](https://www.youtube.com/watch?v=uecdcADM3hY)

This is so hard video to understand properly. Not only it has over 50 minutes, but it contains three talks, by three different people, that speaks about one project from three different points of view. I do what I can, but someone should watch this talk and correct all my mistakes.

Jeff Regier's was the hardest. Very fast, dense and to understand it I would need to compute myself few formulas. Probably the worst timestamps are here.

00:00 Welcome! Prabhat's part of the talk
00:27 Supercomputers at National Energy Research Supercomputing Center (NERSC)
01:21 Top 10 data analytics problems (link to [blog post](https://www.youtube.com/watch?v=uecdcADM3hY))
03:16 Celeste is at top of the list for many reasons
03:46 Cori Phase 2, Cray XC-40, supercomputer that we use
04:23 NERSC big data stack
05:35 Performance and productivity tradeoff?
07:16 Celeste team accomplishment
09:16 The [Celest.jl](https://github.com/jeff-regier/Celeste.jl) collaboration
11:20 Project goals. Jeff Regier's part of the talk
12:53 Examples of an astronomical images that we want to analyze
13:32 Challenge of analyzing faint stars and galaxies
13:57 Our approach using Bayesian inference
14:47 The [Celest.jl](https://github.com/jeff-regier/Celeste.jl) graphical model
16:08 Scientific color priors
17:01 The likelihood: p(images|catalog)
19:32 Tractable and intractable quantities in Bayesian inference
20:07 Problem with integral over too high dimensional space
20:23 Variational inference
21:29 Julia makes implementation of complicated functions possible
22:02 Results for small data
22:37 Validation of our methods against well researched sky region Stripe 82
24:18 Numerical optimization scheme and making it parallel
26:35 Cori Phase 2 supercomputer, some technical information
27:22 Performance results of [Celest.jl](https://github.com/jeff-regier/Celeste.jl)
29:31 Solving large scale I/O problem. Keno Fischer part of the talk
31:03 Problem that we encounter with I/O
32:03 We take down the network with data traffic that we created
32:19 Standard high performance guidelines Julia code
33:44 Majority of hot code in [Celest.jl](https://github.com/jeff-regier/Celeste.jl) compute Hessian matrix of objective function
34:09 Analyzing for loops in the code
35:00 Question: what is ILP (Instruction Level Parallelism)
36:09 How much ILP is required?
37:28 Putting large chunk of Julia and assemble code in one big scalar inner loop and vectoring it
38:18 Improving Julia and LLVM to allow aforementioned vectorization
38:37 Improvements from previous point are slowly moving into Julia proper
39:30 Using [StaticArrays.jl](https://github.com/JuliaArrays/StaticArrays.jl)
40:37 Optimization of memory layout to avoid vector shuffling
44:06 Using multiple dispatch to utilize Hessian matrix structure
48:25 Optimization takeaways
50:24 Conclusions
51:58 Closing information

**Comment by logankilpatrick** [comment]
These are really good! Thanks for doing this.
