### ISSUE TITLE
An Introduction to Julia | Herriman & Verweij

### ISSUE THREAD

**Issue by hazrulakmal** [JuliaCommunity/YouTubeVideoTimestamps#164]
Title: An Introduction to Julia | Herriman & Verweij, [link](https://www.youtube.com/watch?v=cPYgipsg4DM)

00:00 Welcome!
01:55 Why Julia?
18:00 Jupyter Notebooks
27:40 Julia - Strings
31:50 Julia - Tuples, Dictionary & Arrays
45:30 Julia - Loops
54:30 Julia - Conditionals
1:04:55 Julia - Functions
1:25:50 Julia - Packages
1:33:15 Julia - Plots
1:39:00 Julia is fast
1:50:45 Basic linear algebra in Julia

**Comment by KZiemian** [comment]
Thank you. I now try to work to bring this topic back to life. Wish me good luck, I will need it.

**Comment by KZiemian** [comment]
Timestamps were added to the video. We will close this issue, when we get access rights to this GitHub repository.
