### ISSUE TITLE
Julia for Data Science - Video 3: Statistics | Dr. Huda Nassar | JuliaAcademy.com

### ISSUE THREAD

**Issue by isfanafely** [JuliaCommunity/YouTubeVideoTimestamps#169]
Video title : Julia for Data Science - Video 3: Statistics, by Dr. Huda Nassar (for JuliaAcademy.com)
Video link : https://www.youtube.com/watch?v=AAGxWEJ_eWk&t=117s

00:00 Welcome
00:10 Load Packages and Dataset
01:50 Quick analysis of dataset 
02:08 Scatter plot
03:01 Statistics Plots - Box plot
03:48 Statistics Plots - Histogram
05:20 Kernel density estimates
08:19 Probability Distributions - Normal distribution
09:14 Probability Distributions - Binomial distribution
09:46 Probability Distributions - Fit function
11:29 Hypothesis testing - OneSampleTTest
13:36 Hypothesis testing - scipy.stats
18:16 AUC and Confusion matrix

**Comment by KZiemian** [comment]
Thank you. I will now try to revitalize this topic and put your work on the YT. Wish me luck.

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We can now close the issue.
