### ISSUE TITLE
How to install Julia and Jupyter notebooks

### ISSUE THREAD

**Issue by IshraqFARHAN** [JuliaCommunity/YouTubeVideoTimestamps#171]
References:
Speaker:
Video title: How to install Julia and Jupyter notebooks
Link: [https://www.youtube.com/watch?v=oyx8M1yoboY](https://www.youtube.com/watch?v=oyx8M1yoboY)

Contents
00:00 - Welcome!
00:22 - Running Julia 
01:47 - Running Jupyter notebooks
04:04 - Allowing Jupyter notebooks to run Julia

**Comment by KZiemian** [comment]
I will too revitalize this topic. With a bit of luck, we can succeed.

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.
