### ISSUE TITLE
Internals of ModelingToolkit | Yingbo Ma | SciMLCon 2022

### ISSUE THREAD

**Issue by RosalRicardo** [JuliaCommunity/YouTubeVideoTimestamps#172]
Internals of ModelingToolkit | Yingbo Ma | SciMLCon 2022, [https://www.youtube.com/watch?v=ZFoQihr3xLs](url)

References:
Speaker: [Yingbo Ma](https://github.com/YingboMa)
Video title: Internals of ModelingToolkit | Yingbo Ma | SciMLCon 2022
Link: https://www.youtube.com/watch?v=ZFoQihr3xLs
Link to the code: https://github.com/SciML/ModelingToolkit.jl

00:10 - Introduction
00:41 - Definitions of ODE
00:58 - Limitation of ODEs in Engineering
01:56 - Composable modeling and DAEs
03:55 - Object oriented programming
05:41 - RC circuit
07:00 - Structural simplification of DAEs
07:13 - Bareiss algorithm
07:43 - Alias elimination
08:52 - Tearing
12:08 - All Together
13:31 - Acknowlegdement
14:04 - Q&A: Modelica Colaboration
15:46 - Q&A: Optimal control problems
16:17 - Q&A: Future of ModelingToolkit.jl
19:19 - Q&A: Add thermal noise to circuits (SDEs)

**Comment by logankilpatrick** [comment]
Added! Thank you.
