### ISSUE TITLE
JuliaCon 2017 | A Superfacility Model for Data-Intensive Science | Kathy Yelick

### ISSUE THREAD

**Issue by KZiemian** [JuliaCommunity/YouTubeVideoTimestamps#174]
[_A Superfacility Model for Data-Intensive Science_](https://www.youtube.com/watch?v=IEfQ5jIQB4Y)

This is one of this very fast talks and as such, quite challenging. I hope that these timestamps have some value.

00:00 Welcome!
00:29 "Big Data" and science
03:53 Science and Internet of Things
04:50 Many science challenges are at the boundary of theory and experiment
05:26 Roadmap of the talk
05:46 Science and search facitilities
06:59 Automated search and meta-data analysis
07:58 Past and future high performace facitilities
09:02 Filtering and de-nosing data
10:31 Math challenges in energy science data
12:24 Machine learning for science
14:12 Amount of avalible data grow faster than our computational capabilities
16:00 DOE ECP, Department of Energy exascale Computing Project
18:02 Computation and cost of energy used to perform it
20:07 The most costly thing inside machine is moving data around
22:19 Data vs. simulations: The irregularity spectrum
25:07 Programming models for exascale computations
28:32 Example: whole-mantle seismic model
29:55 Example: analysis of genome
32:01 Problems with distributed hash tables
33:10 Optimizing algorithm for matrix multiplication
37:13 7 Giants of Data and 7 Dwarfs of Simulation
38:39 Systems for data analysis
40:24 Why high level languages like Julia are key
41:28 Specialization of computer architectures
41:58 High Performance Computing Policies
42:54 Acknowledgements

**Comment by logankilpatrick** [comment]
Added, thanks!
