### ISSUE TITLE
Duplicated instructions in readme?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [JuliaCommunity/YouTubeVideoTimestamps#175]
with respect to d755a4fd9f79c641adaa0d8744d9f02245f5988a , I want to ask why that para with duplicate lines was added??

![image](https://user-images.githubusercontent.com/19423063/175805735-0947b28c-fc62-40dd-8baa-762d993879a3.png)

<details>

```diff
@@ -1,8 +1,8 @@
-## Get Involved
+## Get Involved (and get a Hackotberfest contrbution completed)

 If you want to help add timestamps to the YouTube videos found here: https://www.youtube.com/user/julialanguage, please follow the below steps:
 - See the time stamps in the description here: https://www.youtube.com/watchv=DGojI9xcCfg&list=PLP8iPy9hna6Q2Kr16aWPOKE0dz9OnsnIJ&index=2 
for an example of what you should do.
 - Find a video without time stamps that interests you
-- Open a new issue with the videos title to "claim" the video such that there's no overlapping work
-- Watch the video and add descriptive descriptions to the issue you opened
-- Once the description is accepted we will add a S/o to you in the video description as a thank you for your help! 
+- Create a new markdown file in the `videos` folder name with the title of the video.
+- Watch the video and add descriptive timestamps to the issue you opened (see here for an example: https://github.com/JuliaCommunity/YouTubeVideoTimestamps/issues/84)
+- Once the timestamps are accepted, we will add a S/o to you in the video description as a thank you for your help and you will get a `hacktoberfest-accepted` label on the PR.
```

```git diff
@@ -1,8 +1,8 @@
## Get Involved {+(and get a Hackotberfest contrbution completed)+}

If you want to help add timestamps to the YouTube videos found here: https://www.youtube.com/user/julialanguage, please follow the below steps:
- See the time stamps in the description here: https://www.youtube.com/watch?v=DGojI9xcCfg&list=PLP8iPy9hna6Q2Kr16aWPOKE0dz9OnsnIJ&index=2 for an example of what you should do.
- Find a video without time stamps that interests you
- [-Open-]{+Create+} a new [-issue-]{+markdown file in the `videos` folder name+} with the[-videos-] title [-to "claim"-]{+of+} the [-video 
such that there's no overlapping work-]{+video.+}
- Watch the video and add descriptive [-descriptions-]{+timestamps+} to the issue you opened {+(see here for an example: https://github.com/JuliaCommunity/YouTubeVideoTimestamps/issues/84)+}
- Once the [-description is accepted-]{+timestamps are accepted,+} we will add a S/o to you in the video description as a thank you for your [-help!-]{+help and you will get a `hacktoberfest-accepted` label on the PR.+}
```

</details>

**Comment by yashpalgoyal1304** [comment]
what is wanted? do you want timestamps in issues or as files?? 😅

**Comment by yashpalgoyal1304** [comment]
Also, i caught a bummer in the [video](https://www.youtube.com/watch?v=DGojI9xcCfg&list=PLP8iPy9hna6Q2Kr16aWPOKE0dz9OnsnIJ&index=2) referred to in the readme itself, the existing timestamps were not removed, which shadowed the new added timestamps.

![image](https://user-images.githubusercontent.com/19423063/175809734-3540d36b-11f1-4045-b52b-140bd4b7cb16.png)

**Comment by KZiemian** [comment]
> Also, i caught a bummer in the [video](https://www.youtube.com/watch?v=DGojI9xcCfg&list=PLP8iPy9hna6Q2Kr16aWPOKE0dz9OnsnIJ&index=2) (referred to in the readme itself), the existing timestamps were not removed, which shadowed the new added timestamps.

There is a lot of bumper like this one, many of them are mentioned in this [issue](https://github.com/JuliaCommunity/YouTubeVideoTimestamps/issues/106).

**Comment by yashpalgoyal1304** [comment]
yeah, there are. but i dont think that there'd be a good way to contribute to that. lol, youtube is soo poor to implement that kind of thing. seeing the huge amount of work that you have done, and the issue with video i found was already mentioned in your issue, i'll be moving my that input over to your's issue.
