### ISSUE TITLE
Web Apps with Genie.jl | Adrian Salceanu | Julia Munich User Group March 2021

### ISSUE THREAD

**Issue by jvaverka** [JuliaCommunity/YouTubeVideoTimestamps#177]
Video [link](https://www.youtube.com/watch?v=0DizdxCSNms)

Contents
00:00 Intro - Genie Framework
04:20 Intro - Genie ecosystem
05:58 Intro - helpful resources
06:11 Demo - what are we building?
07:14 Demo - preview
07:40 Demo - questions
10:52 Demo - readme
13:22 Demo - create MVC app
19:51 Demo - more questions
26:27 Demo - exploring new app
32:30 Demo - configuring database
37:30 Demo - creating new resource
40:54 Demo - creating db table with migrations
46:34 Demo - running migrations
48:00 Demo - editing the model
49:31 Demo - model + db interaction
52:34 Demo - seeding data
1:02:50 Demo - setting up web page
1:08:07 Demo - templating & partials
1:23:48 Demo - layouts
1:26:28 Demo - search functionality
1:37:30 Demo - Revise questions
1:41:17 Demo - building REST API
1:47:42 Q&A - performance / demo source / load-balancing
1:53:40 Tips - routing / deployment
1:55:10 Q&A - high-availability
1:58:40 Farewell - end of scheduled presentation
2:00:40 Bonus - plugin system / authentication plugin
2:11:00 Bonus - questions
2:13:30 Bonus - authentication test
2:16:37 Bonus - secrets
2:23:35 Bonus - create admin user
2:25:04 Bonus - Stipple.jl & final remarks

**Comment by logankilpatrick** [comment]
Added, thank you!
