### ISSUE TITLE
For upcoming JuliaCon (2022) Talk: Writing a GenericArpack library in Julia

### ISSUE THREAD

**Issue by dgleich** [JuliaCommunity/YouTubeVideoTimestamps#179]
Here are the timestamps I had while prepping my upcoming JuliaCon 2022 talk: Writing a GenericArpack library in Julia

The YouTube link is: https://www.youtube.com/watch?v=WE0yyE2e1sc

0:00:00	Singular Values and the Netflix Matrix
0:01:52	What is Arpack?
0:03:14	GenericArpack.jl goals
0:05:10	Why translation?
0:06:13	The plan: port it function by function
0:09:42	Fortran save variables
0:11:00	Reseting ARPACK Random Number Seeds
0:13:07	Lapack Random Numbers in Julia
0:13:29	Saving Subroutine State in Julia
0:14:18	Other details of porting
0:15:00	Example of testing against Arpack_jll
0:15:59	The OpenBLAS 80-bit extended precision norm in Julia
0:17:43	Fixing allocations to mirror Fortran: copyto! and unalias
0:20:05	Why does the line "while true" allocate?
0:21:03	Optimizing out reverse communication
0:21:51	Adding the Hermitian eigensolver
0:22:49	Using high precision types
0:23:32	GenericArpack.jl has similar timing to Arpack
0:24:43	Other notes
0:25:08	Vision

**Comment by dgleich** [comment]
With the JuliaCon 10 second intro, I think these become:

0:00:00 	Welcome
0:00:10		Singular Values and the Netflix Matrix
0:02:02		What is Arpack?
0:03:24		GenericArpack.jl goals
0:05:20		Why translation?
0:06:23		The plan: port it function by function
0:09:52		Fortran save variables
0:11:10		Reseting ARPACK Random Number Seeds
0:13:17		Lapack Random Numbers in Julia
0:13:39		Saving Subroutine State in Julia
0:14:28		Other details of porting
0:15:10		Example of testing against Arpack_jll
0:16:09		The OpenBLAS 80-bit extended precision norm in Julia
0:17:53		Fixing allocations to mirror Fortran: copyto! and unalias
0:20:15		Why does the line while true allocate?
0:21:13		Optimizing out reverse communication
0:22:01		Adding the Hermitian eigensolver
0:22:59		Using high precision types
0:23:42		GenericArpack.jl has similar timing to Arpack
0:24:53		Other notes
0:25:18		Vision

**Comment by logankilpatrick** [comment]
Added, thanks!
