### ISSUE TITLE
Reducing Running Time and Time to First X: A Walkthrough | Rik Huijzer | JuliaCon 2022

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaCommunity/YouTubeVideoTimestamps#180]
Link: https://www.youtube.com/watch?v=jV0B13F1zI8

Could you also add a link to https://huijzer.xyz/posts/inference/ in the description or, preferably in the video around 11:04? I mistyped the link in the video by the way. I'll fix that on my end too via a symlink.

**Contents**
00:00 Welcome
00:32 Float32 and Float64 numbers
02:53 Abstract versus concrete types
04:25 Any can cause more Any return types
05:12 Runtime dispatch
06:08 Digression: optimized code for known types
07:36 Inference barrier
08:57 Type hints
09:25 Fixing the Float32 and Float64 numbers type instability
10:55 Link to more information

**Comment by logankilpatrick** [comment]
Added, thank you!

**Comment by rikhuijzer** [comment]
Uhm the timestamps have been reset again, @logankilpatrick? (https://www.youtube.com/watch?v=jV0B13F1zI8)

Maybe a bot is doing something?

**Comment by rikhuijzer** [comment]
Fixed now. Thanks a lot @ranjanan!
