### ISSUE TITLE
A Data Integration Framework for Microbiome Research | Giulio Benedetti | JuliaCon 2022

### ISSUE THREAD

**Issue by RiboRings** [JuliaCommunity/YouTubeVideoTimestamps#183]
Hi!

Here below is the same content as in the md file inside the videos dir. Thanks again!

References:
Speaker: Giulio Benedetti
Video title: A Data Integration Framework for Microbiome Research | Giulio Benedetti | JuliaCon 2022
Link: https://www.youtube.com/watch?v=Oxi0Pfmskus&list=PLP8iPy9hna6QuDTt11Xxonnfal91JhqjO&index=11

Contents:
0:00 Welcome!
0:06 Opening
0:26
Self-introduction
0:55 Background
1:41 SummarizedExperiments.jl
3:37 MicrobiomeAnalysis.jl
5:55 Next steps
7:18 Acknowledgements

**Comment by logankilpatrick** [comment]
Hey @RiboRings the video link here is wrong

**Comment by logankilpatrick** [comment]
Added!
