### ISSUE TITLE
Cropbox.jl: A Declarative Crop Modeling Framework | Kyungdahm Yun | JuliaCon 2022

### ISSUE THREAD

**Issue by tomyun** [JuliaCommunity/YouTubeVideoTimestamps#184]
References:
Speaker: Kyungdahm Yun
Video title: Cropbox.jl: A Declarative Crop Modeling Framework | Kyungdahm Yun | JuliaCon 2022
Link: https://www.youtube.com/watch?v=l43ldy_L35A

Contents
00:06 Introduction
00:21 Crop Modeling
01:40 Cropbox.jl
02:02 Specification
02:58 Specification - Variable
03:18 Specification - Pattern
04:52 Specification - Unit
05:09 Specification - Documentation
05:30 Simulation
06:22 Visualization
07:31 Evaluation
07:59 Conclusion

**Comment by logankilpatrick** [comment]
Added, thank you!

**Comment by tomyun** [comment]
@logankilpatrick I confirmed when they were added, but then now timestamps are all gone and also the title and description texts are somehow enclosed in square brackets. It'd be nice if you could give a look before the session begins on Wednesday. Thanks!

Title: Cropbox.jl: A Declarative Crop Modeling Framework | Kyungdahm Yun | JuliaCon 2022
Description: [Cropbox.jl](https://github.com/cropbox/Cropbox.jl) provides a domain specific language for developing crop models.
