### ISSUE TITLE
Text Segmentation with Julia | Kento Kawasaki | JuliaCon 2022

### ISSUE THREAD

**Issue by kawasaki-kento** [JuliaCommunity/YouTubeVideoTimestamps#185]
Hi.
I have created a timestamp for the following video.
Thank you for your cooperation.

References:
Speaker: Kento Kawasaki
Video title: Text Segmentation with Julia | Kento Kawasaki | JuliaCon 2022
Link: https://www.youtube.com/watch?v=VtQLmKJpKqY
Link to the code: https://github.com/kawasaki-kento/TextSegmentation.jl

Contents
00:06 Introduction
00:25 Table of Contents
00:49 Text Segmentation
01:29 TextTiling
02:55 TopicTiling
03:44 C99
05:03 How to use the package
07:44 Future Issues

**Comment by logankilpatrick** [comment]
Added, thank you!
