### ISSUE TITLE
ExplainableAI.jl: Interpreting neural networks in Julia | Adrian Hill | JuliaCon 2022

### ISSUE THREAD

**Issue by adrhill** [JuliaCommunity/YouTubeVideoTimestamps#190]
Speaker: Adrian Hill
Video title: ExplainableAI.jl: Interpreting neural networks in Julia | Adrian Hill | JuliaCon 2022
Link to the video: https://www.youtube.com/watch?v=p5dg3vdmlvI
Link to the code: https://github.com/adrhill/ExplainableAI.jl

0:00 Introduction
0:15 Acknowledgements
0:23 What is Explainable AI?
0:54 Clever Hans phenomena
1:32 Implemented methods
1:55 Layer-wise Relevance Propagation
2:14 Demonstration: LRP on an ImageNet classifier
4:46 Demonstration: Neuron selection
5:23 Demonstration: Heatmapping
5:45 Extending the package with custom rules
6:06 Plans for the future

**Comment by logankilpatrick** [comment]
Added! Thank you.

**Comment by adrhill** [comment]
The timestamps are not yet in the video. Is this normal?

**Comment by KZiemian** [comment]
@adrhill Can you check are they visible now?

**Comment by adrhill** [comment]
Perfect, thanks!
