### ISSUE TITLE
PDE-constrained optimization using JuliaSmoothOptimizers | JuliaCon 2022

### ISSUE THREAD

**Issue by tmigot** [JuliaCommunity/YouTubeVideoTimestamps#191]
Video title: PDE-constrained optimization using JuliaSmoothOptimizers | Tangi Migot | JuliaCon2022
Link: [https://www.youtube.com/watch?v=S2DgKcndHr0](https://www.youtube.com/watch?v=BvReBcMyujQ)
Link to the code: https://github.com/JuliaSmoothOptimizers/PDENLPModels.jl

Contents
0:00 Welcome
0:10 Introduction
0:59 PDE-constrained optimization
5:34 Discretization methods for PDEs
8:45 PDENLPModels.jl
10:35 JuliaSmoothOptimizers organization
13:05 Tutorial 1: 2D Poisson-Boltzmann equation
16:30 Tutorial 2: Distributed Poisson control problem
20:10 conclusion
21:20 How to get involved

**Comment by KZiemian** [comment]
I support speakers timestamping their own presentations.

**Comment by logankilpatrick** [comment]
Added, thanks!
