### ISSUE TITLE
 Real-Time, I/O, and Multitasking: Julia for Medical Imaging | Niklas Hackelberg | JuliaCon 2022 

### ISSUE THREAD

**Issue by nHackel** [JuliaCommunity/YouTubeVideoTimestamps#193]
Video Title:  Real-Time, I/O, and Multitasking: Julia for Medical Imaging | Niklas Hackelberg | JuliaCon 2022 
Video Link: https://www.youtube.com/watch?v=chZfGfAAnpE

Content:
00:00 Welcome!
00:34 Motivation: Medical Imaging
00:50 Motivation: Imaging Scanner
01:36 Motivation: Challenges
03:13 Architecture and Packages
04:40 Network Communication Optimizations
05:40 High Performance Sample Transmission
06:08 MPIMeasurements.jl: Main Data Structures
06:49 Threading Model
08:00 Threading Example

**Comment by logankilpatrick** [comment]
Added, thanks!

**Comment by nHackel** [comment]
Ah @logankilpatrick, I just noticed that I did the timestamp the wrong way around and listed the end and not the start of a section.
Here is the corrected version:

00:00 Welcome!
00:10 Motivation: Medical Imaging
00:34 Motivation: Imaging Scanner
00:50 Motivation: Challenges
01:36 Architecture
03:13 Network Communication Optimizations
04:40 High Performance Sample Transmission
05:40 Imaging Scanner Data Structures
06:08 Threading Model
06:49 Threading Example
