### ISSUE TITLE
Modal Decision Trees (Decision Trees, meet Modal Logics) | Giovanni Pagliarini | JuliaCon 2022

### ISSUE THREAD

**Issue by giopaglia** [JuliaCommunity/YouTubeVideoTimestamps#194]
Speaker: Giovanni Pagliarini
Video URL: https://www.youtube.com/watch?v=8F1vZsl8Zvg

00:06 Introduction
00:44 Symbolic Learning & the importance of interpretability
01:29 Standard Decision Trees can't natively deal with temporal/spatial data
02:02 Modal logics are tailored for temporal/spatial reasoning
03:00 Example: how a Modal Decision Tree would classify an image
04:06 ModalDecisionTrees.jl: features & limitations
05:02 Performances
05:45 Live demo!

Merci! :)

**Comment by digital-carver** [comment]
Hi, 

I didn't notice that you had already posted these, so also made some timestamps myself. Your timestamp descriptions are better though, so I'll leave mine out. (Except for 05:02 - I think "Applications" as in your slide title, or "Real-world Applications", would be a better description for that part.)

I also collected the links to the papers mentioned at 05:02, so I'll post them below: 

---
**Links to citations**:

https://drops.dagstuhl.de/opus/volltexte/2021/14783/ - Interval Temporal Random Forests with an Application to COVID-19 Diagnosis

https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4102488 - The Voice of COVID19: Breath and Cough Recording Classification with Temporal Decision Trees and Random Forests

https://arxiv.org/abs/2109.08325 - Decision Tree Learning with Spatial Modal Logics

https://link.springer.com/chapter/10.1007/978-3-031-06242-1_53 - Statistical and Symbolic Neuroaesthetics Rules Extraction from EEG Signals

---

**Comment by giopaglia** [comment]
Right, "Applications" seems more pertinent indeed :)
Thanks for collecting the links, is it possible to have them listed in the video description?
Also, I have two more questions about the YouTube video:
- Can I ask for an adjustment to the video title? I'd like it to be "Decision Trees, meet Modal Logics | Giovanni Pagliarini | JuliaCon 2022". That is, I'd like my last name to show up, and also no "ModalDecisionTrees" which is in line with the title shown in the video preview.
- I tried posting a comment, a few times actually, but it looks like after a few minutes it gets deleted. Is there a reason behind this, that I'm unaware of?

**Comment by digital-carver** [comment]
>  Thanks for collecting the links, is it possible to have them listed in the video description?

That's my hope, to have them in the video description before the timestamp section. But it's for @logankilpatrick/the Julia YouTube team to decide - I'm just a volunteer posting the timestamps as I go back and watch the JuliaCon talks I missed. 

Regarding the comment, if the comment contained a link in it, it may be a victim of YouTube's "spam detection" algorithm - it's kind finicky and unpredictable about what links it allows and disallows. But Logan or someone else on the admin side of the account might have a better answer to that. 

Speaking of links, I forgot to add the repo link in the previous comment, so: 

ModalDecisionTrees on Github: https://github.com/giopaglia/ModalDecisionTrees.jl

**Comment by KZiemian** [comment]
I try to bring this GItHub repo back to life. I don't have access to YT channel, I just normal user, but I will try what I can to make whole topic alive.

**Comment by KZiemian** [comment]
I combined timestamps and materials mentioned in this thread into text below.

Contents
00:00 Opening and introduction
00:44 Symbolic Learning & the importance of interpretability
01:29 Standard Decision Trees can't natively deal with temporal/spatial data
02:02 Modal logics are tailored for temporal/spatial reasoning
03:00 Example: how a Modal Decision Tree would classify an image
04:06 [ModalDecisionTrees.jl](https://github.com/aclai-lab/ModalDecisionTrees.jl): features & limitations
05:02 Performances
05:45 Live demo!

Resources
[ModalDecisionTrees.jl](https://github.com/aclai-lab/ModalDecisionTrees.jl)
Federico Manzella, Giovanni Pagliarini, Guido Sciavicco, Ionel Eduard Stan, [_Interval Temporal Random Forests with an Application to COVID-19 Diagnosis_](https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.TIME.2021.7)
Guido Sciavicco, Federico Manzella, Giovanni Pagliarini, Ionel Eduard Stan, [_The Voice of COVID19: Breath and Cough Recording Classification with Temporal Decision Trees and Random Forests_](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4102488)
Giovanni Pagliarini, Guido Sciavicco, [_Decision Tree Learning with Spatial Modal Logics_](https://arxiv.org/abs/2109.08325)
M. Coccagna, F. Manzella, S. Mazzacane, G. Pagliarini, G. Sciavicco, [_Statistical and Symbolic Neuroaesthetics Rules Extraction from EEG Signals_](https://link.springer.com/chapter/10.1007/978-3-031-06242-1_53)

**Comment by giopaglia** [comment]
Thank you all, here's an updated version.

Contents
- 00:00 Opening and introduction
- 00:44 Symbolic Learning & the importance of interpretability
- 01:29 Standard Decision Trees can't natively deal with temporal/spatial data
- 02:02 Modal logics are tailored for temporal/spatial reasoning
- 03:00 Example: how a Modal Decision Tree would classify an image
- 04:06 [ModalDecisionTrees.jl](https://github.com/aclai-lab/ModalDecisionTrees.jl): features & limitations
- 05:02 Applications
- 05:45 Live demo!

Resources
- [ModalDecisionTrees.jl](https://github.com/aclai-lab/ModalDecisionTrees.jl) - Modal Decision Trees & Forests in Julia
- Manzella, F., Pagliarini, G., Sciavicco, G., & Stan, I. E. (2023). [_The Voice of COVID19: Breath and Cough Recording Classification with Temporal Decision Trees and Random Forests._](https://www.sciencedirect.com/science/article/pii/S093336572200238X?casa_token=vViLMQrczIgAAAAA:z4i7oq58no91H75C8Ykn0aamjWuMkaiIatqFtSB8wSldsZqgyz_1pBpAz1IBzWUNHXYR5OVh8Q) Artificial Intelligence in Medicine, 137, 102486.
- Pagliarini, G., & Sciavicco, G. (2023). [_Interpretable land cover classification with modal decision trees._](https://www.tandfonline.com/doi/full/10.1080/22797254.2023.2262738) European Journal of Remote Sensing, 56(1), 2262738.
- Mazzacane, S., Coccagna, M., Manzella, F., Pagliarini, G., Sironi, V. A., Gatti, A., ... & Sciavicco, G. (2023). [_Towards an objective theory of subjective liking: A first step in understanding the sense of beauty._](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0287513) Plos one, 18(6), e0287513.

**Comment by KZiemian** [comment]
In last post in this [thread](https://discourse.julialang.org/t/learning-materials-and-outreach-to-the-programming-beginners/108041/16) on Julia Discourse they said, that someone is working to bring this repo back to life. At this moment normal users like my can only wait for what will happened.

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We are now can close the issue.
