### ISSUE TITLE
From Mesh Generation to Adaptive Simulation: A Journey in Julia | Andrew Winters | JuliaCon 2022

### ISSUE THREAD

**Issue by andrewwinters5000** [JuliaCommunity/YouTubeVideoTimestamps#195]
YouTube: [https://www.youtube.com/watch?v=_N4ozHr-t9E](https://www.youtube.com/watch?v=_N4ozHr-t9E)
Talk repo: [https://github.com/trixi-framework/talk-2022-juliacon_toolchain](https://github.com/trixi-framework/talk-2022-juliacon_toolchain)
Package repos: [https://github.com/trixi-framework/HOHQMesh.jl](https://github.com/trixi-framework/HOHQMesh.jl), [https://github.com/trixi-framework/Trixi.jl](https://github.com/trixi-framework/Trixi.jl), [https://github.com/trixi-framework/Trixi2Vtk.jl](https://github.com/trixi-framework/Trixi2Vtk.jl)

00:00 Welcome and acknowledgements 
00:41 Overview of workflow
01:37 Prototypical supersonic flow example
02:47 Overview of HOHQMesh.jl
03:54 Installing HOHQMesh.jl
04:38 Breakdown of domain for meshing
05:37 Creating and adding to a HOHQMesh project
08:50 Generating the mesh and output files
09:53 Breakdown of desired solver features
10:44 Overview of Trixi.jl
11:29 Installing Trixi.jl
11:45 Description of a Trixi elixir file
12:14 Adding the physical model
13:19 Adding the mesh and boundary conditions
14:49 Adding the spatial discretization
16:07 Assembling the semidiscretization
16:48 Overview of callbacks
17:58 Description of the AMR callback
19:36 Time integration and running the elixir
20:53 First plot of solution using Makie
22:11 Postprocessing Trixi data with Trixi2Vtk.jl
23:02 Description of results from prototypical example
24:00 Conclusions and outlook

This issue is ready for review, @logankilpatrick . Tack så mycket!

**Comment by KZiemian** [comment]
I don't know who is responsible for this repository at this moment, but I will do my best to put your work on YT. I just normal user of Julia, nothing more.

**Comment by KZiemian** [comment]
I tweaked it a bit for future used.

Contents
00:00 Welcome and acknowledgements
00:41 Overview of workflow
01:37 Prototypical supersonic flow example
02:47 Overview of [HOHQMesh.jl](https://github.com/trixi-framework/HOHQMesh.jl)
03:54 Installing [HOHQMesh.jl](https://github.com/trixi-framework/HOHQMesh.jl)
04:38 Breakdown of domain for meshing
05:37 Creating and adding to a [HOHQMesh.jl](https://github.com/trixi-framework/HOHQMesh.jl) project
08:50 Generating the mesh and output files
09:53 Breakdown of desired solver features
10:44 Overview of [Trixi.jl](https://github.com/trixi-framework/Trixi.jl)
11:29 Installing [Trixi.jl](https://github.com/trixi-framework/Trixi.jl)
11:45 Description of a Trixi elixir file
12:14 Adding the physical model
13:19 Adding the mesh and boundary conditions
14:49 Adding the spatial discretization
16:07 Assembling the semidiscretization
16:48 Overview of callbacks
17:58 Description of the AMR callback
19:36 Time integration and running the elixir
20:53 First plot of solution using Makie
22:11 Postprocessing Trixi data with [Trixi2Vtk.jl](https://github.com/trixi-framework/Trixi2Vtk.jl)
23:02 Description of results from prototypical example
24:00 Conclusions and outlook

Resources
Presentation [repository](https://github.com/trixi-framework/talk-2022-juliacon_toolchain).
[HOHQMesh.jl](https://github.com/trixi-framework/HOHQMesh.jl)
[Trixi.jl](https://github.com/trixi-framework/Trixi.jl)
[Trixi2Vtk.jl](https://github.com/trixi-framework/Trixi2Vtk.jl)

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We can now close the issue.
