### ISSUE TITLE
Julia in VS Code - What's New | David Anthoff, Sebastian Pfitzner | JuliaCon 2022

### ISSUE THREAD

**Issue by poposca** [JuliaCommunity/YouTubeVideoTimestamps#196]
Speakers:  David Anthoff, Sebastian Pfitzne
Video URL: https://www.youtube.com/watch?v=Okn_HKihWn8

0:00 - Welcome and Introduction
0:37 - New features for the Table Viewer
4:02 - Juliaup integration with Visual Studio Code
6:32 - Shell integration
10:20 - New Formatting Engine: Julia Formatter 
12:43 - New Profiler UI
17:11 - Easier evaluation of Julia code inside Markdown
18:12 - Runtime Diagnostics integration (with JET)
21:08 - New Tests Runner System and UI (experimental)

**Comment by KZiemian** [comment]
I wish that we can make timestamps on YT channel more stylistic homogenous, so I allowed myself to tweak your work a bit.

Contents
00:00 Opening and introduction
00:37 New features for the Table Viewer
04:02 Juliaup integration with Visual Studio Code
06:32 Shell integration
10:20 New Formatting Engine: Julia Formatter
12:43 New Profiler UI
17:11 Easier evaluation of Julia code inside Markdown
18:12 Runtime Diagnostics integration (with JET)
21:08 New experimental Tests Runner System and UI

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We can now close the issue.
