### ISSUE TITLE
 Fast, Faster, Julia: High Performance Implementation of the NFFT | Tobias Knopp | JuliaCon 2022 

### ISSUE THREAD

**Issue by nHackel** [JuliaCommunity/YouTubeVideoTimestamps#197]
Speaker: Tobias Knopp
Video url: https://www.youtube.com/watch?v=o9yF7HjkNG4&t=1303s

Content:
00:00 Welcome!
00:10 Background: FFT
02:27 Background: Limits of FFT
03:16 Non-Equidistant Fast Fourier Transform
05:03 Basic Idea of NFFT
06:39 Formula of the NFFT
08:15 Design Space
09:46 Introduction of NFFT.jl
11:25 Example of NFFT.jl
12:35 Dimension-Agnostic Implementations
14:55 Implementation Overview
16:15 Convolution: Idea
18:05 Convolution: Hot-Code Path
19:30 Adjoint Convolution
22:16 Performance and Accuracy Evaluation
22:52 Benchmark Results
22:45 Benchmark Results: Mutli-Threading
23:30 Summary and Outlook

**Comment by KZiemian** [comment]
I allowed myself to teak a little your work.

Content
00:00 Welcome!
00:10 Background: FFT
02:27 Background: Limits of FFT
03:16 Non-Equidistant Fast Fourier Transform
05:03 Basic Idea of NFFT
06:39 Formula of the NFFT
08:15 Design Space
09:46 Introduction of [NFFT.jl](https://github.com/JuliaMath/NFFT.jl)
11:25 Example of [NFFT.jl](https://github.com/JuliaMath/NFFT.jl)
12:35 Dimension-Agnostic Implementations
14:55 Implementation Overview
16:15 Convolution: Idea
18:05 Convolution: Hot-Code Path
19:30 Adjoint Convolution
22:16 Performance and Accuracy Evaluation
22:52 Benchmark Results
22:45 Benchmark Results: Mutli-Threading
23:30 Summary and Outlook

Resources
[NFFT.jl](https://github.com/JuliaMath/NFFT.jl)

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We can now close the issue.
