### ISSUE TITLE
Automatic Differentiation for Solid Mechanics in Julia | Andrea Vigliotti | Juliacon 2022

### ISSUE THREAD

**Issue by avigliotti** [JuliaCommunity/YouTubeVideoTimestamps#199]
Author: 	Andrea Vigliotti, andrea.vigliotti@gmail.com
github:	https://github.com/avigliotti
video url:	https://www.youtube.com/watch?v=EeC2pu9i_F0

0:10 Introduction
0:30 Why AD for solid Mechanics?
1:50 One example, the rod element
2:50 Why Julia?
3:24 AD4SM.jl
4:00 How a second order forward mode AD System works
6:46 Examples of simulation results

AD4SM.jl is [here](https://github.com/avigliotti/AD4SM.jl)
the slides and more examples are [here](https://github.com/avigliotti/AD4SM_examples)
the paper is [here](https://t.co/t8zHT4JHS6)

**Comment by KZiemian** [comment]
I hope that this GitHub will come to live again. I will try my best to achieve that. Meanwhile I tweaked a bit your work.

Contents
0:10 Opening and introduction
0:30 Why AD for solid Mechanics?
1:50 One example, the rod element
2:50 Why Julia?
3:24 [AD4SM.jl](https://github.com/avigliotti/AD4SM.jl)
4:00 How a second order forward mode AD System works
6:46 Examples of simulation results

Mentioned resources
AD4SM.jl package [repository](https://github.com/avigliotti/AD4SM.jl).
Slides of presentation and additional examples [link](https://github.com/avigliotti/AD4SM_examples).
Andrea Vigliotti & Ferdinando Auricchio, [_Automatic Differentiation for Solid Mechanics_](https://link.springer.com/article/10.1007/s11831-019-09396-y).

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by avigliotti** [comment]
Hi @KZiemian, thanks for your interest in the repo, I'm still working on the subject and I will post some updates soon,

best,
Andrea
