### ISSUE TITLE
InferOpt.jl: combinatorial optimization in ML pipelines | G Dalle, L Bouvier, L Baty | JuliaCon 2022

### ISSUE THREAD

**Issue by BatyLeo** [JuliaCommunity/YouTubeVideoTimestamps#203]
Video link: https://www.youtube.com/watch?v=yB86STwZB_M&t=1s
Pluto notebook slides: https://github.com/gdalle/InferOpt-JuliaCon2022
Package repository: https://github.com/axelparmentier/InferOpt.jl
Preprint paper: https://arxiv.org/abs/2207.13513

0:06 Introduction
1:01 What is it for ?
3:41 Example application 1: Shortest Paths on Warcraft maps
6:30 Example application 2: Stochastic Vehicle Scheduling
10:29 Theoretical background: regularization and Fenchel-Young loss
13:14 Tutorial
23:30 Conclusion

**Comment by KZiemian** [comment]
I will try to make this repository work again. Wish me luck. In the mean time I tweaked your work.

Contents
00:00 Opening and introduction
01:01 What is it for?
03:41 Example application 1: Shortest Paths on Warcraft maps
06:30 Example application 2: Stochastic Vehicle Scheduling
10:29 Theoretical background: regularization and Fenchel-Young loss
13:14 Tutorial
23:30 Conclusion

InferOpt.jl, [repository](https://github.com/axelparmentier/InferOpt.jl).
Pluto notebooks of presentation, [repository](https://github.com/gdalle/InferOpt-JuliaCon2022).
Guillaume Dalle, Léo Baty, Louis Bouvier, Axel Parmentier, [_Learning with Combinatorial Optimization Layers: a Probabilistic Approach_](https://arxiv.org/abs/2207.13513).

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
Everything seems to work, so we close the issue.
