### ISSUE TITLE
JuMP 1.0: What you need to know | Miles Lubin | JuliaCon 2022 

### ISSUE THREAD

**Issue by digital-carver** [JuliaCommunity/YouTubeVideoTimestamps#204]
Link to the talk: https://www.youtube.com/watch?v=Fc5Z90k34I0

JuMP on Github: https://github.com/jump-dev/JuMP.jl/
JuMP docs: https://jump.dev/JuMP.jl/stable/

00:06 Introduction
00:21 Talk outline
00:45 What is JuMP? 
01:28 Example JuMP code
02:48 The zoo of modeling languages
03:30 Why is JuMP interesting? 
07:03 What is JuMP used for?
12:50 Case study: PSR
14:14 JuMP as a framework
15:43 JuMP 1.0 and how we got here
20:41 What you need to know
22:21 What's next
22:54 Thank you!

**Comment by KZiemian** [comment]
If will try to bring timestamps issue back to life, wish me life. In the meantime I tweaked a bit your work.

Contents
00:00 Opening and introduction
00:21 Talk outline
00:45 What is JuMP?
01:28 Example JuMP code
02:48 The zoo of modeling languages
03:30 Why is JuMP interesting?
07:03 What is JuMP used for?
12:50 Case study: PSR
14:14 JuMP as a framework
15:43 JuMP 1.0 and how we got here
20:41 What you need to know
22:21 What's next
22:54 Thank you!

Resources
JuMP [repository](https://github.com/jump-dev/JuMP.jl/).
JuMP [documentation](https://jump.dev/JuMP.jl/stable/).

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
Since everything looks fine, we are closing the issue.
