### ISSUE TITLE
 Simple Chains: Fast CPU Neural Networks | Chris Elrod | JuliaCon 2022 

### ISSUE THREAD

**Issue by digital-carver** [JuliaCommunity/YouTubeVideoTimestamps#205]
Link to the talk: https://www.youtube.com/watch?v=rfBYA1gZa6E

SimpleChains on Github: https://github.com/PumasAI/SimpleChains.jl
SimpleChains documentation: https://pumasai.github.io/SimpleChains.jl/stable/

00:05  What is SimpleChains? 
01:20 Example (MNIST classification)
01:52 MNIST example: Why MNIST? 
02:48 Multithreading/processing, AVX
03:33 MNIST example: Model syntax
05:57 Training performance and accuracy
06:38 Benchmarks
07:31 What makes SimpleChains so much faster?

**Comment by KZiemian** [comment]
I add these two changed lines for the future use and tweaked first time entry. I hope it will help with copy-pasting on YT.

Contents
00:00 What is [SimpleChains.jl](https://github.com/PumasAI/SimpleChains.jl)?
01:20 Example (MNIST classification)
01:52 MNIST example: Why MNIST?
02:48 Multithreading/processing, AVX
03:33 MNIST example: Model syntax
05:57 Training performance and accuracy
06:38 Benchmarks
07:31 What makes [SimpleChains.jl](https://github.com/PumasAI/SimpleChains.jl) so much faster?

Resources
SimpleChains.jl [repository](https://github.com/PumasAI/SimpleChains.jl).
SimpleChains.jl [documentation](https://pumasai.github.io/SimpleChains.jl/stable/).

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.
