### ISSUE TITLE
 Data Analysis and Visualization with AlgebraOfGraphics | Pietro Vertechi | JuliaCon 2022 

### ISSUE THREAD

**Issue by digital-carver** [JuliaCommunity/YouTubeVideoTimestamps#206]
Link to the talk: https://www.youtube.com/watch?v=XWzkj6ODJYk

AlgebraOfGraphics on Github: https://github.com/JuliaPlots/AlgebraOfGraphics.jl
AlgebraOfGraphics documentation: http://juliaplots.org/AlgebraOfGraphics.jl/stable/

00:16 Structure of the talk
00:56 From data to visualization: representing data graphically
02:47 Philosophy of AlgebraOfGraphics
03:59 Example usage: How does AlgebraOfGraphics work?
07:11 The AlgebraOfGraphics Gallery
08:16  Prototype GUI for AlgebraOfGraphics
08:44 Thank you!

**Comment by KZiemian** [comment]
I slightly tweaked your work.

Contents
00:00 Opening
00:16 Structure of the talk
00:56 From data to visualization: representing data graphically
02:47 Philosophy of [AlgebraOfGraphics.jl](https://github.com/JuliaPlots/AlgebraOfGraphics.jl)
03:59 Example usage: How does [AlgebraOfGraphics.jl](https://github.com/JuliaPlots/AlgebraOfGraphics.jl) work?
07:11 The [AlgebraOfGraphics.jl](https://github.com/JuliaPlots/AlgebraOfGraphics.jl) Gallery
08:16 Prototype GUI for [AlgebraOfGraphics.jl](https://github.com/JuliaPlots/AlgebraOfGraphics.jl)
08:44 Thank you!

Resources
AlgebraOfGraphics.jl [repository](https://github.com/JuliaPlots/AlgebraOfGraphics.jl).
AlgebraOfGraphics.jl [documentation](http://juliaplots.org/AlgebraOfGraphics.jl/stable/).

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We now can close the issue.
