### ISSUE TITLE
 `do block` considered harmless | Nicolau Leal Werneck | JuliaCon 2022 

### ISSUE THREAD

**Issue by digital-carver** [JuliaCommunity/YouTubeVideoTimestamps#207]
Link to the talk: https://www.youtube.com/watch?v=2VccdiX-9Tg

---

**Pull Requests/Proposals mentioned in the talk**:
* Have **flatmap** out of the box - https://github.com/JuliaLang/julia/pull/44792
* Unfold() - https://github.com/JuliaLang/julia/pull/44873
* Iterable alternative for optional types, also futures - https://github.com/JuliaLang/julia/pull/44864
* Review performance of functional combinators - https://github.com/JuliaLang/julia/issues/45000

do-block section in the Julia manual: https://docs.julialang.org/en/v1/manual/functions/#Do-Block-Syntax-for-Function-Arguments

00:06 Introduction 
00:25 Why is do-syntax so cool? 
02:24 Why avoid writing for-loops?
04:13 Can it really be done? (Limitations)
05:16 Illustrative example: simple for loop
05:59 Illustrative example: nested for loop
06:41 Proposals 
07:26 Conclusion

**Comment by digital-carver** [comment]
Github auto-converted the plain URLs I posted (as links to the PRs/proposals) into the fancy output above. In case that makes it harder to copy, here's the same list with `githubcom` instead of `github.com` (the dot removed) so Github doesn't mess with them:

**Pull Requests/Proposals mentioned in the talk**:
* Have **flatmap** out of the box - https://githubcom/JuliaLang/julia/pull/44792
* Unfold() - https://githubcom/JuliaLang/julia/pull/44873
* Iterable alternative for optional types, also futures - https://githubcom/JuliaLang/julia/pull/44864
* Review performance of functional combinators - https://githubcom/JuliaLang/julia/issues/45000

**Comment by nlw0** [comment]
Hey, thanks for the work!

**Comment by digital-carver** [comment]
Thanks for the talk! The flexibility and variety of syntax options is one of my favourite things about Julia. It's great to see them explored to their full power.

**Comment by KZiemian** [comment]
I tweaked materials in this thread a bit.

Contents
00:00 Opening and introduction
00:25 Why is do-syntax so cool?
02:24 Why avoid writing for-loops?
04:13 Can it really be done? Limitations of the approach
05:16 Illustrative example: simple for loop
05:59 Illustrative example: nested for loop
06:41 Proposals
07:26 Conclusion

Resources
Julia manual section on `do-block`, [link](https://docs.julialang.org/en/v1/manual/functions/#Do-Block-Syntax-for-Function-Arguments).
Pull request [_Implements flatmap_](https://github.com/JuliaLang/julia/pull/44792).
Pull request [_mapreduce: use simpler reduction order in some cases_](https://github.com/JuliaLang/julia/issues/45000).
Pull request [_Unfold() is an iterable based on a transition function_](https://github.com/JuliaLang/julia/pull/44873).

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
It looks to me, that we can close the issue.
