### ISSUE TITLE
Interactive Julia Data Dashboards with Genie | Adrian Salceanu, Helmut Hänsel | JuliaCon 2022

### ISSUE THREAD

**Issue by cpalumbo** [JuliaCommunity/YouTubeVideoTimestamps#208]
Link to the talk: https://www.youtube.com/watch?v=YEQLTCWxDuM
For a longer version of this tutorial and for accessing the demo app, visit https://genieframework.com/juliacon/

🧞 Genie Builder on the VSCode Marketplace: https://marketplace.visualstudio.com/items?itemName=GenieBuilder.geniebuilder
🗒️ Genie Framework Documentation: https://genieframework.com/
💻 Genie Framework Github: https://github.com/GenieFramework

00:06 - Introduction
02:25 - Building our data dashboard
03:10 - Building our UI with Genie Builder (no-code editor)
06:40 - Backend and data functions; connecting UI with backend
15:05 - Advanced plotting and data interactions
22:42 - Deploying our dashboard

**Comment by KZiemian** [comment]
I allow myself to tweak your materials a little.

Contents
00:00 Opening and introduction
02:25 Building our data dashboard
03:10 Building our UI with Genie Builder (no-code editor)
06:40 Backend and data functions; connecting UI with backend
15:05 Advanced plotting and data interactions
22:42 Deploying our dashboard

Resources
Genie framework [repository](https://github.com/GenieFramework).
Genie framework [documentation](https://genieframework.com/).
Genie Builder on the VSCode Marketplace, [link](https://marketplace.visualstudio.com/items?itemName=GenieBuilder.geniebuilder).

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We now can close the issue.
