### ISSUE TITLE
Seam Carving | Week 2 | 18.S191 MIT Fall 2020 | Grant Sanderson

### ISSUE THREAD

**Issue by Pokechu22** [JuliaCommunity/YouTubeVideoTimestamps#211]
https://www.youtube.com/watch?v=rpB6zQNsbQU

This video already has timestamps in the description, but it also has placeholder timestamps, and YouTube is picking up on those instead of the correct timestamps.  The actual timestamps seem good to me.

![image](https://user-images.githubusercontent.com/8334194/183155897-431bae7c-ff27-4930-94d4-cfa4a2705749.png)

**Comment by KZiemian** [comment]
Maybe this problem was already mentioned [here](https://github.com/JuliaCommunity/YouTubeVideoTimestamps/issues/106)? In any case, it make take a time, before this one get fixed.

**Comment by Pokechu22** [comment]
Looks like this specific video isn't mentioned in that issue, but there are other videos with the same issue mentioned there.

**Comment by KZiemian** [comment]
At this moment I can't do anything to fix this, but maybe @logankilpatrick will find a way to make this correction faster?

**Comment by logankilpatrick** [comment]
I think I just fixed this, can one of you check?

**Comment by Pokechu22** [comment]
It seems to still be broken to me (no chapters show up at all); try changing the "24:06 Other images and uses 00:00 Welcome!" line to "24:06 Other images and uses".

**Comment by KZiemian** [comment]
I don''t want to promise anything, but there is real chance that at least some of this corrections will be made in this week.

**Comment by KZiemian** [comment]
@Pokechu22 I want to revitalize the whole repository for timestamping, but I just normal Julia user. Wish me good luck, I probably will need it.

**Comment by KZiemian** [comment]
This video is fixed, we can now close the issue.

**Comment by KZiemian** [comment]
I will try to watch for problems like this one. Open issue, when you find another video with such problem. We can now close this particular issue.
