### ISSUE TITLE
Optimising Fantasy Football with JuMP | Dean Markwick | JuliaCon 2022

### ISSUE THREAD

**Issue by digital-carver** [JuliaCommunity/YouTubeVideoTimestamps#212]
Link to the talk: https://www.youtube.com/watch?v=IS-lziTqClE

Accompanying Blog Post: https://dm13450.github.io/2022/08/05/FPL-Optimising.html

00:05 Introduction
00:10 What is Fantasy Premier League (FPL)? 
00:52 Objective of this talk
01:15 An FPL season in 2 minutes
02:47 The human decision making process in FPL
03:21 Applying JuMP to FPL - the Basics
03:41 Level 1: Choosing the best team (given the squad)
05:33 Level 2: Choosing the optimal 15-person squad
06:56 Conclusions
07:17 Thanks!

**Comment by KZiemian** [comment]
I tweaked unimportant things, to make it more copy-pastable (at least this is my hope).

Contents
00:00 Opening and introduction
00:10 What is Fantasy Premier League (FPL)?
00:52 Objective of this talk
01:15 An FPL season in 2 minutes
02:47 The human decision making process in FPL
03:21 Applying JuMP to FPL - the Basics
03:41 Level 1: Choosing the best team (given the squad)
05:33 Level 2: Choosing the optimal 15-person squad
06:56 Conclusions
07:17 Thanks!

Resources
Accompanying Blog Post, [link](https://dm13450.github.io/2022/08/05/FPL-Optimising.html).

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We can now close the issue.
