### ISSUE TITLE
JuliaCon 2022 YouTube Playlist has duplicate videos (14 remaining)

### ISSUE THREAD

**Issue by ericjmorey** [JuliaCommunity/YouTubeVideoTimestamps#213]
Of the 229 videos on the JuliaCon 2022 YouTube Playlist, there are 14 duplicates remaining after an initial attempt to clean up the list.

[Playlist: The 9th annual JuliaCon, 2022 (Online) The Julia Programming Language All the keynotes, talks and sponsor presentations from the 9th annual JuliaCon 2022. #julialang](https://m.youtube.com/playlist?list=PLP8iPy9hna6TRg6qJaBLJ-FRMi9Cp7gSX)

Duplicate videos are listed below:

Title, Video URL
--
From Mesh Generation to Adaptive Simulation: A Journey in Julia \| Andrew Winters \| JuliaCon 2022, https://www.youtube.com/watch?v=_N4ozHr-t9E
Automatic Differentiation for Quantum Electron Structure \| M Towara, N Schmitz, G Kemlin, https://www.youtube.com/watch?v=21XdZYGZfOg
GapTrain: a faster and automated way to generate GA potentials \| Letícia Madureira \| JuliaCon 2022, https://www.youtube.com/watch?v=5PDC_ZDQIC8
A user’s perspective on using JuMP in an academic project \| Mathieu Tanneau \| JuliaCon 2022, https://www.youtube.com/watch?v=61fnHmri7_Q
Modeling Instron's Crash Simulation System with ModelingToolkit.jl \| Bradley Carman \| JuliaCon 2022, https://www.youtube.com/watch?v=ChwKqrH8OQU
Simulation of atmospheric turbulence with MicroHH.jl \| Chiel van Heerwaarden \| JuliaCon 2022, https://www.youtube.com/watch?v=CQagmbX4je4
RangeEnclosures.jl: a flexible API to bound function ranges \| Luca Ferranti \| JuliaCon 2022, https://www.youtube.com/watch?v=hMIwqoLj6S8
Using contexts and capabilities to provide privacy protection \| Tom Kwong \| JuliaCon 2022, https://www.youtube.com/watch?v=JDugc977VSw
TintiNet.jl: a language model for protein 1D property estimation \| Guilherme Fahur Bottino, https://www.youtube.com/watch?v=Q6xWyAe8J38
Reaction rates and phase diagrams in ElectrochemicalKinetics.jl \| Rachel Kurchin \| JuliaCon 2022, https://www.youtube.com/watch?v=QUKBobLoykY
PDDL.jl: A fast and flexible interface for automated planning \| Xuan (Tan Zhi Xuan) \| JuliaCon 2022, https://www.youtube.com/watch?v=S757gSLScwM
A matrix-free fix-propagate-and-project heuristic for MILPs \| Mathieu Besançon \| JuliaCon 2022, https://www.youtube.com/watch?v=x3UeFdje6jM
SparseVariables - Efficient sparse modelling with JuMP \| Lars Hellemo \| JuliaCon 2022, https://www.youtube.com/watch?v=YuDvfZo9W5A
From Mesh Generation to Adaptive Simulation: A Journey in Julia \| Andrew Winters \| JuliaCon 2022, https://www.youtube.com/watch?v=_N4ozHr-t9E

**Comment by KZiemian** [comment]
I will try to check if this is still a case and if so, I will try to bring more attention to your issue.

**Comment by KZiemian** [comment]
I believe it is now fixed. If someone will confirm that, we can close this issue.

**Comment by ericjmorey** [comment]
I'll take a look this week

**Comment by KZiemian** [comment]
I now want to check playlist form JuliaCon 2023. When I will be done with it, I will try check this playlist myself, so no need to hurry.

**Comment by KZiemian** [comment]
After removing duplicated mentioned above, I checked playlist and cannot find posted two times. But I still hesitated with closing this issue.

**Comment by KZiemian** [comment]
I check this playlist two time, everything seems to be alright. As a result, I will close the issue.
