### ISSUE TITLE
Quantum computing with ITensor and PastaQ | Matthew Fishman, Giacomo Torlai | JuliaCon 2022

### ISSUE THREAD

**Issue by amin13afa** [JuliaCommunity/YouTubeVideoTimestamps#215]
Hi Logan 
Thanks for your endless efforts.
This video is chosen as my first timestamp project, please let me know if there is any problem.

References:
Speaker: Matthew Fishman
Video title: Quantum computing with ITensor and PastaQ | Matthew Fishman, Giacomo Torlai | JuliaCon 2022
Link:[Video](https://www.youtube.com/watch?v=Mm5EaBnDSbs)
Link to the code: [Code](https://github.com/amin13afa/JuliaCon2022_ITensor_PastaQ)

0:00 Welcome 
0:19 Introduction 
0:41 Introduction to quantum computing 
1:43 Quantum computers' potential applications 
2:31 Remaining quantum computers challenges 
3:00 Complexity of simulating a quantum computer 
4:18 Introduction to tensor network diagrams 
5:43 Representation of qubit states in tensor network diagrams 
6:00 Introduction to ITensor 
7:27 Tensor contraction in ITensor 
9:01 Advantages and disadvantages of ITensor 
9:48 SVD of a tensor 
11:09 Tensor network example 
12:36 Different types of tensor network 
13:06 Gradient calculations of tensor network 
14:23 Applications of tensor network calculations to quantum computing 
15:20 Full state simulation of a quantum process 
16:08 PastaQ 
16:58 A simple code in PastaQ 
18:17 Simulation of the ground-state of a quantum many-body system 
22:14 Summary 
23:51 Future directions

I'm waiting for your feedback.

**Comment by KZiemian** [comment]
I try to revitalised the project. Here is your work slightly tweaked.

Contents
00:00 Welcome
00:19 Introduction
00:41 Introduction to quantum computing
01:43 Quantum computers' potential applications
02:31 Remaining quantum computers challenges
03:00 Complexity of simulating a quantum computer
04:18 Introduction to tensor network diagrams
05:43 Representation of qubit states in tensor network diagrams
06:00 Introduction to [ITensor](https://github.com/ITensor)
07:27 Tensor contraction in [ITensor](https://github.com/ITensor)
09:01 Advantages and disadvantages of [ITensor](https://github.com/ITensor)
09:48 SVD of a tensor
11:09 Tensor network example
12:36 Different types of tensor network
13:06 Gradient calculations of tensor network
14:23 Applications of tensor network calculations to quantum computing
15:20 Full state simulation of a quantum process
16:08 PastaQ
16:58 A simple code in PastaQ
18:17 Simulation of the ground-state of a quantum many-body system
22:14 Summary
23:51 Future directions

Resources
ITensor [repository](https://github.com/ITensor)
Implementation of code disscused during presentation, [link](https://github.com/amin13afa/JuliaCon2022_ITensor_PastaQ).

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
Everything seems to work properly, so we close the issue.
