### ISSUE TITLE
Contributing to Open Source with Technical Writing. | Ifihanagbara Olusheye | JuliaCon 2022

### ISSUE THREAD

**Issue by dmarinere** [JuliaCommunity/YouTubeVideoTimestamps#217]
Added timestamp for this talk 
link https://www.youtube.com/watch?v=MPw9KMujWEI
TItle  Contributing to Open Source with Technical Writing.

**Comment by KZiemian** [comment]
Excuse me, where your timestamps can be found? I didn't see it here, not in pull request.

**Comment by KZiemian** [comment]
Thank you. I think we can now close this issue.

**Comment by KZiemian** [comment]
From what I see, we can now close the issue.
