### ISSUE TITLE
Getting started with Julia and Machine Learning | Anthony Blaom & Samuel | JuliaCon 2022

### ISSUE THREAD

**Issue by ktzhao** [JuliaCommunity/YouTubeVideoTimestamps#219]
References:
Speaker: Anthony Blaom & Samuel
Video title: Getting started with Julia and Machine Learning | Anthony Blaom & Samuel | JuliaCon 2022
Link: https://www.youtube.com/watch?v=uFBPMQ9Ns-E
Link to the code: https://github.com/ablaom/HelloJulia.jl

Contents
0:00 Welcome & Introduction
02:14 0 Outline
05:10 1 Workshop Resources
09:40 2 Machine Learning 
11:35 2.1 Supervised Learning
20:56 2.1.1 Survival of Passengers on the Titanic
24:45 3.1 Begin of Coding (Tutorial 1)
41:53 3.1.1 Functions
46:30 3.1.2 Iterate
56:00 3.1.3 Pluto Notebook
1:01:42 3.1.4 Probability Distributions
1:08:48 3.1.5 Plotting
1:13:30 3.2 Tutorial 2: Dataframe
1:20:39 Skip Coffee Break
1:28:09 OpenML
1:30:06 3.2.1 Grabbing the Titanic dataset 
1:40:40 3.3 Tutorial 3: Machine Learning
1:40:43 3.3.1 Scitype
1:46:43 3.3.1 Titanic Data 
2:09:30 3.3.2 Splitting Data into train and test sets
2:13:13 3.3.3 Cleaning Data
2:22:47 3.3.4 Splitting Data into input features and target
2:28:05 3.3.5 Choosing model
2:33:04 3.3.6 The fit/predict worflow
2:39:00 4 Q&A

**Comment by KZiemian** [comment]
I try to revitalize this project, wish me good luck. In the meantime, I tweaked a bit your work.

Contents
00:00, Opening and introduction
02:14, 0. Outline
05:10, 1. Workshop resources
09:40, 2. Machine Learning
11:35, 2.1. Supervised Learning
20:56, 2.1.1. Survival of Passengers on the Titanic
24:45, 3.1. Begin of Coding (Tutorial 1)
41:53, 3.1.1. Functions
46:30, 3.1.2. Iterate
56:00, 3.1.3. [Pluto.jl](https://plutojl.org/) notebook
1:01:42, 3.1.4. Probability Distributions
1:08:48, 3.1.5. Plotting
1:13:30, 3.2. Tutorial 2: Dataframe
1:20:39, Skip Coffee Break
1:28:09, OpenML
1:30:06, 3.2.1. Grabbing the Titanic dataset
1:40:40, 3.3. Tutorial 3: Machine Learning
1:40:43, 3.3.1. Scitype
1:46:43, 3.3.1. Titanic data
2:09:30, 3.3.2. Splitting data into train and test sets
2:13:13, 3.3.3. Cleaning data
2:22:47, 3.3.4. Splitting data into input features and target
2:28:05, 3.3.5. Choosing model
2:33:04, 3.3.6. The fit/predict worflow
2:39:00, 4. Q&A

Resources
Code of workshops, [link](https://github.com/ablaom/HelloJulia.jl).
Pluto.jl [home page](https://plutojl.org/).
Pluto.jl [repository](https://github.com/fonsp/Pluto.jl).

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We now can close the issue.
