### ISSUE TITLE
Building an Immediate-Mode GUI (IMGUI) from scratch | Siddharth Bhatia | JuliaCon 2022

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaCommunity/YouTubeVideoTimestamps#222]
Talk title: Building an Immediate-Mode GUI (IMGUI) from scratch | Siddharth Bhatia | JuliaCon 2022
Talk link: https://www.youtube.com/watch?v=-z8_F9ozERc

Contents
00:00 - JuliaCon 2022 welcome screen
00:06 - Brief introduction to Graphical User Interfaces (GUIs)
01:46 - Partial pseudocode of a GUI application
03:49 - Handling user input (mouse/keyboard events)
08:13 - Widget related pseudocode in a GUI application
09:59 - Widget IDs - uniquely identify widgets across frames
12:22 - User interaction and the concept of hot and active widgets
18:35 - Implementing buttons, sliders, and text-boxes
23:26 - Outro

**Comment by KZiemian** [comment]
I allowed myself to tweak a bit your work, to make it easier to past it on YT. I hope soon project will be bring back to life.

Contents
00:00 Brief introduction to Graphical User Interfaces (GUIs)
01:46 Partial pseudocode of a GUI application
03:49 Handling user input (mouse/keyboard events)
08:13 Widget related pseudocode in a GUI application
09:59 Widget IDs - uniquely identify widgets across frames
12:22 User interaction and the concept of hot and active widgets
18:35 Implementing buttons, sliders, and text-boxes
23:26 Outro

**Comment by Sid-Bhatia-0** [comment]
Thank you @KZiemian. It makes sense to remove the welcome screen tag. It isn't helping.

I am not sure if this PR will be merged. Anyways, I have updated my comment on the video itself with the change.

> I hope soon project will be bring back to life.

I am working on a game that uses this library, so I might potentially add some improvements to it later. 😄

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by Sid-Bhatia-0** [comment]
Thank you very much!

**Comment by KZiemian** [comment]
Timestamps added, we are closing the issue.
