### ISSUE TITLE
Katharine Hyatt: Quantum Statistical Simulations with Julia

### ISSUE THREAD

**Issue by YingHongTham** [JuliaCommunity/YouTubeVideoTimestamps#224]
Link: https://www.youtube.com/watch?v=QThApV3HIxc
Video title: Quantum Statistical Simulations with Julia
Speaker: Katharine Hyatt

Contents:
0:37 Introduction - "Quantum?" "Statistical?"
2:39 How numerics helps - simulations
3:54 Finding the ground state - 3 techniques
4:19 Density Matrix Renormalization Group
5:49 Quantum Monte Carlo
10:18 Exact Diagonalization
11:19 Numerics in Condensed Matter Theory - problem: most physicists aren't coders
13:40 Julia to the rescue
17:29 Our experience with Julia
23:33 Summary
26:21 Questions
26:22 Question on using clusters; Julia is architecture-agnostic
29:41 Question: when do exact diag, want a fraction of modes or just one?
32:13 Question: Julia impact on peer review
34:25 Comment from audience, code vs paper is primary
35:16 Thanks on something
35:37 Question: Julia shortcomings?

Hope this helps

**Comment by KZiemian** [comment]
Thank you. I will work on making this project back to life. I also tweaked a bit your work.

Contents
00:00 Welcome!
00:37 Introduction: "Quantum"? "Statistical"?
02:39 How numerics helps: simulations
03:54 Finding the ground state: 3 techniques
04:19 Density Matrix Renormalization Group
05:49 Quantum Monte Carlo
10:18 Exact Diagonalization
11:19 Numerics in Condensed Matter Theory. Problem: most physicists aren't coders
13:40 Julia to the rescue
17:29 Our experience with Julia
23:33 Summary
26:22 Q&A: using clusters; Julia is architecture-agnostic
29:41 Q&A: when do exact diag, want a fraction of modes or just one?
32:13 Q&A: Julia impact on peer review
34:25 Comment from audience, code vs paper is primary
35:16 Thanks on something
35:37 Q&A: Julia shortcomings?

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We can now close the issue.
