### ISSUE TITLE
Matrix Structures | Week3 | 18.S191 MIT Fall 2020

### ISSUE THREAD

**Issue by YingHongTham** [JuliaCommunity/YouTubeVideoTimestamps#225]
References:
Speaker: Alan Edelman
Video title: Matrix Structures | Week3 | 18.S191 MIT Fall 2020
Link: https://www.youtube.com/watch?v=zoUeUG-Sm6g

Contents
0:56 Take away: take advantage of structure (to save space/time)
1:38 in Julia, no overhead -> can easily take advantage of structure
1:58 One-hot vectors
3:00 just store two numbers
3:58 build OneHot as subtype of AbstractVector
4:13 julia syntax: '<:' - subtype constructor
4:48 define two functions for OneHot 
7:18 representing in pictures
8:30 Diagonal matrices - in LinearAlgebra package
10:05 Sparse matrix representation
11:10 i,j, a_ij representation
11:20 CSC - Column Sparse Compressed format (default julia)
14:14 Another way of compressing - "summarizing numbers"
14:26 Random vector - what essential information to store?
15:25 Mean and standard deviation enough (in some contexts)
17:04 Multiplication tables (outer product of two vectors)
18:47 How much information in multiplication tables?
21:10 Check if matrix is multiplication table
23:06 add multiplication tables
23:29 Can one find out if matrix is sum of multiplication tables?
23:55 Answer: Singular Value Decomposition
23:50 Example for sum of outer products: flags
28:30 Example for using SVD to get matrix as sum of outer products: image processing
28:40 extract 3 matrices, one for each RGB channel
30:00 using SVD
30:15 one outer product - very bad
30:42 sum two outer products - minecraft tree
31:15 sum of 3, 4, etc. - image gets clearer
32:48 this is idea behind Principal Component Analysis in statistics

**Comment by KZiemian** [comment]
This GitHub repo is now at sleep, I will try to weak it up. I also allowed myself to tweaked your work.

Contents
00:56 Take away: take advantage of structure (to save space/time)
01:38 In Julia, no overhead -> can easily take advantage of structure
01:58 One-hot vectors
03:00 Just store two numbers
03:58 Build OneHot as subtype of AbstractVector
04:13 Julia syntax '<:' for subtype constructor
04:48 Define two functions for OneHot
07:18 Representing in pictures
08:30 Diagonal matrices - in LinearAlgebra package
10:05 Sparse matrix representation
11:10 i, j, a_ij representation
11:20 CSC, Column Sparse Compressed format (default julia)
14:14 Another way of compressing - "summarizing numbers"
14:26 Random vector, what essential information to store?
15:25 Mean and standard deviation enough (in some contexts)
17:04 Multiplication tables (outer product of two vectors)
18:47 How much information in multiplication tables?
21:10 Check if matrix is multiplication table
23:06 Add multiplication tables
23:29 Can one find out if matrix is sum of multiplication tables?
23:55 Answer: Singular Value Decomposition
23:50 Example for sum of outer products: flags
28:30 Example for using SVD to get matrix as sum of outer products: image processing
28:40 Extract 3 matrices, one for each RGB channel
30:00 Using SVD
30:15 One outer product - very bad
30:42 Sum two outer products, minecraft tree
31:15 Sum of 3, 4, etc., image gets clearer
32:48 This is an idea behind Principal Component Analysis in statistics

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
Everything seems be in place, so we close this issue.
