### ISSUE TITLE
Reproducible Publications with Julia and Quarto | J.J. Allaire | JuliaCon 2022

### ISSUE THREAD

**Issue by nelsonpray** [JuliaCommunity/YouTubeVideoTimestamps#228]
References:
Speaker: J.J. Allaire
Video title: Reproducible Publications with Julia and Quarto | J.J. Allaire | JuliaCon 2022
Link: https://www.youtube.com/watch?v=Y1uKNO32H_I
Slides: https://jjallaire.github.io/quarto-juliacon-2022/

Contents
00:00 Welcome
00:22 Overview
01:11 What is Quarto?
06:20 Simple Example
07:28 Code Cells
08:11 Rendering Pipeline
09:04 Creating Citations
09:41 Creating Cross References
10:50 Callouts
11:01 Advanced Page Layout
11:54 Diagrams
12:08 Output Formats
15:54 Quarto and Julia - Prerequisites
16:33 Basic Workflow
1728 IJulia
18:35 Performance Considerations
21:04 Why IJulia?
22:14 Tools - VS Code
23:18 Tools - Text Editors
23:49 Thank You

**Comment by KZiemian** [comment]
I will work to make this repo alive again. Wish me good luck.

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
I think we can close this issue.
