### ISSUE TITLE
Lessons learned while working as a technical writer at FluxML | JuliaCon 2023

### ISSUE THREAD

**Issue by g-adel** [JuliaCommunity/YouTubeVideoTimestamps#229]
References:
Speaker: Saransh Chopra
Video title: Lessons learned while working as a technical writer at FluxML | JuliaCon 2023
Link: https://www.youtube.com/watch?v=ieAjBVUl0tg

0:00 - Intro
0:22- Lesson 1 Clever documentation will push away beginners and newcomers
1:28- Lesson 2 There are no "perfect" docstrings
2:10 - Lesson 3 Doctests make documentation much more maintainable in the longer run
3:50 - Lesson 4 Broken cross-references and links are a big letdown for everyone
4:40 - Lesson 5 Scattered docs make it really hard to navigate to the right content
6:45 - Lesson 6 Utility infrastructure for documentation will make your life smooth

**Comment by KZiemian** [comment]
Thank you. I tweaked few things, to make it more copy-pastable.

Contents
0:00 Intro
0:22 Lesson 1: Clever documentation will push away beginners and newcomers
1:28 Lesson 2: There are no "perfect" docstrings
2:10 Lesson 3: Doctests make documentation much more maintainable in the longer run
3:50 Lesson 4: Broken cross-references and links are a big letdown for everyone
4:40 Lesson 5: Scattered docs make it really hard to navigate to the right content
6:45 Lesson 6: Utility infrastructure for documentation will make your life smooth

**Comment by KZiemian** [comment]
The link in the first post lead me to [Taking Vector Transposes Seriously](https://www.youtube.com/watch?v=C2RO34b_oPM).

**Comment by g-adel** [comment]
@KZiemian Fixed. Thanks

**Comment by KZiemian** [comment]
I think we can now close the issue.
