### ISSUE TITLE
Julia for Data Science | Video 1: Data

### ISSUE THREAD

**Issue by jgilis** [JuliaCommunity/YouTubeVideoTimestamps#230]
References:
Speaker: Dr. Huda Nassar
Video title: Julia for Data Science - Video 1: Data, by Dr. Huda Nassar (for JuliaAcademy.com)
Link: https://www.youtube.com/watch?v=iG1dZBaxS-U

0:00 - Intro
1:04 - Loading packages
2:20- Importing data: readdlm
4:52 - Importing data: CSV
12:25 - Importing data: XLSX
24:00 - Importing other data formats
29:58 - Process data from Julia
30:36 - Exercises on Array
34:03 - Exercises on Dataframe
36:08 - Exercises on Dictionary
44:53 - Wrap-up exercises
46:03 - Missing data
47:19 - Outro

**Comment by KZiemian** [comment]
Thank you. When waiting that this repo will be bring back to live, I tweaked a bit your work.

Contents
00:00 Intro
01:04 Loading packages
02:20 Importing data: readdlm
04:52 Importing data: CSV
12:25 Importing data: XLSX
24:00 Importing other data formats
29:58 Process data from Julia
30:36 Exercises on Array
34:03 Exercises on Dataframe
36:08 Exercises on Dictionary
44:53 Wrap-up exercises
46:03 Missing data
47:19 Outro

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
Description of video looks fine, so we will close the issue.
