### ISSUE TITLE
Julia for Data Science | Video 2: Linear Algebra

### ISSUE THREAD

**Issue by jgilis** [JuliaCommunity/YouTubeVideoTimestamps#231]
References:
Speaker: Dr. Huda Nassar
Video title: Julia for Data Science - Video 2: Linear Algebra, by Dr. Huda Nassar (for JuliaAcademy.com)
Link: https://www.youtube.com/watch?v=bndXPsRHPg0

0:00 - Intro
1:43 - Basic operations and types
9:55 - Backslash operator
11:50 - Factorizations
18:24 - Sparse linear algebra
21:34 - Images as matrices
34:40 - Outro

**Comment by KZiemian** [comment]
I tweaked it a bit.

Contents
00:00 Intro
01:43 Basic operations and types
09:55 Backslash operator
11:50 Factorizations
18:24 Sparse linear algebra
21:34 Images as matrices
34:40 Outro

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
Everything seems to be done, so we are closing issue.
