### ISSUE TITLE
Julia for Data Science | Video 3: Statistics

### ISSUE THREAD

**Issue by jgilis** [JuliaCommunity/YouTubeVideoTimestamps#232]
References:
Speaker: Dr. Huda Nassar
Video title: Julia for Data Science - Video 3: Statistics, by Dr. Huda Nassar (for JuliaAcademy.com)
Link: https://www.youtube.com/watch?v=AAGxWEJ_eWk

0:00 - Intro and geyser data
3:07 - Statistics plots
5:19 - Kernel density estimates
8:19 - Probability distributions
11:27 - Hypothesis testing
18:16 - AUC and confusion matrix
19:54 - Outro

**Comment by KZiemian** [comment]
Wish me luck with bringing this repository to life. I tweaked your work a bit, to make it slightly easier to handle.

Contents
00:00 Intro and geyser data
03:07 Statistics plots
05:19 Kernel density estimates
08:19 Probability distributions
11:27 Hypothesis testing
18:16 AUC and confusion matrix
19:54 Outro

**Comment by KZiemian** [comment]
We can now close this issue.

**Comment by KZiemian** [comment]
Timestamps for this video was already done in issue [169](https://github.com/JuliaCommunity/YouTubeVideoTimestamps/issues/169). Their are incorporated on YT, so we can close this issue.
