### ISSUE TITLE
Julia for Data Science | Video 4: Dimensionality Reduction

### ISSUE THREAD

**Issue by jgilis** [JuliaCommunity/YouTubeVideoTimestamps#233]
References:
Speaker: Dr. Huda Nassar
Video title: Julia for Data Science - Video 4: Dimensionality Reduction, by Dr. Huda Nassar (JuliaAcademy.com)
Link: https://www.youtube.com/watch?v=hIsYy04zO7U

0:00 - Intro and cars data
3:33 - PCA
10:25 - tSNE
12:32 - UMAP
14:37 - Outro

**Comment by KZiemian** [comment]
I slightly changed your work.

Contents
00:00 Intro and cars data
03:33 PCA
10:25 tSNE
12:32 UMAP
14:37 Outro

**Comment by KZiemian** [comment]
We can now close the issue.

**Comment by KZiemian** [comment]
This video has extensive timestamp done by [Chandu-4444](https://www.youtube.com/watch?v=hIsYy04zO7U), so we can close this issue.
