### ISSUE TITLE
Julia for Data Science | Video 5: Clustering

### ISSUE THREAD

**Issue by jgilis** [JuliaCommunity/YouTubeVideoTimestamps#234]
References:
Speaker: Dr. Huda Nassar
Video title: Julia for Data Science - Video 5: Clustering, by Dr. Huda Nassar (for JuliaAcademy.com)
Link: https://www.youtube.com/watch?v=cwurgt7cn5s

0:00 - Intro and houses data
4:36 - K-means clustering
8:13 - K-medoids clustering
9:53 - Hierarchical clustering
11:46 - DBscan
15:00 - Outro

**Comment by KZiemian** [comment]
I tweaked your work a bit.

Contents
00:00 Intro and houses data
04:36 K-means clustering
08:13 K-medoids clustering
09:53 Hierarchical clustering
11:46 DBscan
15:00 Outro

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We can now close the issue.
