### ISSUE TITLE
Julia for Data Science | Video 6: Classification

### ISSUE THREAD

**Issue by jgilis** [JuliaCommunity/YouTubeVideoTimestamps#237]
References:
Speaker: Dr. Huda Nassar
Video title: Julia for Data Science - Video 6: Classification, by Dr. Huda Nassar (for JuliaAcademy.com)
Link:https://www.youtube.com/watch?v=OQRPeIQasdo

0:00 - Intro and iris data
7:37 - Lasso
11:47 - Ridge
12:32 - Elastic net
13:03 - Decision trees
14:26 - Random forests
14:56 - Nearest neighbor method
18:07 - Support vector machine
18:53 - Warp-up (comparison)
20:04 - Outro

**Comment by KZiemian** [comment]
I tweaked your work a bit.

Contents
00:00 Intro and iris data
07:37 Lasso
11:47 Ridge
12:32 Elastic net
13:03 Decision trees
14:26 Random forests
14:56 Nearest neighbour method
18:07 Support vector machine
18:53 Warp-up (comparison)
20:04 Outro

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
Timestamps are in place, so we can close this issue.
