### ISSUE TITLE
Julia for Data Science | Video 7: Regression

### ISSUE THREAD

**Issue by jgilis** [JuliaCommunity/YouTubeVideoTimestamps#238]
References:
Speaker: Dr. Huda Nassar
Video title: Julia for Data Science - Video 7: Regression, by Dr. Huda Nassar (for JuliaAcademy.com)
Link: https://www.youtube.com/watch?v=5TCbIK_cpZE

0:00 - Intro
0:54 - Manual regression
2:04 - Regression with numpy
3:35 - Regression with Julia
4:55 - Wrangling of housing data
9:33 - Regression for housing data
14:03 - Logistic regression
18:05 - Non-linear regression]
21:22 - Outro

**Comment by KZiemian** [comment]
I tweaked your work a bit.

Contents
00:00 Intro
00:54 Manual regression
02:04 Regression with numpy
03:35 Regression with Julia
04:55 Wrangling of housing data
09:33 Regression for housing data
14:03 Logistic regression
18:05 Non-linear regression
21:22 Outro

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We can now close the issue.
