### ISSUE TITLE
Julia for Data Science | Video 8: Graphs

### ISSUE THREAD

**Issue by jgilis** [JuliaCommunity/YouTubeVideoTimestamps#239]
References:
Speaker: Dr. Huda Nassar
Video title: Julia for Data Science - Video 8: Graphs, by Dr. Huda Nassar (for JuliaAcademy.com)
Link: https://www.youtube.com/watch?v=1AgFyLpM3_4

0:00 - Intro
3:09 - Adjacency matrix
5:33 - LightGraphs package
6:05 - MatixNetworks package
7:16 - scomponents
8:46 - Degree distribution
12:09 - Shortest path problem
15:25 - Minimum spanning tree
17:07 - PageRank
19:52 - Clustering coefficients
21:43 - Outro

**Comment by KZiemian** [comment]
I hope that in the January 2024 your work will be available on YT.

Contents
00:00 Intro
03:09 Adjacency matrix
05:33 LightGraphs package
06:05 MatixNetworks package
07:16 scomponents
08:46 Degree distribution
12:09 Shortest path problem
15:25 Minimum spanning tree
17:07 PageRank
19:52 Clustering coefficients
21:43 Outro

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We now can close the issue.
