### ISSUE TITLE
Julia for Data Science | Video 9: Optimization

### ISSUE THREAD

**Issue by jgilis** [JuliaCommunity/YouTubeVideoTimestamps#240]
References:
Speaker: Dr. Huda Nassar
Video title: Julia for Data Science - Video 9: Optimization, by Dr. Huda Nassar (for JuliaAcademy.com)
Link: https://www.youtube.com/watch?v=7b9b6glGnjA

0:00 - Intro
1:32 - Problem 1: Portfolio investment
10:20 - Problem 2: Image recovery
14:38 - Problem 3: Diet optimization
21:10 - Problem 4: Passport
25:53 - Outro

**Comment by KZiemian** [comment]
Again, my tweaked version.

Contents
00:00 Intro
01:32 Problem 1: Portfolio investment
10:20 Problem 2: Image recovery
14:38 Problem 3: Diet optimization
21:10 Problem 4: Passport
25:53 Outro

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
Timestamps are in place. We can now close the issue.
