### ISSUE TITLE
Julia for Data Science | Video 10: Neural nets

### ISSUE THREAD

**Issue by jgilis** [JuliaCommunity/YouTubeVideoTimestamps#241]
References:
Speaker: Dr. Huda Nassar
Video title: Julia for Data Science - Video 10: Neural Nets, by Dr. Huda Nassar (for JuliaAcademy.com)
Link: https://www.youtube.com/watch?v=Oxi0Pfmskus

0:00 - Intro and MIST data
5:05 - Build the network
6:40 - Loss and accuracy
8:01 - Train the network
9:04 - Test the network
10:13 - Outro

**Comment by KZiemian** [comment]
Yet again, tweaked version.

Contents
00:00 Intro and MIST data
05:05 Build the network
06:40 Loss and accuracy
08:01 Train the network
09:04 Test the network
10:13 Outro

**Comment by KZiemian** [comment]
We can now close this issue.

**Comment by KZiemian** [comment]
The video already has timestamps made by [Ahm3rIjaz](https://github.com/Ahm3rIjaz), so we can close the issue.
