### ISSUE TITLE
Julia for Data Science | Video 11: Other languages

### ISSUE THREAD

**Issue by jgilis** [JuliaCommunity/YouTubeVideoTimestamps#242]
References:
Speaker: Dr. Huda Nassar
Video title: Julia for Data Science - Video 11: Other Languages, by Dr. Huda Nassar (for JuliaAcademy.com)
Link: https://www.youtube.com/watch?v=3DYJiAgApdk

0:00 - Intro
0:41 - Python
2:04 - R
5:17 - C
6:30 - Outro

**Comment by KZiemian** [comment]
I tweaked it a little.

Contents
0:00 Intro
0:41 Python
2:04 R
5:17 C
6:30 Outro

**Comment by KZiemian** [comment]
This video already has timestamps, again made by [Ahm3rIjaz ](https://github.com/Ahm3rIjaz), so we are closing the issue.
