### ISSUE TITLE
Julia for Data Science | Video 12: Visualization

### ISSUE THREAD

**Issue by jgilis** [JuliaCommunity/YouTubeVideoTimestamps#243]
References:
Speaker: Dr. Huda Nassar
Video title: Julia for Data Science - Video 12: Plots, by Dr. Huda Nassar (for JuliaAcademy.com)
Link: https://www.youtube.com/watch?v=-XvtUiNrCYM

0:00 - Intro
2:54 - Import data
4:20 - Violin plots
9:37 - Histograms and bar charts
14:32 - Insets
15:47 - Error bars
20:37 - Double axes
23:33 - High dimensional data in 2D
28:29 - Outro

**Comment by KZiemian** [comment]
I allowed myself to tweak your work.

Contents
00:00 Intro
02:54 Import data
04:20 Violin plots
09:37 Histograms and bar charts
14:32 Insets
15:47 Error bars
20:37 Double axes
23:33 High dimensional data in 2D
28:29 Outro

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We can now close the issue.
