### ISSUE TITLE
Quantum Monte Carlo in Julia | Rafał Pracht | JuliaCon 2023

### ISSUE THREAD

**Issue by ktzhao** [JuliaCommunity/YouTubeVideoTimestamps#247]
References:
Speaker: Rafał Pracht
Video title: Quantum Monte Carlo in Julia | Rafał Pracht | JuliaCon 2023
Link: https://www.youtube.com/watch?v=3VyeMS5L1fs

Contents
00:02 0 AGENDA
00:25 1 Quantum Circuits
00:25 1.1 QuantumCircuits.jl
00:40 1.2 Why
01:29 1.3 Asembler
02:58 2 Quantum Monte Carlo
02:59 2.1 Monte Carlo
03:33 2.2 Monte Carlo in finance
03:43 2.3 Option
04:43 2.4 The Quantum Monte Carlo
05:17 3 Implementation
05:18 3.1 The distribution loading 
05:53 3.2 Quantum Binomial Tree
06:20 3.3 The code
07:53 3.4 The number of paths
08:20 3.5 The papers and source

**Comment by KZiemian** [comment]
I tweaked your work a bit.

Contents
0:00, 0. Agenda
0:25, 1. Quantum Circuits
0:25, 1.1. QuantumCircuits.jl
0:40, 1.2. Why?
1:29, 1.3. Asembler
2:58, 2. Quantum Monte Carlo
2:59, 2.1. Monte Carlo
3:33, 2.2. Monte Carlo in finance
3:43, 2.3. Option
4:43, 2.4. The Quantum Monte Carlo
5:17, 3. Implementation
5:18, 3.1. The distribution loading
5:53, 3.2. Quantum Binomial Tree
6:20, 3.3. The code
7:53, 3.4. The number of paths
8:20, 3.5. The papers and source

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.
