### ISSUE TITLE
Polyhedral Computation | Benoît Legat | JuliaCon 2023

### ISSUE THREAD

**Issue by 99ashutosh** [JuliaCommunity/YouTubeVideoTimestamps#248]
References:
Speaker: Benoît Legat
Video title: Polyhedral Computation | Benoît Legat | JuliaCon 2023
Link: https://www.youtube.com/watch?v=YuxJtvgg6uc

Contents
00:00 Welcome!
00:10 What is Polyhedral computation?
01:00 Where is it used for?
01:40 Existing Libraries
02:00 Fastest Algorithm
04:15 JIT Representation
05:16 Overview of Polyhedral.jl Package
06:17 Questions
08:28 Outro

**Comment by KZiemian** [comment]
I will do my best, hopefully, to revitalized this repository.

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
I combined your timestamps with this presented in the issue [256](https://github.com/JuliaCommunity/YouTubeVideoTimestamps/issues/256) and posted it on the YT. We can now close the issue.
