### ISSUE TITLE
Shipping Julia Packages with System-Images | Venkateshprasad Bhat, Joris Kraak | JuliaCon 2023

### ISSUE THREAD

**Issue by 99ashutosh** [JuliaCommunity/YouTubeVideoTimestamps#249]
References:
Speaker: Venkateshprasad Bhat, Joris Kraak 
Video title: Shipping Julia Packages with System-Images | Venkateshprasad Bhat, Joris Kraak | JuliaCon 2023
Link: https://www.youtube.com/watch?v=3YnaAF0tIC8

Contents
00:00 Welcome!
00:10 Overview
01:02 Advantages of system images
01:48 Files to ship
02:58 Build Instructions
05:18 Questions
08:02 Outro

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We can now close the issue.
