### ISSUE TITLE
Julia Usecases in Actuarial Science Related Fields | Yun-Tien Lee | JuliaCon 2023

### ISSUE THREAD

**Issue by ktzhao** [JuliaCommunity/YouTubeVideoTimestamps#250]
References:
Speaker: Yun-Tien Lee
Video title: Julia Usecases in Actuarial Science Related Fields | Yun-Tien Lee | JuliaCon 2023
Link: https://www.youtube.com/watch?v=1LPqoxw2h2o

Contents
00:02 0 Introduction
00:37 1 Potential insurance analytics applications

01:19 1.1 Use case 1 - Similarity calculation
02:09 1.2 Use case 2 - Simulation
02:31 1.3 Use case 3 - Parameter estimation

03:34 2.1 Use case 1 - Similarity calculation (Categorical)
04:27 2.2 Use case 2 - Simulation (Variable Setup)
05:44 2.3 Use case 3 - Parameter estimation
06:50 3 Future work

**Comment by KZiemian** [comment]
I tweaked your work a bit.

Contents
00:00, 0. Introduction
00:37, 1. Potential insurance analytics applications
01:19, 1.1. Use case 1 - Similarity calculation
02:09, 1.2. Use case 2 - Simulation
02:31, 1.3. Use case 3 - Parameter estimation
03:34, 2.1. Use case 1 - Similarity calculation (Categorical)
04:27, 2.2. Use case 2 - Simulation (Variable Setup)
05:44, 2.3. Use case 3 - Parameter estimation
06:50, 3. Future work

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
I think everything is all right and we can close the issue.
