### ISSUE TITLE
Streaming Real Time Financial Market Data with AWS Cloud | Ruize Ren | JuliaCon 2023

### ISSUE THREAD

**Issue by ktzhao** [JuliaCommunity/YouTubeVideoTimestamps#252]
References:
Speaker: Ruize Ren
Video title: Streaming Real Time Financial Market Data with AWS Cloud | Ruize Ren | JuliaCon 2023
Link: https://www.youtube.com/watch?v=3XNsaPbLpoE

Contents
00:05 0 Introduction
00:14 1 Motivation 
00:56 2 Strategy
02:29 3 Alternative strategy
03:42 4 Example
04:56 5 Performance
05.41 6 Summary

**Comment by KZiemian** [comment]
I changed your work a bit.

Contents
0:05, 0. Introduction
0:14, 1. Motivation
0:56, 2. Strategy
2:29, 3. Alternative strategy
3:42, 4. Example
4:56, 5. Performance
5.41, 6. Summary

**Comment by KZiemian** [comment]
If I can, I want to point out, that if timestamps don't start from `0:00` or `00:00` they maybe not work properly on YT, which is mentioned [here](https://support.google.com/youtube/answer/9884579?hl=en). Typical problem is that they are not shown on the progress bar of the video. For this reason I allowed myself to tweak your work a bit, one example you can find [here](https://www.youtube.com/watch?v=3XNsaPbLpoE).

At this moment we can close this issue.

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We are closing the issue.
