### ISSUE TITLE
The New XGBoost Wrapper | Michael Savastio | JuliaCon 2023

### ISSUE THREAD

**Issue by ktzhao** [JuliaCommunity/YouTubeVideoTimestamps#253]
References:
Speaker: Michael Savastio
Video title: The New XGBoost Wrapper | Michael Savastio | JuliaCon 2023
Link: https://www.youtube.com/watch?v=d5v4ELN3NSc

Contents
00:05 0 Introduction
00:17 1 what is xgboost?
01:05 2 important recent contributors
02:02 3 XGBoost.jl TL;DR
02:38 4 XGBoost.jl features
04:31 5 the infamous windows error
05:34 6 TODO
06:32 7 pure Julia alternative: EvoTrees.jl
07:26 8 Q&A

**Comment by KZiemian** [comment]
I change your work a bit, I hope that it will help us in the future.

Contents
00:05, 0. Introduction
00:17, 1. What is xgboost?
01:05, 2. Important recent contributors
02:02, 3. XGBoost.jl TL;DR
02:38, 4. XGBoost.jl features
04:31, 5. The infamous windows error
05:34, 6. TODO
06:32, 7. Pure Julia alternative: EvoTrees.jl
07:26, 8. Q&A

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We now can close the issue.
