### ISSUE TITLE
Polyhedral Computation | Benoît Legat | JuliaCon 2023

### ISSUE THREAD

**Issue by ktzhao** [JuliaCommunity/YouTubeVideoTimestamps#256]
References:
Speaker: Benoît Legat
Video title: Polyhedral Computation | Benoît Legat | JuliaCon 2023
Link: https://www.youtube.com/watch?v=YuxJtvgg6uc

Contents

00:04 0 Introduction
00:16 1 What is Polyhedral Computation
01:00 2 What is it used for
01:40 3 Which libraries exists
02:01 4 Fastest algorithm depend on the class of polyhedra
04:16 5 Just In Time representation conversion
05:14 6 Polyhedra.jl interface
06:16 7 Q&A

**Comment by KZiemian** [comment]
Slightly changed version of your work.

Contents
00:00, 0. Opening and introduction
00:16, 1. What is Polyhedral Computation
01:00, 2. What is it used for
01:40, 3. Which libraries exists
02:01, 4. Fastest algorithm depend on the class of polyhedra
04:16, 5. Just In Time representation conversion
05:14, 6. Polyhedra.jl interface
06:16, 7. Q&A

**Comment by KZiemian** [comment]
Another timestamps for this video are in [248](https://github.com/JuliaCommunity/YouTubeVideoTimestamps/issues/248).

**Comment by KZiemian** [comment]
Since timestamps to this video was also presented in issue [248](https://github.com/JuliaCommunity/YouTubeVideoTimestamps/issues/248), I combined them two and put them on YT. I think I can now close this issue.
