### ISSUE TITLE
What's New with Progradio.jl - Projected Gradient Optimization | Eduardo M. G. Vila | JuliaCon 2023

### ISSUE THREAD

**Issue by ktzhao** [JuliaCommunity/YouTubeVideoTimestamps#257]
References:
Speaker: Eduardo M. G. Vila
Video title: What's New with Progradio.jl - Projected Gradient Optimization | Eduardo M. G. Vila | JuliaCon 2023
Link: https://www.youtube.com/watch?v=EZ2kq0Obaio

Contents

00:04 0 Introduction
00:06 1 What's new with Progradio.jl - Projected Gradient Optimization in Julia
02:01 2 JuDO - Julia for Dynamic Optimization 
02:54 3 Updates from Last Year's Release
03:12 4 Quasi-Wolfe Line Search
06:53 5 Simplex Constraints 
08:00 6 Changes to Problem Structure
08:41 7 Upcomong Changes & Future Work
09:36 8 Q&A

**Comment by KZiemian** [comment]
Can you look at my tweaked version?

Contents
0:00, 1. What's new with Progradio.jl, Projected Gradient Optimization in Julia
2:01, 2. JuDO - Julia for Dynamic Optimization
2:54, 3. Updates from Last Year's Release
3:12, 4. Quasi-Wolfe Line Search
6:53, 5. Simplex Constraints
8:00, 6. Changes to Problem Structure
8:41, 7. Upcomong Changes & Future Work
9:36, 8. Q&A

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We can now close the issue.
