### ISSUE TITLE
Multi-objective optimization with JuMP | Xavier Gandibleux | JuliaCon 2023

### ISSUE THREAD

**Issue by ktzhao** [JuliaCommunity/YouTubeVideoTimestamps#260]
References:
Speaker: Xavier Gandibleux
Video title: Multi-objective optimization with JuMP | Xavier Gandibleux | JuliaCon 2023
Link: https://www.youtube.com/watch?v=E3NdeUTdyFQ

Contents
00:06 0 Introduction
00:29 1 A chat at ROADEF in Feb 2016
01:34 2 Lecturing with Julia and JuMP (1st Course)
04:00 3 Short Survey on 3 aspects: student - Julia - JuMP
06:50 4 Lecturing with Julia and JuMP (2nd Course) 
07:48 5 Short Survey on 3 aspects: student - Julia+MOA
09:18 6 Conclusion

**Comment by KZiemian** [comment]
I tweaked your work a bit.

Contents
00:00, 0. Opening and introduction
00:29, 1. A chat at ROADEF in Feb 2016
01:34, 2. Lecturing with Julia and JuMP (1st Course)
04:00, 3. Short Survey on 3 aspects: student - Julia - JuMP
06:50, 4. Lecturing with Julia and JuMP (2nd Course)
07:48, 5. Short Survey on 3 aspects: student - Julia+MOA
09:18, 6. Conclusion

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
We can now close the issue.
