### ISSUE TITLE
Unapologetically Beyond Universality | Folkmar Bornemann | ASE60

### ISSUE THREAD

**Issue by ktzhao** [JuliaCommunity/YouTubeVideoTimestamps#261]
References:
Speaker: Folkmar Bornemann
Video title: Unapologetically Beyond Universality | Folkmar Bornemann | ASE60
Link: https://www.youtube.com/watch?v=ZnZw_RIy-20

Contents
00:06 0 Introduction
00:33 1 Unapologetically Beyond Universality
01:29 2 WHEN THE MAN COMES AROUND ...
03:00 3 universality in random matrix theory and beyond
04:45 4 why beyond universality?
06:07 5 determinantal expansions
07:30 6 numerical evaluation
09:07 7 extreme integrability
12:42 8 the case beta=2
15:46 9 reverse engineering shinault-tracy
18:19 10 integration, literally so
20:46 11 example
21:31 12 linear form structure of the u_jk-minors
22:48 13 example
23:48 14 application: solution of Ulam's problem
26:01 15 about tricks
28:13 Q&A

**Comment by KZiemian** [comment]
I tweaked it a bit.

Contents
00:00, 0. Introduction
00:33, 1. Unapologetically Beyond Universality
01:29, 2. WHEN THE MAN COMES AROUND...
03:00, 3. Universality in random matrix theory and beyond
04:45, 4. Why beyond universality?
06:07, 5. Determinantal expansions
07:30, 6. Numerical evaluation
09:07, 7. Extreme integrability
12:42, 8. The case beta = 2
15:46, 9. Reverse engineering shinault-tracy
18:19, 10. Integration, literally so
20:46, 11. Example
21:31, 12. Linear form structure of the u_jk-minors
22:48, 13. Example
23:48, 14. Application: solution of Ulam's problem
26:01, 15. About tricks
28:13, Q&A

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
It seems that timestamps were correctly incorporated, so we are closing the issue.
