### ISSUE TITLE
State of Julia | Valentin Churavy, Jameson Nash, Tim Holy | JuliaCon 2023

### ISSUE THREAD

**Issue by SyxP** [JuliaCommunity/YouTubeVideoTimestamps#264]
References:
Speaker: Valentin Churavy, Jameson Nash, Tim Holy
Video title: State of Julia | Valentin Churavy, Jameson Nash, Tim Holy | JuliaCon 2023
Link: https://www.youtube.com/watch?v=jFhL8EVrz7s

Contents
0:00 Introduction

-- Highlights of Julia
1:32 Interactivity
3:42 Speed
4:39 Expressivity
5:51 Onboarding Newcomers

-- New Features
7:08 Overview and History
8:59 Latency and Load Times
14:32 Package Extensions
17:38 Independence of Stdlibs from base Julia
19:00 JuliaSyntax.jl
21:00 REPL Improvements
22:46 Other Language Highlights
23:34 Improved Debugging & Profiler tools
26:38 Stacktrace Rendering
28:00 Static Compilation 
35:05 GPU Ecosystem & Accelerated Computing
37:32 Threading
38:07 Garbage Collection 

39:00 Ecosystem Highlights
39:43 Parallel Efficiency (ImplicitGlobalGrid.jl)
40:19 Black Hole Imaging (w/ Julia & Enzyme.jl)

42:03 Start of Q&A
42:08 Qn on Precompilation (Time & Profiling)
43:03 Qn on next LTS
44:03 Qn on Documentation, Testing & Macro Hygiene
46:00 Qn on Independence of Stdlibs
46:50 Qn on Debugger usage difficulty
49:35 Comment on cormullion's Art

**Comment by KZiemian** [comment]
I allowed myself to make few channegs to what you did.

Contents
00:00 Introduction
01:32 1) Highlights of Julia. Interactivity
03:42 Speed
04:39 Expressivity
05:51 Onboarding newcomers
07:08 2) New features. Overview and history
08:59 Latency and load times
14:32 Package extensions
17:38 Independence of Stdlibs from base Julia
19:00 JuliaSyntax.jl
21:00 REPL improvements
22:46 Other language highlights
23:34 Improved debugging & profiler tools
26:38 Stacktrace rendering
28:00 Static compilation
35:05 GPU ecosystem & accelerated computing
37:32 Threading
38:07 Garbage collection
39:00 3) Ecosystem highlights
39:43 Parallel efficiency (ImplicitGlobalGrid.jl)
40:19 Black hole imaging (w/ Julia & Enzyme.jl)
42:03 4) Q&A: precompilation (time & profiling)
43:03 Q&A next LTS
44:03 Q&A: documentation, testing & macro hygiene
46:00 Q&A: independence of Stdlibs
46:50 Q&A: on debugger usage difficulty
49:35 Q&A: comment on cormullion's art

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close the issue, when we get access rights to this GitHub repository.
