### ISSUE TITLE
Parallelizing your data with Dagger and DTables | Julian Samaroo | JuliaCon 2023

### ISSUE THREAD

**Issue by Antoinemarteau** [JuliaCommunity/YouTubeVideoTimestamps#266]
Hi, here is a contribution, tell me if I should modify something :) 

References:
Speaker: Julian Samaroo
Video title: Parallelizing your data with Dagger and DTables | Julian Samaroo | JuliaCon 2023
Link: https://youtu.be/RXjjTQffen0?si=z_EGH89fNS3Oo-xr
Link to the code: https://github.com/jpsamaroo/JuliaCon2023Talks/tree/main/Data

Contents
0:00 Welcome
0:06 Introduction
0:27 What is Dagger.jl ?
2:10 What is DTables.jl
3:50 DTables: Out of core data
6:30 DTables: Data partitionning
11:20 Dagger: Lazy operations
12:52 DTables: Caveat with GC (CSV < Arrow)
14:07 DTables: Examples
17:43 DTables: Heterogeneous tables support
20:12 Dagger: Supported data formats
21:49 Dagger: Chunks and data on disk
22:40 Conclusion
23:13 Questions

**Comment by KZiemian** [comment]
I will try to help your issue move into reality.

**Comment by KZiemian** [comment]
I made few changes to make your work more copy-pastable.

Contents
00:00 Welcome
00:06 Introduction
00:27 What is Dagger.jl?
02:10 What is DTables.jl
03:50 DTables: Out of core data
06:30 DTables: Data partitionning
11:20 Dagger: Lazy operations
12:52 DTables: Caveat with GC (CSV < Arrow)
14:07 DTables: Examples
17:43 DTables: Heterogeneous tables support
20:12 Dagger: Supported data formats
21:49 Dagger: Chunks and data on disk
22:40 Conclusion
23:13 Questions

Resources
Code from the talk, [link](https://github.com/jpsamaroo/JuliaCon2023Talks/tree/main/Data).

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
Since everything looks fine, we are closing the issue.
