### ISSUE TITLE
HPC Tools for Julia: Inspecting, Monitoring, and Tuning Performance | Carsten Bauer | JuliaCon 2023

### ISSUE THREAD

**Issue by Antoinemarteau** [JuliaCommunity/YouTubeVideoTimestamps#267]
Hi, here is another contribution, tell me if I should modify something :) 

References:
Speaker: Carsten Bauer
Video title: HPC Tools for Julia: Inspecting, Monitoring, and Tuning Performance | Carsten Bauer | JuliaCon 2023
Link: https://www.youtube.com/watch?v=ksh-CNM2YJU&t=7s

Contents
0:00 Welcome
0:06 Introduction
0:32 HPC tools and Julia
2:10 LIKWID - hardware performances monitoring
3:57 LIKWID - alternatives: LinuxPerf.jl and PAPI.jl
4:22 ThreadPinning - pin Julia threads
6:20 ScoreP - MPI profiling and tracing
8:44 ScoreP - alternative: NVTX.jl
9:11 ScoreP - open trace formats
10:37 MPITape - MPI call visualization
12:10 Outlook and conclusion
12:42 Questions

Edit: fixed the link

**Comment by KZiemian** [comment]
I made few minor changes to your work.

Contents
00:00 Opening and introduction
00:32 HPC tools and Julia
02:10 LIKWID - hardware performances monitoring
03:57 LIKWID - alternatives: LinuxPerf.jl and PAPI.jl
04:22 ThreadPinning - pin Julia threads
06:20 ScoreP - MPI profiling and tracing
08:44 ScoreP - alternative: NVTX.jl
09:11 ScoreP - open trace formats
10:37 MPITape - MPI call visualization
12:10 Outlook and conclusion
12:42 Questions

**Comment by KZiemian** [comment]
Everything seems to be ok, so we are closing the issue.
