### ISSUE TITLE
Fast Fourier Transforms in Julia (Steve Johnson)

### ISSUE THREAD

**Issue by chloemhall** [JuliaCommunity/YouTubeVideoTimestamps#269]
link: https://www.youtube.com/watch?v=1iBLaHGL1AM

00:00 : Introduction
01:25 : Background
03:39 : Example syntax
04:32 : Use of ! in place function
07:38 : sin / cos transformations
10:14 : Matlab dct vs Julia
10:49 : Questions- NLopt

**Comment by KZiemian** [comment]
I tweaked a bit your work.

Contents
00:00 Introduction
01:25 Background
03:39 Example of syntax
04:32 Use of ! in place function
07:38 sin / cos transformations
10:14 MATLAB dct vs Julia
10:49 Q&A: NLopt

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close the issue, when we get access rights to this GitHub repository.
