### ISSUE TITLE
Automatic Differentiation and SciML: What Can Go Wrong | Chris Rackauckas

### ISSUE THREAD

**Issue by agchesebro** [JuliaCommunity/YouTubeVideoTimestamps#276]
[Automatic Differentiation and SciML: What Can Go Wrong](https://www.youtube.com/watch?v=OyFP565kDUI) | Chris Rackauckas

00:00:00 Welcome
00:00:45 Content outline
00:01:50 Prologue: Why do differentiable simulation?
00:02:32 Universal Approximation Theorem
00:06:00 UODE example 1 – infection model
00:15:50 Why neural networks vs other universal approximators
00:20:36 UODE example 2 – learning binary black hole dynamics from LIGO data
00:22:50 UODE example 3 – diffusion-advection process in a chemical reactor system
00:28:40 Scientific machine learning digital twins
00:32:46 Does scientific machine learning require differentiation of the simulator?
00:33:03 UODE example 4 – ocean columns for climate models
00:39:16 Integral control to prevent solution drift
00:41:20 Differentiation of solvers and automatic differentiation
00:55:40 Three steps to summarize the solution process
01:02:16 Why adjoints by reversing is unconditionally unstable 
01:08:30 What is automatic differentiation and how does it help?
01:09:02 Worked example of automatic differentiation (available on Discourse: [https://discourse.julialang.org/t/does-zygote-differentiate-symbolically/96528/21](https://discourse.julialang.org/t/does-zygote-differentiate-symbolically/96528/21))
01:12:32 Dual numbers and automatic differentiation
01:20:58 What does automatic differentiation of an ODE solver give you?
01:31:40 When automatic differentiation gives numerically incorrect answers
01:35:42 Benefits of adaptivity
01:48:14 Other cases where automatic differentiation can fail (e.g., chaotic systems)
01:57:33 SciML common interface for Julia equation solvers
02:02:50 Returning to binary black hole dynamics as a worked example of successful SciML
02:08:11 Methods to improve the fitting process and pitfalls of single shooting
02:15:45 Multiple shooting and collocation
02:24:17 Neural network architectures in ODEs
02:35:11 Other methods that ignore derivative issues and future directions
02:45:23 Reservoir computing
02:47:52 Final comments and questions

**Comment by KZiemian** [comment]
Thak you and I apologize for not putting your timestamps earlier on YT.
