### ISSUE TITLE
The Special Math of Translating Theory to Software in Differential Eqs | Chris Rackauckas

### ISSUE THREAD

**Issue by agchesebro** [JuliaCommunity/YouTubeVideoTimestamps#277]
[The Special Math of Translating Theory to Software in Differential Eqs](https://www.youtube.com/watch?v=s_t6dIKjUUc) | Chris Rackauckas

00:00 Welcome and introduction
01:40 First problem: Small ODEs in pharmacometrics
02:49 Euler’s method and Runge-Kutta methods
07:28 Why not just use arbitrarily high order methods?
11:06 Dormand-Prince as default solver (e.g., ode45)
13:59 Can we drop the Dormand-Prince simplifying assumption?
14:56 Yes – this is why Julia defaults to Tsit5
16:35 Origins of Vern solvers
22:08 Building in adaptivity for solvers
25:20 Going beyond explicit Runge-Kutta methods
26:14 When to choose a non-BDF approach for stiff ODE solvers
29:54 Final comments and questions

**Comment by KZiemian** [comment]
Thank you, I added your timestamps.
