### ISSUE TITLE
So You Think You Know How to Take Derivatives? | Steven Johnson

### ISSUE THREAD

**Issue by agchesebro** [JuliaCommunity/YouTubeVideoTimestamps#278]
[So You Think You Know How to Take Derivatives?](https://www.youtube.com/watch?v=-l7JHalBubw) | Steven Johnson

00:00 Welcome and introduction
02:15 Derivatives: the “easy” part of calculus?
06:41 Why matrix calculus matters
11:24 Automatic differentiation: from calculus to compilers
14:44 Derivatives as linearization
19:20 Gradients as linear operators
24:41 The chain rule and forward vs reverse mode
27:49 “Adjoint method” for engineering optimization
29:05 Final comments and questions

**Comment by KZiemian** [comment]
Thank you. Your timestamps are now on the YT.
