### ISSUE TITLE
Inverses and Newton method | MIT Computational Thinking Spring 2021 | Lecture 5

### ISSUE THREAD

**Issue by vnegi10** [JuliaCommunity/YouTubeVideoTimestamps#34]

**Comment by vnegi10** [comment]
@logankilpatrick 

Contents

0:00 - Introduction/Announcements
1:25 - Non-linear maps continued
3:09 - Invite to interact on Discord
4:26 - Another example of perspective projection
5:16 - Definition of a linear transformation
7:12 - Linearity relation is simply matrix times vector
7:58 - What is a matrix multiplication?
10:08 - Visual representation of how it works
11:20 - Coordinate transformations vs object transformations
12:40 - Julia: Images are arrays
13:06 - Julia: Probing a pixel
13:44 - Linking image coordinates (i,j) to spatial coordinates (x,y) 
15:25 - Transforming image of a Corgi
17:35 - Function to transform xy to ij
18:30 - Creating reusable functions
21:00 - Inverse functions
22:05 - Trying different scaling 
23:20 - What does inverse really do?
24:42 - Inverting non-linear transformations
27:40 - Bringing it all together
30:00 - Collisions
31:20 - Why are we doing this backwards?
33:00 - David takes over for the next part - Motivation
33:52 - What does it mean by calculating an inverse?
34:38 - Newton's method in 1D
35:50 - How does it work? - Interactive visualization using Plots.jl
38:55 - Trying the same with a new function
39:40 - What happens if we start from a different initial value?
40:40 - Newton's method is not good if your starting value is too far from the root
40:48 - Julia: Using Symbolics.jl
41:10 - Julia: Using ForwardDiff
42:52 - Perturbation to a non-linear function
45:13 - Looking back at the interactive visualization for Newton's method
45:44 - Writing the mathematical expressions behind the visualization
46:25 - Expanding via the definition of a derivative
47:35 - Obtaining a generic expression for the solution
47:49 - Julia: Implementing Newton's method in 1D
48:12 - Julia: For loop, x -= a is the same as x = x - a
49:53 - Derivatives in 2D
51:10 - Newton's method in 2D
52:36 - Changing to non-linear transformation
55:45 - Julia: Implementing Newton's method in 2D
56:00 - Julia: Use of the "\" operator
57:10 - Concluding remarks

**Comment by logankilpatrick** [comment]
Thank you! Done
