### ISSUE TITLE
Managing Packages | Intro to Julia (for Programmers) | on Julia Academy | with Logan Kilpatrick

### ISSUE THREAD

**Issue by vnegi10** [JuliaCommunity/YouTubeVideoTimestamps#35]
@logankilpatrick 

https://www.youtube.com/watch?v=KldNhe4kvuk

Contents

0:00 - Welcome
0:45 - Looking for packages
1:20 - About JuliaHub
2:18 - How to use packages?
3:00 - using Pkg, Pkg.add("Example")
3:20 - Check if the package is available for use
3:40 - What does it mean to make use of a Julia package?
4:34 - Looking at the src of Example.jl
5:14 - Commands to use packages are added to the top of a file
5:32 - Adding packages via the REPL
6:03 - Entering the Pkg prompt
6:29 - Check status (list all packages available for use in the current project environment)
7:05 - Check for help
7:30 - Add Colors.jl 
7:38 - Add Example.jl
8:18 - How to get out of the Pkg prompt?
8:40 - List of commands available in the Pkg manager
9:20 - Remove Example.jl
9:45 - Closing remarks

**Comment by logankilpatrick** [comment]
Wonderful! Thank you
