### ISSUE TITLE
Modeling climate change | MIT Computational Thinking Spring 2021 | Lecture 25

### ISSUE THREAD

**Issue by ntmt2903** [JuliaCommunity/YouTubeVideoTimestamps#36]
Video Link: [Lecture 25](https://youtu.be/nm86_hDwYTU) 
Pluto notebook: [Notebook](https://computationalthinking.mit.edu/Spring21/inverse_climate_model/)
MARGO's Github: [Source code](https://github.com/ClimateMARGO/ClimateMARGO.jl/blob/main/src/Optimization/deterministic_optimization.jl)

Timestamps: 
0:00 - Pleasantry exchange
0:41 - Introduction to MARGO
1:24 - Henri on the motivation behind MARGO
3:00 - How to interact with the climate model 
5:16 - Emission mitigation and carbon dioxide removal to minimize climate suffering
9:30 - Mitigation, Removal, Geo-engineering
9:50 - Adaptation: Henri explaining the equations 
17:20 - Mitigating emissions
20:15 - Cost & damages 
22:30 - Henri on net cost & net benefit
24:20 - Picking up the slack carbon dioxide removal 
26:22 - Alan on climate model incorporating economic variables
27:10 - David on Solving inverse problems 
28:40 - Modeling with JuMP
33:05 - Example of JuMP (Unconstrained optimization)
43:20 - Constrained optimization 
47:55 - MARGO source code with JuMP
51:15 - MARGO's automated optimization 
54:20 - Henri on how optimal policy depends on the model's assumptions
56:45 - Wrap up (advice for interested CS students)

**Comment by ntmt2903** [comment]
@logankilpatrick is this the right amount of details?

**Comment by logankilpatrick** [comment]
Yes! This is great. You could even do with slightly less detail

**Comment by logankilpatrick** [comment]
Added the timestamps, thank you again!
