### ISSUE TITLE
DataFrames.jl 1.0 tutorial | Workshop | JuliaCon 2021

### ISSUE THREAD

**Issue by tp2750** [JuliaCommunity/YouTubeVideoTimestamps#37]
[Video link](https://www.youtube.com/watch?v=tJf24gfcSto)
[Github repository](https://github.com/bkamins/JuliaCon2021-DataFrames-Tutorial)
[Q&A](https://pigeonhole.at/DATAFRAME)

01:40 First round of questions https://pigeonhole.at/DATAFRAME
11:00 Clone the repository
15:30 More questions
21:30 Pkg.instantiate()
23:00 Start notebook
23:50 Questions
28:25 Statistical prerequisites (start of notebook)
29:45 Load packages
32:30 More questions
47:50 Resume tutorial (cell 5)
50.10 CSV.read (cell 6)
58:40 Transformation mini language (cell 7)
1:10:00 Questions
1:37:25 Break
1:40:50 Resume questions
2:00:20 Resume tutorial ("Exploratory data analysis" / cell 10)
2:11:30 Building a predictive model
2:20:20 Break
2:22:30 Questions
2:30:00 Advanced DataFrames.jl functionalities: bootstrapping example (cell 32)
2:44:20 plot with error bars (cell 44)
2:46:40 Redo using Bootstrap.jl (cell 45)
2:49:45 Unnesting (cell 50)
2:50:40 Reordering columns (cell 51)
2:52:10 Sorting on custom function (cell 53)
2:54:20 Questions
3:03:00 Summary

**Comment by tp2750** [comment]
@logankilpatrick is this useful?

**Comment by logankilpatrick** [comment]
Yes! 100% useful, just added this

**Comment by logankilpatrick** [comment]
Thank you!
