### ISSUE TITLE
Package development: improving engineering quality & latency

### ISSUE THREAD

**Issue by timholy** [JuliaCommunity/YouTubeVideoTimestamps#38]
- 0:20 : Julia internals: compiler specialization, dispatch, backedges, invalidation, precompilation
- 31:50 : catching errors and inference failures with JET
- 1:24:03 : visualizing the costs of compilation and generating precompile directives with SnoopCompile
- 1:56:08 : tutorial on reading lowered and typed code
- 2:14:37 : tutorial on using Cthulhu
- 2:47:06 : catching and fixing inference failures with SnoopCompile & Cthulhu integration

CC @aviatesk

**Comment by aviatesk** [comment]
Looks great, thanks Tim.

**Comment by timholy** [comment]
Added by @dpsanders :heart:

**Comment by aviatesk** [comment]
Thanks so much, @dpsanders !
