### ISSUE TITLE
hPF-MD.jl: Hybrid Particle-Field Molecular-Dynamics Simulation

### ISSUE THREAD

**Issue by caprilesport** [JuliaCommunity/YouTubeVideoTimestamps#39]
Video link: [link](https://www.youtube.com/watch?v=nclG1k6GAiA)
Github repo: [Repo](https://github.com/Chenghao-Wu/hPF-MD.jl)

Timestamps:
* 0:36 : Background and Motivation
* 2:24 : Theory and Method
* 3:58 : Hybrid Particle-Field Method
* 5:56 : hPF-MD.jl Motivation
* 7:24 : hPF-MD.jl Example
* 8:30 : Conclusion and Future Works

**Comment by caprilesport** [comment]
@logankilpatrick Hope it's useful

**Comment by logankilpatrick** [comment]
Yes, thank you!!!
