### ISSUE TITLE
Dictionaries.jl - for improved productivity and performance 

### ISSUE THREAD

**Issue by Sov-trotter** [JuliaCommunity/YouTubeVideoTimestamps#41]
Video Link : [link](https://www.youtube.com/watch?v=Y-hAZcqAw28)
Github : [repo](https://github.com/andyferris/Dictionaries.jl)

00:10 : Outline
00:30 : What is Dictionaries.jl
01:02 : Why Dictionaries.jl
05:08 : Implementation
13:47 : Performance
16:52 : The Interface
18:56 : Usage 
19:01 : Basic Usage in REPL
23:46 : Grouping and Aggregation in REPL
25:14 : Table operations - TypedTables.jl
27:01 : Conclusion

@logankilpatrick

**Comment by logankilpatrick** [comment]
Added, thank you!
