### ISSUE TITLE
Changing Physics education with Julia | George Datseris | JuliaCon2021

### ISSUE THREAD

**Issue by cmdenis** [JuliaCommunity/YouTubeVideoTimestamps#42]
Video Link : [https://youtu.be/04HAQXl5aj4](https://youtu.be/04HAQXl5aj4)

00:40 : I Have A Dream...
02:11 : Putting Things Into Perspective
04:23 : How It Works
05:16 : Actual Pages
05:38 : Benefits Of Showing _Real_ Code
07:56 : Delay Coordinates Embedding
10:49 : Code ↔️ Figure
13:41 : Interactive Applications
16:14 : Makie.jl = 2 stronk 2 be true
17:13 : Exercises Like In Practice
19:39 : Careful: Don't Abuse Pre-Made Libraries
21:59 : Online Repository
22:25 : Live Polling During The Lecture
23:48 : DynamicalSystems.jl 2.0
24:12 : Summary

@logankilpatrick

**Comment by Datseris** [comment]
Oh I was just about to do this, thank you very much @cmdenis I appreciate it!

**Comment by logankilpatrick** [comment]
Thank you both!
