### ISSUE TITLE
Building on AlphaZero with Julia

### ISSUE THREAD

**Issue by filchristou** [JuliaCommunity/YouTubeVideoTimestamps#43]
video link : https://www.youtube.com/watch?v=nbLmR0aDumo
repo : https://github.com/jonathan-laurent/AlphaZero.jl

Timestamps:
00:00 => Welcome    
00:10 => Introduction    
00:43 => DeepMind short history moments    
02:15 => Outline    
03:00 => An Introduction to AlphaZero    
04:55 => Monte-Carlo Tree Search    
06:11 => MCTS in Action    
07:46 => UCT Formula    
10:18 => After 600 simulations     
11:00 => MCTS as a policy improvement operator     
11:50 => How to apply MCTS?    
12:56 => AlphaZero beyond board games    
13:40 => AlphaZero for automated theorem proving     
17:56 => AlphaZero.jl and execution speed    
19:27 => AlphaZero.jl parallelism                    
20:48 => Composable parallelism            
21:34 => There is room for performance improvement    
22:59 => AlphaZero.jl online documentation    
23:42 => Conclusion  

@logankilpatrick

**Comment by logankilpatrick** [comment]
Thank you a ton! just a small piece of feedback, we don't need the angled brackets, just the timestamp and the words
