### ISSUE TITLE
Agents.jl and the next chapter in agent based modelling | Tim DuBois | JuliaCon2021

### ISSUE THREAD

**Issue by Hasnep** [JuliaCommunity/YouTubeVideoTimestamps#45]
0:08 Introduction to agent based modelling
3:02 Philosophy of Agents.jl
3:27 Agents.jl is Simple
8:15 Agents.jl is Performant
14:55 Agents.jl is Interactive
17:22 Agents.jl is Integrated
21:11 Looking forward

**Comment by logankilpatrick** [comment]
Sweet, thank you again!
