### ISSUE TITLE
An individual-based model to simulate Coffee Leaf Rust epidemics | Manuela Vanegas F | JuliaCon2021

### ISSUE THREAD

**Issue by Hasnep** [JuliaCommunity/YouTubeVideoTimestamps#46]
0:20 Introduction to Coffee Leaf Rust
2:50 The SpatialRust model
4:12 Model implementation
5:23 Examples
5:52 Preliminary Results
6:49 Pending work

**Comment by logankilpatrick** [comment]
Great, thank you!
