### ISSUE TITLE
Solving optimization problems at Fonterra | Oleg Barbin | JuliaCon2021

### ISSUE THREAD

**Issue by dominiqueplante** [JuliaCommunity/YouTubeVideoTimestamps#47]
0:29 Agenda
0:45 Problem Background
2:12 Organic Milk Planning Process
3:17 Opportunities & Benefits
3:40 Solution Approach
3:54 Proposed Solution - A Julia application
4:25 Why Mixed Integer?
5:18 Benefits of JuMP
5:51 JuMP models are easy to work with
6:43 Active JuMP development

**Comment by logankilpatrick** [comment]
Done, thanks!
