### ISSUE TITLE
Tomographic Image Reconstruction with Julia | Tobias Knopp | JuliaCon2021

### ISSUE THREAD

**Issue by nHackel** [JuliaCommunity/YouTubeVideoTimestamps#48]
00:20 What is Tomography
01:48 Principle of Tomography explained with Computed Tomography (CT)
02:55 Popular Imaging Modalities
03:35 Imaging Equation
04:20 Image Reconstruction 
07:14 State of the Art
08:46 Hybrid Image Reconstruction Platforms
10:27 Design Goals for Julia Package Family
12:45 Reused Existing Julia Packages
14:01 Newly Developed Shared Packages
16:10 Overview of Julia Imaging Packages
16:39 MPIReco.jl: Overview
17:45 MPIReco.jl: Example
18:24 MPIReco.jl: Performance and Accuracy
19:38 Magnetic Particle Imaging (MPI)
20:08 MPIReco.jl: Interface
20:48 Commercial MPI Imager and Online Reconstruction
21:36 Online Reconstruction Example Video
22:03 Dynamic Image Reconstruction in MPI
23:55 Graphical User Interfaces
24:31 GUI Example Video
25:39 Summary and Outlook

**Comment by nHackel** [comment]
[Video link](https://www.youtube.com/watch?v=cDZq_vr10CQ) and link to packages being presented [MRIReco.jl](https://github.com/MagneticResonanceImaging/MRIReco.jl) and [MPIReco.jl](https://github.com/MagneticParticleImaging/MPIReco.jl)

@logankilpatrick

**Comment by logankilpatrick** [comment]
Done! this looks great
