### ISSUE TITLE
GPU programming in Julia | Workshop | JuliaCon 2021

### ISSUE THREAD

**Issue by ignace-computing** [JuliaCommunity/YouTubeVideoTimestamps#49]

**Comment by ignace-computing** [comment]
Status update: first 35 minutes done. 
Left here: https://youtu.be/Hz9IMJuW5hU?t=2135
Will try to continue the work!

00:24 	Welcome
01:20 	Outline
02:44	JuliaGPU packages
04:08:	JuliaGPU back-ends
05:34	GPU Architecture
07:25	Parallel programming models
08:55	Follow along and links to notebooks, JuliaHub
12:37	Start of tuturial with notebook
16:00 		Array programming
28:20		Kernel programming
34:32		Parallel programming

Materials
https://github.com/maleadt/juliacon21-gpu_workshop

**Comment by logankilpatrick** [comment]
Wonderful! Please @ me when they are done

**Comment by logankilpatrick** [comment]
bumping this @ignace-computing

**Comment by ignace-computing** [comment]
Thank you for the reminder. Will try to finish this, at the latest this week.

**Comment by ignace-computing** [comment]
Hi @logankilpatrick, it is finally finished! Sorry for keeping you waiting a bit long :).
I updated the timestamps above, and removed one typo in the timestamps that were already there.

**Comment by logankilpatrick** [comment]
Thank YOU!
