### ISSUE TITLE
🎈 Pluto.jl — one year later | Fons van der Plas | JuliaCon2021

### ISSUE THREAD

**Issue by fonsp** [JuliaCommunity/YouTubeVideoTimestamps#50]
https://www.youtube.com/watch?v=HiI4jgDyDhY

00:00 Welcome!
00:10 Introduction
00:57 Disable cells (new feature)
03:34 Package manager (new feature)
07:53 Exporting notebooks (new feature)
11:52 Macro support (new feature)
13:55 JavaScript framework
16:28 Future ideas
19:30 Future experiments
23:09 Future prototypes
25:46 Closing remarks

**Comment by logankilpatrick** [comment]
Done! Can't wait to watch this talk
