### ISSUE TITLE
Bias Audit and Mitigation in Julia | Ashrya Agrawal | JuliaCon2021

### ISSUE THREAD

**Issue by ashryaagr** [JuliaCommunity/YouTubeVideoTimestamps#51]
Slides: https://www.ashrya.in/juliacon
Repo: https://github.com/ashryaagr/Fairness.jl

00:00 => Welcome
00:08 => Introduction
00:21 => Introduction to the problem of Fairness
01:12 => Sources of bias
02:12 => Complexity of the fairness problem
04:16 => Fairness.jl package
05:24 => Fairness.jl workflow
07:08 => Fairness pipeline, 
07:17 => Our research
07:34 => Julia ecosystem
08:13 => Outlook

@logankilpatrick

**Comment by ashryaagr** [comment]
Youtube link: **https://www.youtube.com/watch?v=Ij0exPwmT2w** (starts in 26 mins)

**Comment by logankilpatrick** [comment]
Done! Thank you
