### ISSUE TITLE
Code, docs, and tests: what’s in the General registry? Mosè Giordano, Eric P Hanson | JuliaCon2021

### ISSUE THREAD

**Issue by tylerjthomas9** [JuliaCommunity/YouTubeVideoTimestamps#52]
YouTube Link: https://youtu.be/9YWwiFbaRx8

GitHub: https://github.com/JuliaEcosystem/PackageAnalyzer.jl

00:08 Welcome
01:32 Lines of code
03:53 Licenses
05:38 Documentation
09:05 Testing
13:17 Continuous Integration 
15:05 Contributor count
19:33 Package templates
 20:05 PackageAnalyzer.jl 
22:45 Conclusion

**Comment by tylerjthomas9** [comment]
@logankilpatrick

**Comment by logankilpatrick** [comment]
Done, thank you!!
