### ISSUE TITLE
Keynote: William Kahan - Debugging Tools for Floating-Point Code

### ISSUE THREAD

**Issue by Sov-trotter** [JuliaCommunity/YouTubeVideoTimestamps#53]
Will keep updating here! :)

Video Link : [link](https://www.youtube.com/watch?v=qHddEkfQBrA)

00:00 Prof. Alan Edelman introducing Prof. William Kahan
00:24 History of IEEE Floating Point Standard
00:19 How does a Floating-Point Program differ from others
3:55 Common misconception regarding floating-point
5:32 Problem 1 - Accuracy isn't Transitive
8:24 Problem 2 - Roundoff

**Comment by logankilpatrick** [comment]
awesome! Thank you.

**Comment by logankilpatrick** [comment]
@Sov-trotter bumping this

**Comment by Sov-trotter** [comment]
Yeah sorry for leaving this mid way. WIll try to get it done before the weekend.

**Comment by logankilpatrick** [comment]
Closing for now but feel free to re-open if you get around to this, no pressure!

**Comment by KZiemian** [comment]
I will try to finish timestamps for this video.
