### ISSUE TITLE
Designing Spacecraft Trajectories with Julia | Dan Padilha | JuliaCon2021

### ISSUE THREAD

**Issue by dpad** [JuliaCommunity/YouTubeVideoTimestamps#54]
Video link: https://www.youtube.com/watch?v=iJr_lU7_7Go
Github repo: https://github.com/dpad/OrbitalTrajectories.jl

Timestamps:

0:10 : Speaker's introduction
0:23 : What do astrodynamicists do?
1:20 : Why Julia?
2:13 : Simulating spacecraft motion
3:34 : Composing functionality
4:32 : The nitty-gritty details
5:18 : Simulation performance
5:45 : Differentiation for State Transition Matrices (STMs)
6:49 : Generating quasi-periodic orbits
7:26 : Summary
9:09 : Reference & Acknowledgements

Pinging @logankilpatrick for review -- I pretty much just went by slide titles, hope that's okay! (Oh, and thanks for all your work!)

**Comment by logankilpatrick** [comment]
Added! Thank you
