### ISSUE TITLE
Solving Pokemon Go Battles using Julia | Ian Slagle | JuliaCon2021

### ISSUE THREAD

**Issue by cmdenis** [JuliaCommunity/YouTubeVideoTimestamps#55]
Video Link : https://youtu.be/6PB1aIl9_6k

00:22 : Motivation
00:40 : Pokémon Go Mechanics
01:35 : Structure Packing
02:32 : Monte Carlo Simulations
03:25 : Nash Simulations
03:51 : MC vs Nash
04:32 : UMAP
05:09 : MCTS Battle
05:57 : Conclusions
06:30 : Credits, Bibliography, Acknowledgments

@logankilpatrick

**Comment by logankilpatrick** [comment]
Done, thanks!
