### ISSUE TITLE
JuliaCon 2021: Julia in VS Code - What's New

### ISSUE THREAD

**Issue by waldyrious** [JuliaCommunity/YouTubeVideoTimestamps#56]
Video link: https://www.youtube.com/watch?v=kl3ySM4o-dw

00:07 Introduction
01:10 Message from Microsoft about Jupyter integration
02:04 Native notebook support for Jupyter notebooks
10:42 Plot gallery
13:32 Debugger speedup
15:53 Persistent connections to external REPLs
17:23 Progress logging
18:32 Create package releases from within VSCode
24:33 Conclusion

/cc @logankilpatrick

**Comment by logankilpatrick** [comment]
Ah this is a great video, thank you!
