### ISSUE TITLE
What's new in COSMO? | Michael Garstka | JuliaCon2021

### ISSUE THREAD

**Issue by migarstka** [JuliaCommunity/YouTubeVideoTimestamps#57]
Video Link: https://www.youtube.com/watch?v=O50kKay3Ie8&t=14s

Timestamps:
0:07 - Introduction
0:24 - Package overview
4:45 - Anderson acceleration
7:48 - Safeguarded acceleration - code example
11:12 - Acceleration - benchmarks
12:26 - Chordal decomposition and clique merging
16:09 - A clique graph-based merging strategy
17:29 - Clique merging - code example
21:06 - Clique merging - benchmarks
22:37 - Conclusions

Pinging @logankilpatrick for review. Thank you!

**Comment by logankilpatrick** [comment]
Thank you Michael!
