### ISSUE TITLE
JuliaCon 2021: Roadmap to Julia BLAS and LinearAlgebra

### ISSUE THREAD

**Issue by waldyrious** [JuliaCommunity/YouTubeVideoTimestamps#58]
Video link: https://www.youtube.com/watch?v=KQ8nvlURX4M

00:09 Introduction
01:00 Why?
03:03 Performance
11:16 Flexibility
15:14 Interoperability
18:43 Roadmap

/cc @logankilpatrick

**Comment by logankilpatrick** [comment]
Added! Thanks again.
