### ISSUE TITLE
Shaped Data with Acsets | Owen Lynch | JuliaCon2021

### ISSUE THREAD

**Issue by ajahraus** [JuliaCommunity/YouTubeVideoTimestamps#59]
Video Link: https://www.youtube.com/watch?v=ZzTJ3Hrw2w8

Contents
0:07 - Introduction
0:58 - Outline
1:41 - What are acsets?
3:38 - Graphs as Relational Databases
4:42 - Compose with Dataframes: Attributes
5:14 - Acset Schemas (A more formal definition)
6:50 - Acsets on a Schema
7:45 - Previous Example in a new Framework 
9:07 - Other data structures using acsets
13:22 - Code Demo
19:30 - The data structure of an acset
20:44 - Fast accessor and mutators 
22:18 - The Bright Future
23:33 - Semagram Code Demo

**Comment by ajahraus** [comment]
@logankilpatrick

**Comment by logankilpatrick** [comment]
Added! Thanks
