### ISSUE TITLE
New tools to solve PDEs in Julia with Gridap.jl | Francesc Verdugo et al | JuliaCon2021

### ISSUE THREAD

**Issue by cmdenis** [JuliaCommunity/YouTubeVideoTimestamps#60]
Video Link : https://youtu.be/hsQiFP4S5RY

00:25 : Some PDEs Solved With Gridap In 2021
00:39 : Outline
01:00 : New User API
01:50 : How Efficient Is Gridap?
02:52 : Simulating Complex Geometries In Gridap
05:10 : Simulating Real-World Applications In Gridap

@logankilpatrick

**Comment by logankilpatrick** [comment]
Done! thanks
