### ISSUE TITLE
Relational AI Sponsor Talk | JuliaCon 2021

### ISSUE THREAD

**Issue by tylerjthomas9** [JuliaCommunity/YouTubeVideoTimestamps#61]
Youtube link: https://www.youtube.com/watch?v=BTmmjTAwNgI

Title: Relational AI Sponsor Talk | JuliaCon 2021

Timestamps:
00:37 Introduction
01:45 Knowledge graphs
04:43 Example RelationalAI Workloads
05:39 Rel Introduction
06:30 Toy example with the Julia compiler
07:18 Rel Example
09:12 Julia metaprogramming
10:17 Conclusion

@logankilpatrick

**Comment by logankilpatrick** [comment]
Added! thanks again
