### ISSUE TITLE
Matlab to Julia: Hours to Minutes for MRI Image Analysis | Jonathan Doucette | JuliaCon2021

### ISSUE THREAD

**Issue by jondeuce** [JuliaCommunity/YouTubeVideoTimestamps#62]
Video link: https://www.youtube.com/watch?v=6OxsK2R5VkA

Title: Matlab to Julia: Hours to Minutes for MRI Image Analysis

Timestamps:
0:00 - Introduction
0:22 - Introduction and motivation
0:42 - MRI crash course
1:05 - Quantitative susceptibility mapping
1:38 - Success of Matlab in traditional MRI
2:01 - Struggles of Matlab in modern MRI
2:47 - Myelin water imaging
3:21 - Non-negative least squares problem
4:07 - Bottlenecks
4:50 - Switching to Julia: EPG algorithm
5:53 - Switching to Julia: NNLS solver
6:30 - Switching to Julia: parallelism
7:26 - Switching to Julia: 60X faster
7:35 - DECAES.jl
7:55 - Acknowledgements and contact information

@logankilpatrick these timestamps should be good to go!

**Comment by logankilpatrick** [comment]
Thank you!
