### ISSUE TITLE
Javis.jl - Julia Animations and Visualizations

### ISSUE THREAD

**Issue by Wikunia** [JuliaCommunity/YouTubeVideoTimestamps#63]
Video link: https://www.youtube.com/watch?v=FXqQc8bi_vw

Timestamps:
0:09 Loading Intro
0:33 Introduction
3:06 Technical: Intro
4:05 Technical: Manim
4:59 Technical: Processing
5:47 Technical: Javis
8:29 Notebooks: Example
11:29 Notebooks: Jupyter
13:09 Notebooks: Pluto
15:32 Use Cases: Liveviewer
16:52 Use Cases: Streaming
18:37 Teaching with Javis
19:18 Community Use
19:45 Case Study: Neuroinformatics
20:34 Next Steps
21:40 Get Involved
22:05 Acknowledgements
23:09 Attributions

@logankilpatrick

**Comment by logankilpatrick** [comment]
Added! Thank you

**Comment by Wikunia** [comment]
Oh no thanks @felixcremer seems like I messed something up.
Sorry @logankilpatrick and thanks for fixing it in advance.

**Comment by logankilpatrick** [comment]
Fixed!
