### ISSUE TITLE
JuliaCon 2021: The OSCAR Computer Algebra System

### ISSUE THREAD

**Issue by waldyrious** [JuliaCommunity/YouTubeVideoTimestamps#64]
Video link: https://www.youtube.com/watch?v=rWQK4mU3jQc

0:07 Introduction
0:34 What is OSCAR?
1:14 Who are we?
2:07 The structure of OSCAR
3:52 Features of OSCAR
5:05 Feature highlight: multivatiate polynomials
6:27 Oscar vs. Symbolics
7:29 Conclusion

**Comment by waldyrious** [comment]
@logankilpatrick are you watching this repository or should I tag you on every issue?

**Comment by logankilpatrick** [comment]
Feel free to keep tagging me or not since I am watching the repo. Thanks again for this, really helps!

**Comment by waldyrious** [comment]
I'm happy to help, it really pleases me when videos have timestamps. (Besides, noting down the chapters helps me retain the content after I watch the videos! :smile:)
