### ISSUE TITLE
JuliaCon 2021: Atomic fields: the new primitives on the block

### ISSUE THREAD

**Issue by waldyrious** [JuliaCommunity/YouTubeVideoTimestamps#65]
Video link: https://www.youtube.com/watch?v=2rBv6sV4Xts

0:47 Introduction
1:07 What is @atomic?
1:32 Not atomic: Single-threaded example
2:27 Not atomic: Broken example
3:31 @atomic: Fixed example
3:50 What @atomic does not do
5:03 Other atomic operators
9:53 Conclusion

**Comment by logankilpatrick** [comment]
I just edited the first 45 seconds of silence, can you modify these slightly?

**Comment by waldyrious** [comment]
Sure. I subtracted 47 seconds, but had to round some of the timestamps up or down because the transitions don't usually happen at the exact second marks.

0:00	Introduction
0:21	What is @atomic?
0:47	Not atomic: Single-threaded example
1:41	Not atomic: Broken example
2:44	@atomic: Fixed example
3:04	What @atomic does not do
4:18	Other atomic operators
9:06	Conclusion

**Comment by logankilpatrick** [comment]
Added! Thank you for updating this
