### ISSUE TITLE
JuliaCon 2021: Symbolics.jl - fast and flexible symbolic programming

### ISSUE THREAD

**Issue by waldyrious** [JuliaCommunity/YouTubeVideoTimestamps#66]
Video link: https://www.youtube.com/watch?v=Vkz4c-lDMU8

00:08 Introduction
00:21 Origin
00:48 Goals
01:23 Symbolics.jl tour
04:55 Expression trees
09:38 Rule-based rewriting
11:25 Symbolic Arrays
16:10 Symbolic Arrays: ArrayOp
23:33 Acknowledgements
23:50 More to see

**Comment by logankilpatrick** [comment]
Busy weekend! Appreciate the help here

**Comment by waldyrious** [comment]
> Busy weekend! Appreciate the help here

Gotta take advantage of the free time when it comes around; not a common occurrence these days :)
