### ISSUE TITLE
JuliaCon 2021: Diversity and Inclusion in the Julia community

### ISSUE THREAD

**Issue by waldyrious** [JuliaCommunity/YouTubeVideoTimestamps#67]
Video link: https://www.youtube.com/watch?v=xwpLArLkM-Y

0:08 Introduction
1:26 What we have done in the last year
4:23 Background info on Google Analytics 
4:47 JuliaLang Website 
5:55 Discourse 
6:10 The Docs 
6:28 Julia Academy 
6:52 YouTube
7:14 Takeaways & Next Steps

**Comment by logankilpatrick** [comment]
Done! Thank you again!
