### ISSUE TITLE
JuliaCon 2021: Unleashing Algebraic Metaprogramming in Julia with Metatheory.jl

### ISSUE THREAD

**Issue by waldyrious** [JuliaCommunity/YouTubeVideoTimestamps#68]
Video link: https://www.youtube.com/watch?v=tdXfsTliRJk

00:08 Introduction
01:18 What can we do with Metatheory.jl?
02:06 Equations are good
03:29 Classical rewriting
05:38 E-Graph
06:26 The path to the E-Graph
08:56 Why Julia?
09:31 A sketch of an E-Graph in Julia
10:21 Equality saturation
12:08 What is so cool about e-graphs?
14:05 Classical rewriting vs E-Graph rewriting
14:41 Symbolics.jl
17:03 Fibonacci with SymbolicUtils.jl vs Metatheory.jl
18:46 Category Theory
21:21 Going faster than Knuth-Bendix
22:35 Other Experiments
23:13 Future directions

**Comment by logankilpatrick** [comment]
Added! Thank you.
