### ISSUE TITLE
JuliaSim: Machine Learning Accelerated Modeling and Simulation | Chris Rackauckas | JuliaCon2021

### ISSUE THREAD

**Issue by rtyasdf** [JuliaCommunity/YouTubeVideoTimestamps#69]
Video link: https://www.youtube.com/watch?v=lNbU5jNp67s

00:07 Introduction
00:42 Industrial application of Julia
02:44 Fast Differential Equation Solvers
05:07 Speedup of symbolic computation
05:52 Integration with neural networks
06:45 Engineering a Community
09:48 SciML coverage
10:58 Missing pieces in SciML
15:29 JuliaSim introduction
17:32 Next generation of algorithms
18:27 Acceleration via surrogates
21:57 Composed surrogates
23:42 Training surrogates with JuliaHub
24:13 Pretrained models
25:39 GUI
26:30 Examples of JuliaSim integration
27:27 JuliaSim Roadmap
28:26 Try JuliaSim

**Comment by logankilpatrick** [comment]
Added, thank you!
