### ISSUE TITLE
Hierarchical Multiple Instance Learning | Tomas Pevny | JuliaCon 2021

### ISSUE THREAD

**Issue by SimonMandlik** [JuliaCommunity/YouTubeVideoTimestamps#70]
Video link: https://www.youtube.com/watch?v=Bf0CvltIDbE

0:08 Introduction and Motivation
1:07 Possible solutions to the deviceID problem
2:52 HMIL approach
6:32 Comparison to SOTA
7:20 Theoretical guarantees
8:29 Mill.jl: node types
9:11 Mill.jl: representing leafs
10:58 Mill.jl: representing dicts
11:59 Mill.jl: representing arrays
13:19 Mill.jl: working with the whole sample
14:26 Mill.jl: training a model with JsonGrinder.jl and Flux.jl
19:58 Summary

**Comment by logankilpatrick** [comment]
Woohoo, added!
