### ISSUE TITLE
Julia for Biologists | Elisabeth Roesch | JuliaCon2021

### ISSUE THREAD

**Issue by SosUts** [JuliaCommunity/YouTubeVideoTimestamps#71]
Video Link : https://www.youtube.com/watch?v=gRj7E5kYG1I

00:48 : Further resources and contact details
01:25 : Contents
02:00 : Introduction: Tools of a biologist
06:57 : Julia enables new biology
09:23 : Speed Ex. 1 - Single cell data and network inference
13:24 : Speed Ex. 2 - Pharmacology and dynamical systems
17:24 : What is abstraction in context of programming language?
18:35 : What is abstraction in Julia?
19:17 : Why should biologists care about abstraction?
20:15 : Abstraction Ex. 1 - Structural Bioinformatics and code reuse
23:19 : Abstraction Ex. 2 - Image processing
23:19 : Metaprogramming
28:11 : Metaprogramming Ex.1 - Biochemical reaction networks
29:00 : Metaprogramming Ex.2 - Whole cell modeling
29:59 : Summary
32:47 : The package ecosystem in Julia for biologists
33:40 : More reasons why to use Julia
35:05 : Acknowledgements
35:40 : Tips from the community

@logankilpatrick

**Comment by logankilpatrick** [comment]
Done! Thank you
