### ISSUE TITLE
Adaptive and extendable simulations with Trixi.jl | M Schlottke-Lakemper, H Ranocha | JuliaCon2021

### ISSUE THREAD

**Issue by sloede** [JuliaCommunity/YouTubeVideoTimestamps#72]
YouTube: https://www.youtube.com/watch?v=hoViWRAhCBE
Talk repo: https://github.com/trixi-framework/talk-2021-juliacon
Package repo: https://github.com/trixi-framework/Trixi.jl

00:08 Welcome
00:46 Motivation and goals for Trixi.jl
03:32 Current state and simulation examples
05:47 Live demo: Introduction
06:36 Live demo: Creating a Trixi simulation from scratch
09:49 Live demo: Using a different initial condition
10:46 Live demo: Adaptive mesh refinement
12:22 Live demo: Advanced usage
14:08 Evaluating Julia for simulation science
14:15 Performance
17:36 Ease of use
18:03 Binary dependencies
19:04 Reproducibility
19:38 Extendability
22:44 Conclusions and outlook

**Comment by logankilpatrick** [comment]
Added, thank you!

**Comment by sloede** [comment]
@logankilpatrick Thanks for adding the time stamps. However, it seems like the first item was gobbled and instead the original call for time stamps is still present:
![image](https://user-images.githubusercontent.com/3637659/128869127-bbc81354-be98-4a68-a472-14be53865c76.png)

I think the first two items should be replaced by
```
00:08 Welcome
```

**Comment by logankilpatrick** [comment]
Fixed! The timestamps have to start from 00:00 so left the welcome message at the beginning

**Comment by sloede** [comment]
Thanks! LGTM now!
