### ISSUE TITLE
Enabling Rapid Microservice Development with a Julia SDK | Malcolm Miller | JuliaCon2021

### ISSUE THREAD

**Issue by mmiller-max** [JuliaCommunity/YouTubeVideoTimestamps#73]
Think that's completed in the comment below, video is [here](https://www.youtube.com/watch?v=KixO3udfcKA).

**Comment by mmiller-max** [comment]
0:18 - Talk overview
0:56 - The challenges of developing microservices
3:57 - Our situation at Deloitte and why we created an SDK
4:36 - SDK Overview
5:09 - Hosting the SDK
5:56 - Microservice template package
11:21 - Utility packages
11:37 - Utility packages for common functionality across microservices
14:33 - Utility packages to create consistent interfaces
18:23 - GraphQL Interface, an example utility package
21:10 - Pros and Cons of using an SDK

**Comment by logankilpatrick** [comment]
Added, thank you!
