### ISSUE TITLE
A deep dive into MakieLayout | Julius Krumbiegel | JuliaCon2021

### ISSUE THREAD

**Issue by tp2750** [JuliaCommunity/YouTubeVideoTimestamps#75]
Video link: https://www.youtube.com/watch?v=AtqXFfaMZqo

00:00 Welcome
00:51 Building a Figure
03:56 GridLayout protrusions
05:23 Nested protrusions
06:56 Manual bounding boxes
07:58 GridLayout and Figure Decoupling
10:40 Multiple objects in the same GridLayout cell
12:23 Tellwidth and tellheight
14:33 Mixed align mode
17:22 Placing objects in protrusions
20:03 Nesting sublayouts into figure positions
23:14 Closing remarks

**Comment by logankilpatrick** [comment]
Added, thank you!
