### ISSUE TITLE
Infinite-Dimensional Optimization with InfiniteOpt.jl | Joshua Pulsipher | JuliaCon2021

### ISSUE THREAD

**Issue by pulsipher** [JuliaCommunity/YouTubeVideoTimestamps#76]
Link to video: https://www.youtube.com/watch?v=z03Fjvz90os&t=3s&ab_channel=TheJuliaProgrammingLanguage

00:00 Welcome!
00:20 Conceptual abstract.
00:53 What is finite optimization?
02:03 What is infinite optimization?
02:49 InfiniteOpt's underlying modeling abstraction.
07:30 What is InfiniteOpt.jl and how can I use it?
12:13 Case studies of innovative problem strategies.
16:38 Commentary on extending JuMP.jl.
18:17 Development plans.
18:55 Final remarks.

InfiniteOpt's Webpage: https://github.com/pulsipher/InfiniteOpt.jl
InfiniteOpt's Paper: https://arxiv.org/abs/2106.12689

**Comment by logankilpatrick** [comment]
Added, thank you!
