### ISSUE TITLE
Auto-Parallelization at Cloud Scale with Banyan | Caleb Winston | JuliaCon2021

### ISSUE THREAD

**Issue by clarisw** [JuliaCommunity/YouTubeVideoTimestamps#77]
Video link: https://www.youtube.com/watch?v=Mn7Wf9ezT38

0:00 Welcome!
0:10 Running Julia at Scale is Hard
1:03 Banyan for Julia at Scale
1:15 How Banyan Works
1:51 What does Banyan offer today?
2:11 Example Use-Case
2:22 What's next for Banyan?

**Comment by logankilpatrick** [comment]
Added, thanks!!
