### ISSUE TITLE
Julog.jl: Prolog-like Logic Programming in Julia (JuliaCon2021)

### ISSUE THREAD

**Issue by waldyrious** [JuliaCommunity/YouTubeVideoTimestamps#78]
Video link: https://www.youtube.com/watch?v=FzHML1bbcSU

0:08 Introduction
0:19 Logic Programming
1:45 Logic Programming: Prolog
2:10 Logic Programming: Julog
2:32 Logic Programming: SLD Resolution
3:27 Natural Numbers
3:59 List Operations
4:21 Interpolation Expressions
5:04 Custom Functions
5:45 Performance

**Comment by logankilpatrick** [comment]
Thank you!

**Comment by waldyrious** [comment]
Hmm, looks like the timestamps are clickable in the video description, but not recognized by the system that generates the chapters in the playback timeline itself. After looking around a bit, it seems like the timestamps need to be in the `XX:XX` format rather than the `X:XX` format.

The reason this wasn't an issue in the other short (<10 min) videos where I contributed timestamps (#64, #65 and #67) is because you manually added "0:00 Welcome" at the top of the list of timestamps, which helped YouTube identify it.

Could you add the `0` prefix to the timestamps in this video? Thanks!

**Comment by KZiemian** [comment]
@waldyrious I fixed it. It seems that problem was that `0:08 Introduction` started from time `0:08` not `0:00`.

**Comment by waldyrious** [comment]
Oh! Thanks for catching that, I stand corrected. Indeed the presence of the 0:00 was what was missing, not the double-digit formatting. Not sure how I missed that pattern before :)

That said, would you mind changing the timestamps to say:

> 0:00 Welcome!
> 0:08 Introduction

...to match the other videos?

**Comment by KZiemian** [comment]
No problem to me, but [YT](https://support.google.com/youtube/answer/9884579?hl=en) say that chapter shouldn't be shorter than 10 seconds. Can I write

> 0:00 Welcome!
> 0:10 Introduction

or something like that? Chapters shorter than 10s can work, but I don't want try since YT discoursed them.

**Comment by waldyrious** [comment]
Oh, I didn't know about that guideline! However, it seems that chapters shorter than 10s do work in practice... see here for example: https://www.youtube.com/watch?v=rWQK4mU3jQc

**Comment by KZiemian** [comment]
@waldyrious Yes, I also see chapters shorter that 10s working on YT. At the same time, it official page says they shouldn't be shorter. This is one of this situations, that I just feel split up.

**Comment by waldyrious** [comment]
Yeah, I get it. In the end it doesn't make much difference as it's such a short period of time. I'm okay with leaving the timestamps as they are.

**Comment by KZiemian** [comment]
Yeah, we live them as they are. When they stop working, then we will be thinking about it. In the mean time, there are many things to do on Julia YT channel.
