### ISSUE TITLE
Easy, Featureful Parallelism with Dagger.jl

### ISSUE THREAD

**Issue by plafer** [JuliaCommunity/YouTubeVideoTimestamps#79]
0:00 - Introduction
0:45 - Overview
1:28 - When and why use Dagger instead of Distributed?
2:48 - Coding example
5:17 - A note on Dagger.delayed
5:54 - How does Dagger scheduler work?
6:47 - How is Dagger different from what Distributed.pmap and friends do?
7:18 - Dagger vs Distributed - Dagger is built on top of Distributed
8:12 - Real application demo built on Dagger - security camera monitoring system
22:32 - Dagger feature: distributed arrays
23:05 - Dagger feature: checkpointing
25:25 - Dagger feature: GPU programming with DaggerGPU.jl
25:55 - Future Dagger feature: Distributed tables
26:20 - Future Dagger feature: Task and data scopes
26:57 - Future Dagger feature: Mutable chunks
27:26 - Check the Issues on the Dagger repository for more

**Comment by logankilpatrick** [comment]
Thank you!!
