### ISSUE TITLE
The Julia SciML Ecosystem: Scientific Machine Learning as a Software Problem - Chris Rackauckas

### ISSUE THREAD

**Issue by pitmonticone** [JuliaCommunity/YouTubeVideoTimestamps#81]
### References 

* **Video**: [The Julia SciML Ecosystem: Scientific Machine Learning as a Software Problem](https://youtu.be/XRJ-rtP2fVE)
* **Speaker**: @ChrisRackauckas (@SciML)

### Timestamps 

00:00 Overview 
00:21 Objective: The aim of the SciML ecosystem 
01:24 Definition: What is scientific machine learning
02:45 Example: An application to ocean columns modelling 
07:25 Hard Problem: How to fit a neural network inside a simulator 
10:59 No Silver Bullet: Different adjoint methods for different problems 
13:24 SciML vs. The Rest: A comparison with other libraries in other languages 
14:38 SciML Today: The current state of the SciML ecosystem
15:35 Conclusion: Further developments

**Comment by logankilpatrick** [comment]
Thank you, added!
