### ISSUE TITLE
Modeling Spacecraft Separation Dynamics in Julia - Jonathan Diegelman

### ISSUE THREAD

**Issue by pitmonticone** [JuliaCommunity/YouTubeVideoTimestamps#82]
### References 

* **Video**: [Modeling Spacecraft Separation Dynamics in Julia](https://youtu.be/tQpqsmwlfY0)
* **Speaker**: @jonniedie 

### Timestamps 

00:15 Overview: A case study in tooling for engineering simulations 
01:52 Spacecraft Separation: Problem description and modelling 
04:22 Current Separation Analysis Tool: Flexibility, complexity and efficiency issues
07:49 RECURSAT: Design, requirements and capabilities
12:56 RECURSAT Demo: The ballast placement problem

**Comment by logankilpatrick** [comment]
Thank you!
