### ISSUE TITLE
Differentiable Programming for Quantum Control with SciML - Frank Schäfer

### ISSUE THREAD

**Issue by pitmonticone** [JuliaCommunity/YouTubeVideoTimestamps#83]
### References 

* **Video**: [Differentiable Programming for Quantum Control with SciML](https://youtu.be/uDUwdAqKzYM)
* **Speaker**: @frankschae 

### Timestamps 

00:11 Speaker Presentation: Frank Schäfer
00:33 Overview: Controlling quantum dynamics with SciML
01:07 Example 1: Quantum optimal control in a closed system
04:04 Example 1: The ODE-based learning scheme 
06:14 Sensitivity Analysis: Discrete and continuous options provided by DiffEqSensitivity.jl  
07:36 Example 1: The ODE-based learning process
09:10 Example 2: Quantum optimal control in an open system
11:10 Example 2: The SDE-based learning scheme 
11:35 Example 2: The SDE-based learning process
13:41 Future developments: Combination with parameter estimation from experimental data
14:44 Aknowlegements and References

**Comment by logankilpatrick** [comment]
Done!
