### ISSUE TITLE
Musical Julia | Radhika Ivaturi | JuliaCon2021

### ISSUE THREAD

**Issue by sachholden** [JuliaCommunity/YouTubeVideoTimestamps#84]
Hi Logan

Thanks for all the hard work you are doing to build our Julia community.
I've chosen a special video for my first submission :)
Following feedback from you, I'll work on some others that I've short listed. 

References:
Speaker: Radhika Ivaturi
Video title: Musical Julia | Radhika Ivaturi | JuliaCon2021
Link: https://www.youtube.com/watch?v=S2DgKcndHr0
Link to the code: https://github.com/RadsPad7/MusicalJulia

Contents
0:00 Welcome
0:10 Musical Julia - The Journey
0:38 The Little Book Of Julia Algorithms
0:47 Introduction to Western and Indian Musical Notation
1:30 Musical Julia - Understanding the problem
1:17 Musical Julia - Solving the problem using an if-else loop
1:26 Additional learning: Arrays, push, file writing & reading
1:36 Musical Julia - Current Status
1:51 Musical Julia - Roadmap: App, Sheet Music reader
2:30 Musical Julia - Acknowledgements to all who helped and Juliacon community & organizers
2:23 Musical Julia - Code run through
2:33 Musical Julia - Github link to the code: github.com/RadsPad7/MusicalJulia

**Comment by logankilpatrick** [comment]
This is very well done, thank you!!!
