### ISSUE TITLE
Accelerating Scientific Machine Learning with Automatic Differentiable Surrogates - Ludovico Bessi

### ISSUE THREAD

**Issue by pitmonticone** [JuliaCommunity/YouTubeVideoTimestamps#85]
### References 

* **Video**: [Accelerating Scientific Machine Learning with Automatic Differentiable Surrogates](https://youtu.be/QlOwlPNlVNo)
* **Speaker**: @ludoro 

### Timestamps 

00:00 Speaker Presentation: Ludovico Bessi
00:55 Overview
01:04 Objective of Surrogates.jl: Approximate an expansive function
03:19 Main features of Surrogates.jl: Sampling, surrogate models and optimization methods
04:36 Code Examples
07:09 Future directions: More methods and harder problems

**Comment by logankilpatrick** [comment]
Added!
