### ISSUE TITLE
Automated Solution of Symbolic Partial Differential Equations via Physics-Informed Neural Networks

### ISSUE THREAD

**Issue by pitmonticone** [JuliaCommunity/YouTubeVideoTimestamps#86]
### References 

* **Video**: [Automated Solution of Symbolic Partial Differential Equations via Physics-Informed Neural Networks](https://youtu.be/DS3CZ_gVAMs)
* **Speaker**: @KirillZubov (@SciML)

### Timestamps 

00:00 Speaker Presentation: Kirill Zubov
00:39 Overview: NeuralPDE.jl
01:33 Objective: Solving PDEs via physics-informed neural networks 
02:11 Neural PDEs: The learning scheme
03:09 Example 1: 2D Poisson equation 
06:13 Example 2: 3D PDE with GPU
08:00 Performance Benchmarks: 3D PDE with CPU vs. GPU

**Comment by logankilpatrick** [comment]
Done, thanks!
