### ISSUE TITLE
Modeling Biochemical Systems with Catalyst.jl - Samuel Isaacson

### ISSUE THREAD

**Issue by pitmonticone** [JuliaCommunity/YouTubeVideoTimestamps#87]
### References 

* Video: [Modeling Biochemical Systems with Catalyst.jl](https://youtu.be/5p1PJE5A5Jw)
* Speaker: @isaacsas (@SciML)

### Timestamps 

00:00 Aknowledgements and References: Catalyst.jl, ModelingToolkit.jl and contributors
00:26 Overview: What is Catalyst.jl 
01:18 Example: A simple repressilator model
02:33 Objective: Why you Catalyst.jl 
04:36 Example: How to generate an ODE model
05:15 Example: How to solve an ODE model
05:51 Example: How to generate a jump model
07:52 Example: General Julia functions work as rate laws
09:22 Example: How to programmatically construct networks or network components 
11:43 Example: How to import and solve larger networks
13:44 DiffEqJump SSA Methods
15:20 Future Plans: Compositional models, network analysis and more

**Comment by logankilpatrick** [comment]
Thank you!
