### ISSUE TITLE
Automatic Numerical Bifurcation Analysis with Applications to Neurosciences with BifurcationKit

### ISSUE THREAD

**Issue by pitmonticone** [JuliaCommunity/YouTubeVideoTimestamps#88]
### References 

* Video: [Automatic Numerical Bifurcation Analysis with Applications to Neurosciences with BifurcationKit](https://youtu.be/PvZNLkvxTgY)
* Speaker: @rveltz 

### Timestamps 

00:00 Speaker Presentation: Romain Veltz 
00:26 Overview
01:46 Objective of BifurcationKit.jl: Numerical bifurcation analysis of large dimensional equations
03:01 Motivation for BifurcationKit.jl: New efficient algorithms for large problems taking advantage of the Julia ecosystem
04:43 Continuation Algorithms: Deflated continuation (DC) vs. pseudo arc-length continuation (PALC)
08:35 PALC: Towards automatic bifurcation diagrams 
11:27 Example: Semi automatic bifurcation diagram entirely on GPU 
13:15 Main Features of BifurcationKit.jl
14:18 Conclusion and Future Developments

**Comment by logankilpatrick** [comment]
Thank you!

**Comment by rveltz** [comment]
Thanks
