### ISSUE TITLE
Mixed Feedbacks and Noise, How Bacteria Modulate their Stress Response - Torkel Loman

### ISSUE THREAD

**Issue by pitmonticone** [JuliaCommunity/YouTubeVideoTimestamps#89]
### References 

* Video: [Mixed Feedbacks and Noise, How Bacteria Modulate their Stress Response](https://youtu.be/92H_jJDdMwA)
* Speaker: @TorkelE (@SciML) 

### Timestamps 

00:00 Speaker Presentation
00:13 Overview: A general model of bacterial stress response 
00:33 Stress Response: How sigma-factors regulate bacterial stress response 
02:31 General Dynamics: How to model a general sigma-factor circuit
04:39 Stochastic Pulsing: Experimentally observed sigma-factor behaviour
08:08 Behavioural Complexity: Classification of all response types 
09:16 Behavioral Phases: Parameter space characterization for model validation and application to synthetic biology  
13:54 Conclusion: Acknowledgements and references

**Comment by logankilpatrick** [comment]
Thank you, added!
