### ISSUE TITLE
Simplifying Delays in Systems Biology | Julia SciML | SIAM CSE 2021 | Niklas Korsbo

### ISSUE THREAD

**Issue by pitmonticone** [JuliaCommunity/YouTubeVideoTimestamps#90]
### References 

* Video: [Simplifying Delays in Systems Biology](https://youtu.be/DcVeaIOx1S0)
* Speaker: @korsbo (@SciML) 

### Timestamps 

00:00 Speaker Presentation: Niklas Korsbo
00:48 Big Picture: A conceptual introduction to mathematical modeling for systems biology
02:40 Linear Pathways: Chains of events are ubiquitous in systems biology
03:15 Modeling Challange: How to effectively simplify linear pathways  
05:34 Output Dynamics: Characterising the "sharpness" of the delay distribution
08:34 Alternative Semplification: Fixing rates while tuning the pathway length
11:16 Better Simplification: From Erlang to Gamma distributed delay
12:21 Summary: What we've done and what we've obtained 
15:24 Conclusion: Distributed delays are high-fidelity simplification of linear pathways 
17:02 Acknowledgement and References

**Comment by logankilpatrick** [comment]
Done, thanks very much for all of these!
